// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>This object provides the bell schedule information for a school and school year, including timetable days, periods and bell schedules.</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class BellSchedule : SifDataObject
{
	/// <summary>
	/// Creates an instance of a BellSchedule
	/// </summary>
	public BellSchedule() : base( Adk.SifVersion, StudentDTD.BELLSCHEDULE ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="refId">The Id (GUID) that uniquely identifies the object. </param>
	///<param name="schoolInfoRefId">The Id (GUID) that uniquely identifies the school to which this bell schedule information applies</param>
	///<param name="schoolYear">School year for which the information is applicable, expressed as the four-digit year in which the school year ends (e.g., "2007" for the 2006-07 school year).</param>
	///<param name="bellScheduleName">A name that uniquely identifies a particular BellSchedule from others for the same school and year.</param>
	///<param name="timetableDayList">The timetable days for this school year bell schedule. This essentially provides a list of the time day identifiers that are used in the BellPeriod definitions below with some additional properties for each. The identifiers defined here may be referenced by other objects / elements like MeetingTime.</param>
	///<param name="timetablePeriodList">The timetable periods for this school year bell schedule. This essentially provides a list of the time period identifiers that are used in the BellPeriod definitions below with some addition properties for each. The identifiers defined here may be referenced by other objects / elements like MeetingTime.</param>
	///<param name="bellPeriodList">The bell periods for this school year bell schedule.</param>
	///
	public BellSchedule( string refId, string schoolInfoRefId, int? schoolYear, string bellScheduleName, TimetableDay timetableDayList, TimetablePeriod timetablePeriodList, BellPeriod bellPeriodList ) : base( Adk.SifVersion, StudentDTD.BELLSCHEDULE )
	{
		this.RefId = refId;
		this.SchoolInfoRefId = schoolInfoRefId;
		this.SchoolYear = schoolYear;
		this.BellScheduleName = bellScheduleName;
		this.TimetableDayList =  new TimetableDayList( timetableDayList );
		this.TimetablePeriodList =  new TimetablePeriodList( timetablePeriodList );
		this.BellPeriodList =  new BellPeriodList( bellPeriodList );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected BellSchedule( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { StudentDTD.BELLSCHEDULE_REFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>RefId</c> attribute.
	/// </summary>
	/// <value> The <c>RefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The Id (GUID) that uniquely identifies the object. "</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public override string RefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.BELLSCHEDULE_REFID ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.BELLSCHEDULE_REFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SchoolInfoRefId&gt;</c> element.
	/// </summary>
	/// <value> The <c>SchoolInfoRefId</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The Id (GUID) that uniquely identifies the school to which this bell schedule information applies"</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string SchoolInfoRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.BELLSCHEDULE_SCHOOLINFOREFID ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.BELLSCHEDULE_SCHOOLINFOREFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SchoolYear&gt;</c> element.
	/// </summary>
	/// <value> The <c>SchoolYear</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "School year for which the information is applicable, expressed as the four-digit year in which the school year ends (e.g., "2007" for the 2006-07 school year)."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public int? SchoolYear
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.BELLSCHEDULE_SCHOOLYEAR ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.BELLSCHEDULE_SCHOOLYEAR, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;BellScheduleName&gt;</c> element.
	/// </summary>
	/// <value> The <c>BellScheduleName</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "A name that uniquely identifies a particular BellSchedule from others for the same school and year."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string BellScheduleName
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.BELLSCHEDULE_BELLSCHEDULENAME ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.BELLSCHEDULE_BELLSCHEDULENAME, new SifString( value ), value );
		}
	}

	///<summary>Sets the value of the <c>&lt;TimetableDayList&gt;</c> element.</summary>
	/// <param name="TimetableDay">An entry for each unique timetable day</param>
	///<remarks>
	/// <para>This form of <c>setTimetableDayList</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>TimetableDayList</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetTimetableDayList( TimetableDay TimetableDay ) {
		RemoveChild( StudentDTD.BELLSCHEDULE_TIMETABLEDAYLIST);
		AddChild( StudentDTD.BELLSCHEDULE_TIMETABLEDAYLIST, new TimetableDayList( TimetableDay ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;TimetableDayList&gt;</c> element.
	/// </summary>
	/// <value> A TimetableDayList </value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this null as: "The timetable days for this school year bell schedule. This essentially provides a list of the time day identifiers that are used in the BellPeriod definitions below with some additional properties for each. The identifiers defined here may be referenced by other objects / elements like MeetingTime."</para>
	/// <para>To remove the <c>TimetableDayList</c>, set <c>TimetableDayList</c> to <c>null</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public TimetableDayList TimetableDayList
	{
		get
		{
			return (TimetableDayList)GetChild( StudentDTD.BELLSCHEDULE_TIMETABLEDAYLIST);
		}
		set
		{
			RemoveChild( StudentDTD.BELLSCHEDULE_TIMETABLEDAYLIST);
			if( value != null)
			{
				AddChild( StudentDTD.BELLSCHEDULE_TIMETABLEDAYLIST, value );
			}
		}
	}

	///<summary>Sets the value of the <c>&lt;TimetablePeriodList&gt;</c> element.</summary>
	/// <param name="TimetablePeriod">An entry for each unique timetable period</param>
	///<remarks>
	/// <para>This form of <c>setTimetablePeriodList</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>TimetablePeriodList</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetTimetablePeriodList( TimetablePeriod TimetablePeriod ) {
		RemoveChild( StudentDTD.BELLSCHEDULE_TIMETABLEPERIODLIST);
		AddChild( StudentDTD.BELLSCHEDULE_TIMETABLEPERIODLIST, new TimetablePeriodList( TimetablePeriod ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;TimetablePeriodList&gt;</c> element.
	/// </summary>
	/// <value> A TimetablePeriodList </value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this null as: "The timetable periods for this school year bell schedule. This essentially provides a list of the time period identifiers that are used in the BellPeriod definitions below with some addition properties for each. The identifiers defined here may be referenced by other objects / elements like MeetingTime."</para>
	/// <para>To remove the <c>TimetablePeriodList</c>, set <c>TimetablePeriodList</c> to <c>null</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public TimetablePeriodList TimetablePeriodList
	{
		get
		{
			return (TimetablePeriodList)GetChild( StudentDTD.BELLSCHEDULE_TIMETABLEPERIODLIST);
		}
		set
		{
			RemoveChild( StudentDTD.BELLSCHEDULE_TIMETABLEPERIODLIST);
			if( value != null)
			{
				AddChild( StudentDTD.BELLSCHEDULE_TIMETABLEPERIODLIST, value );
			}
		}
	}

	///<summary>Sets the value of the <c>&lt;BellPeriodList&gt;</c> element.</summary>
	/// <param name="BellPeriod">An entry for each unique bell period for the bell schedule</param>
	///<remarks>
	/// <para>This form of <c>setBellPeriodList</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>BellPeriodList</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetBellPeriodList( BellPeriod BellPeriod ) {
		RemoveChild( StudentDTD.BELLSCHEDULE_BELLPERIODLIST);
		AddChild( StudentDTD.BELLSCHEDULE_BELLPERIODLIST, new BellPeriodList( BellPeriod ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;BellPeriodList&gt;</c> element.
	/// </summary>
	/// <value> A BellPeriodList </value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this null as: "The bell periods for this school year bell schedule."</para>
	/// <para>To remove the <c>BellPeriodList</c>, set <c>BellPeriodList</c> to <c>null</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public BellPeriodList BellPeriodList
	{
		get
		{
			return (BellPeriodList)GetChild( StudentDTD.BELLSCHEDULE_BELLPERIODLIST);
		}
		set
		{
			RemoveChild( StudentDTD.BELLSCHEDULE_BELLPERIODLIST);
			if( value != null)
			{
				AddChild( StudentDTD.BELLSCHEDULE_BELLPERIODLIST, value );
			}
		}
	}

}}
