// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>Information regarding the action(s) taken in response to the incident.</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class IncidentAction : SifElement
{
	/// <summary>
	/// Creates an instance of an IncidentAction
	/// </summary>
	public IncidentAction() : base ( StudentDTD.INCIDENTACTION ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="startDate">The date on which the action begins.</param>
	///<param name="endDate">The date through which the action is in effect, inclusive.</param>
	///<param name="duration">Identifies the length, in school days, of the action. Note: decimal places may be used for fractions of school days.</param>
	///<param name="zeroTolerance">Identifies whether or not this action was imposed as a consequence of state or local zero tolerance policies.</param>
	///<param name="policeNotification">Identifies whether there was notification of local law enforcement, regardless of whether official action was taken.</param>
	///<param name="arrest">Identifies whether there were any arrests.</param>
	///
	public IncidentAction( DateTime? startDate, DateTime? endDate, decimal? duration, YesNo zeroTolerance, YesNo policeNotification, IncidentActionArrestType arrest ) : base( StudentDTD.INCIDENTACTION )
	{
		this.StartDate = startDate;
		this.EndDate = endDate;
		this.Duration = duration;
		this.SetZeroTolerance( zeroTolerance );
		this.SetPoliceNotification( policeNotification );
		this.SetArrest( arrest );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected IncidentAction( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { StudentDTD.INCIDENTACTION_STARTDATE, StudentDTD.INCIDENTACTION_ENDDATE, StudentDTD.INCIDENTACTION_DURATION, StudentDTD.INCIDENTACTION_ZEROTOLERANCE, StudentDTD.INCIDENTACTION_POLICENOTIFICATION, StudentDTD.INCIDENTACTION_ARREST }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;StartDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>StartDate</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The date on which the action begins."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public DateTime? StartDate
	{
		get
		{
			return (DateTime?) GetSifSimpleFieldValue( StudentDTD.INCIDENTACTION_STARTDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.INCIDENTACTION_STARTDATE, new SifDate( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EndDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>EndDate</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The date through which the action is in effect, inclusive."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public DateTime? EndDate
	{
		get
		{
			return (DateTime?) GetSifSimpleFieldValue( StudentDTD.INCIDENTACTION_ENDDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.INCIDENTACTION_ENDDATE, new SifDate( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Duration&gt;</c> element.
	/// </summary>
	/// <value> The <c>Duration</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies the length, in school days, of the action. Note: decimal places may be used for fractions of school days."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public decimal? Duration
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( StudentDTD.INCIDENTACTION_DURATION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.INCIDENTACTION_DURATION, new SifDecimal( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ZeroTolerance&gt;</c> element.
	/// </summary>
	/// <value> The <c>ZeroTolerance</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies whether or not this action was imposed as a consequence of state or local zero tolerance policies."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ZeroTolerance
	{
		get
		{ 
			return GetFieldValue( StudentDTD.INCIDENTACTION_ZEROTOLERANCE );
		}
		set
		{
			SetField( StudentDTD.INCIDENTACTION_ZEROTOLERANCE, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;ZeroTolerance&gt;</c> element.
	/// </summary>
	/// <param name="val">A YesNo object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies whether or not this action was imposed as a consequence of state or local zero tolerance policies."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetZeroTolerance( YesNo val )
	{
		SetField( StudentDTD.INCIDENTACTION_ZEROTOLERANCE, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;PoliceNotification&gt;</c> element.
	/// </summary>
	/// <value> The <c>PoliceNotification</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies whether there was notification of local law enforcement, regardless of whether official action was taken."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string PoliceNotification
	{
		get
		{ 
			return GetFieldValue( StudentDTD.INCIDENTACTION_POLICENOTIFICATION );
		}
		set
		{
			SetField( StudentDTD.INCIDENTACTION_POLICENOTIFICATION, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;PoliceNotification&gt;</c> element.
	/// </summary>
	/// <param name="val">A YesNo object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies whether there was notification of local law enforcement, regardless of whether official action was taken."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetPoliceNotification( YesNo val )
	{
		SetField( StudentDTD.INCIDENTACTION_POLICENOTIFICATION, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Arrest&gt;</c> element.
	/// </summary>
	/// <value> The <c>Arrest</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies whether there were any arrests."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Arrest
	{
		get
		{ 
			return GetFieldValue( StudentDTD.INCIDENTACTION_ARREST );
		}
		set
		{
			SetField( StudentDTD.INCIDENTACTION_ARREST, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;Arrest&gt;</c> element.
	/// </summary>
	/// <param name="val">A IncidentActionArrestType object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies whether there were any arrests."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetArrest( IncidentActionArrestType val )
	{
		SetField( StudentDTD.INCIDENTACTION_ARREST, val );
	}

}}
