// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.us.Student
{
	///<summary>
	/// Defines the set of values that can be specified whenever an IncidentCodeType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  an IncidentCodeType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	[Serializable]
	public class IncidentCodeType : SifEnum
	{
	/// <summary>Other nonsexual harassment ("1897")</summary>
	public static readonly IncidentCodeType C1049_1897 = new IncidentCodeType("1897");

	/// <summary>Obscene electronic communication ("2440")</summary>
	public static readonly IncidentCodeType C1049_2440 = new IncidentCodeType("2440");

	/// <summary>Truancy ("1240")</summary>
	public static readonly IncidentCodeType C1049_1240 = new IncidentCodeType("1240");

	/// <summary>Possession of tobacco ("3340")</summary>
	public static readonly IncidentCodeType C1049_3340 = new IncidentCodeType("3340");

	/// <summary>Other school threat ("2797")</summary>
	public static readonly IncidentCodeType C1049_2797 = new IncidentCodeType("2797");

	/// <summary>Other drug offense ("1697")</summary>
	public static readonly IncidentCodeType C1049_1697 = new IncidentCodeType("1697");

	/// <summary>Chemical/biological threat ("2730")</summary>
	public static readonly IncidentCodeType C1049_2730 = new IncidentCodeType("2730");

	/// <summary>Distribution of illegal drug ("1630")</summary>
	public static readonly IncidentCodeType C1049_1630 = new IncidentCodeType("1630");

	/// <summary>Electronic threat ("3240")</summary>
	public static readonly IncidentCodeType C1049_3240 = new IncidentCodeType("3240");

	/// <summary>Possession of medication in violation of school rules ("2140")</summary>
	public static readonly IncidentCodeType C1049_2140 = new IncidentCodeType("2140");

	/// <summary>Possession of alcohol ("1040")</summary>
	public static readonly IncidentCodeType C1049_1040 = new IncidentCodeType("1040");

	/// <summary>Other vandalism ("3597")</summary>
	public static readonly IncidentCodeType C1049_3597 = new IncidentCodeType("3597");

	/// <summary>Other obscene behavior ("2497")</summary>
	public static readonly IncidentCodeType C1049_2497 = new IncidentCodeType("2497");

	/// <summary>Drawing obscene pictures ("2430")</summary>
	public static readonly IncidentCodeType C1049_2430 = new IncidentCodeType("2430");

	/// <summary>Hazing ("1820")</summary>
	public static readonly IncidentCodeType C1049_1820 = new IncidentCodeType("1820");

	/// <summary>Other attendance policy violation ("1297")</summary>
	public static readonly IncidentCodeType C1049_1297 = new IncidentCodeType("1297");

	/// <summary>Tardiness ("1230")</summary>
	public static readonly IncidentCodeType C1049_1230 = new IncidentCodeType("1230");

	/// <summary>Other tobacco offense ("3397")</summary>
	public static readonly IncidentCodeType C1049_3397 = new IncidentCodeType("3397");

	/// <summary>Use of tobacco ("3330")</summary>
	public static readonly IncidentCodeType C1049_3330 = new IncidentCodeType("3330");

	/// <summary>Alcohol (liquor law violations: possession, use, sale) ("1000")</summary>
	public static readonly IncidentCodeType C1049_1000_ALCOHOL = new IncidentCodeType("1000");

	/// <summary>Fire alarm ("2720")</summary>
	public static readonly IncidentCodeType C1049_2720 = new IncidentCodeType("2720");

	/// <summary>Sale of substance represented as an illegal drug ("1620")</summary>
	public static readonly IncidentCodeType C1049_1620 = new IncidentCodeType("1620");

	/// <summary>Other threat ("3297")</summary>
	public static readonly IncidentCodeType C1049_3297 = new IncidentCodeType("3297");

	/// <summary>Other inappropriate use of medication ("2197")</summary>
	public static readonly IncidentCodeType C1049_2197 = new IncidentCodeType("2197");

	/// <summary>Written threat ("3230")</summary>
	public static readonly IncidentCodeType C1049_3230 = new IncidentCodeType("3230");

	/// <summary>Other alcohol ("1097")</summary>
	public static readonly IncidentCodeType C1049_1097 = new IncidentCodeType("1097");

	/// <summary>Use of medication in violation of school rules ("2130")</summary>
	public static readonly IncidentCodeType C1049_2130 = new IncidentCodeType("2130");

	/// <summary>Drinking alcohol ("1030")</summary>
	public static readonly IncidentCodeType C1049_1030 = new IncidentCodeType("1030");

	/// <summary>Suspicion of use ("1680")</summary>
	public static readonly IncidentCodeType C1049_1680 = new IncidentCodeType("1680");

	/// <summary>Other theft ("3197")</summary>
	public static readonly IncidentCodeType C1049_3197 = new IncidentCodeType("3197");

	/// <summary>Other suicide offense ("3097")</summary>
	public static readonly IncidentCodeType C1049_3097 = new IncidentCodeType("3097");

	/// <summary>Vandalism of personal property ("3520")</summary>
	public static readonly IncidentCodeType C1049_3520 = new IncidentCodeType("3520");

	/// <summary>Obscene written messages ("2420")</summary>
	public static readonly IncidentCodeType C1049_2420 = new IncidentCodeType("2420");

	/// <summary>Bullying ("1810")</summary>
	public static readonly IncidentCodeType C1049_1810 = new IncidentCodeType("1810");

	/// <summary>Sale of alcohol ("1010")</summary>
	public static readonly IncidentCodeType C1049_1010_SALE_ALCOHOL = new IncidentCodeType("1010");

	/// <summary>Skipping class ("1220")</summary>
	public static readonly IncidentCodeType C1049_1220 = new IncidentCodeType("1220");

	/// <summary>Distribution of alcohol ("1020")</summary>
	public static readonly IncidentCodeType C1049_1020_DISTRIBUTION_ALCOHOL = new IncidentCodeType("1020");

	/// <summary>Distribution of tobacco ("3320")</summary>
	public static readonly IncidentCodeType C1049_3320 = new IncidentCodeType("3320");

	/// <summary>Bomb threat ("2710")</summary>
	public static readonly IncidentCodeType C1049_2710 = new IncidentCodeType("2710");

	/// <summary>Sale of illegal drug ("1610")</summary>
	public static readonly IncidentCodeType C1049_1610 = new IncidentCodeType("1610");

	/// <summary>Verbal threat ("3220")</summary>
	public static readonly IncidentCodeType C1049_3220 = new IncidentCodeType("3220");

	/// <summary>Distribution of medication ("2120")</summary>
	public static readonly IncidentCodeType C1049_2120 = new IncidentCodeType("2120");

	/// <summary>Possession of drug paraphernalia ("1670")</summary>
	public static readonly IncidentCodeType C1049_1670 = new IncidentCodeType("1670");

	/// <summary>General theft, Other entity ("3120")</summary>
	public static readonly IncidentCodeType C1049_3120 = new IncidentCodeType("3120");

	/// <summary>Harassment, Sexual (Unwelcome Sexual Contact) ("1900")</summary>
	public static readonly IncidentCodeType C1049_1900 = new IncidentCodeType("1900");

	/// <summary>Attempted suicide ("3020")</summary>
	public static readonly IncidentCodeType C1049_3020 = new IncidentCodeType("3020");

	/// <summary>Vandalism of school property ("3510")</summary>
	public static readonly IncidentCodeType C1049_3510 = new IncidentCodeType("3510");

	/// <summary>Displays of affection in violation of school policy ("2410")</summary>
	public static readonly IncidentCodeType C1049_2410 = new IncidentCodeType("2410");

	/// <summary>Sexual Offenses, Other (Lewd Behavior, Indecent Exposure) ("2900")</summary>
	public static readonly IncidentCodeType C1049_2900 = new IncidentCodeType("2900");

	/// <summary>Harassment, Nonsexual (Physical, Verbal, or Psychological) ("1800")</summary>
	public static readonly IncidentCodeType C1049_1800 = new IncidentCodeType("1800");

	/// <summary>Sexual Battery (Sexual Assault) ("2800")</summary>
	public static readonly IncidentCodeType C1049_2800 = new IncidentCodeType("2800");

	/// <summary>Forging absence excuse ("1210")</summary>
	public static readonly IncidentCodeType C1049_1210 = new IncidentCodeType("1210");

	/// <summary>Fighting (Mutual Altercation) ("1700")</summary>
	public static readonly IncidentCodeType C1049_1700 = new IncidentCodeType("1700");

	/// <summary>Sale of tobacco ("3310")</summary>
	public static readonly IncidentCodeType C1049_3310 = new IncidentCodeType("3310");

	/// <summary>School Threat (Threat of Destruction or Harm) ("2700")</summary>
	public static readonly IncidentCodeType C1049_2700 = new IncidentCodeType("2700");

	/// <summary>Drugs Excluding Alcohol and Tobacco (Illegal Drug Possession, Sale, Use/Under the Influence) ("1600")</summary>
	public static readonly IncidentCodeType C1049_1600 = new IncidentCodeType("1600");

	/// <summary>Physical threat ("3210")</summary>
	public static readonly IncidentCodeType C1049_3210 = new IncidentCodeType("3210");

	/// <summary>Weapons Possession (Firearms and Other Weapons) ("3700")</summary>
	public static readonly IncidentCodeType C1049_3700 = new IncidentCodeType("3700");

	/// <summary>Sale of medication ("2110")</summary>
	public static readonly IncidentCodeType C1049_2110 = new IncidentCodeType("2110");

	/// <summary>Possession of illegal drug ("1660")</summary>
	public static readonly IncidentCodeType C1049_1660 = new IncidentCodeType("1660");

	/// <summary>Robbery (Taking of Things by Force) ("2600")</summary>
	public static readonly IncidentCodeType C1049_2600 = new IncidentCodeType("2600");

	/// <summary>Disorderly Conduct (Disruptive Behavior) ("1500")</summary>
	public static readonly IncidentCodeType C1049_1500 = new IncidentCodeType("1500");

	/// <summary>General theft, Person ("3110")</summary>
	public static readonly IncidentCodeType C1049_3110 = new IncidentCodeType("3110");

	/// <summary>Violation of School Rules (Disobeying School Policy) ("3600")</summary>
	public static readonly IncidentCodeType C1049_3600 = new IncidentCodeType("3600");

	/// <summary>Physical Altercation, Minor (Pushing, Shoving) ("2500")</summary>
	public static readonly IncidentCodeType C1049_2500 = new IncidentCodeType("2500");

	/// <summary>Burglary/Breaking and Entering (Stealing Property/Unlawful Entry) ("1400")</summary>
	public static readonly IncidentCodeType C1049_1400 = new IncidentCodeType("1400");

	/// <summary>Suicide ("3010")</summary>
	public static readonly IncidentCodeType C1049_3010 = new IncidentCodeType("3010");

	/// <summary>Vandalism (Damage to School or Personal Property) ("3500")</summary>
	public static readonly IncidentCodeType C1049_3500 = new IncidentCodeType("3500");

	/// <summary>Obscene Behavior ("2400")</summary>
	public static readonly IncidentCodeType C1049_2400 = new IncidentCodeType("2400");

	/// <summary>Battery (Physical Attack/Harm) ("1300")</summary>
	public static readonly IncidentCodeType C1049_1300 = new IncidentCodeType("1300");

	/// <summary>Trespassing (Unlawful or Unauthorized Presence) ("3400")</summary>
	public static readonly IncidentCodeType C1049_3400 = new IncidentCodeType("3400");

	/// <summary>Obscene language/profanity ("2460")</summary>
	public static readonly IncidentCodeType C1049_2460 = new IncidentCodeType("2460");

	/// <summary>Kidnapping (Abduction) ("2300")</summary>
	public static readonly IncidentCodeType C1049_2300 = new IncidentCodeType("2300");

	/// <summary>Attendance Policy Violation (Not Attending School or Classes as Required) ("1200")</summary>
	public static readonly IncidentCodeType C1049_1200 = new IncidentCodeType("1200");

	/// <summary>Tobacco (Possession or Use) ("3300")</summary>
	public static readonly IncidentCodeType C1049_3300 = new IncidentCodeType("3300");

	/// <summary>Insubordination (Disobedience) ("2200")</summary>
	public static readonly IncidentCodeType C1049_2200 = new IncidentCodeType("2200");

	/// <summary>Arson (Setting a Fire) ("1100")</summary>
	public static readonly IncidentCodeType C1049_1100 = new IncidentCodeType("1100");

	/// <summary>Threat/Intimidation (Causing Fear of Harm) ("3200")</summary>
	public static readonly IncidentCodeType C1049_3200 = new IncidentCodeType("3200");

	/// <summary>Inappropriate Use of Medication (Prescription or over-the-counter) ("2100")</summary>
	public static readonly IncidentCodeType C1049_2100 = new IncidentCodeType("2100");

	/// <summary>Use of illegal drug ("1650")</summary>
	public static readonly IncidentCodeType C1049_1650 = new IncidentCodeType("1650");

	/// <summary>Theft (Stealing Personal or Other Property) ("3100")</summary>
	public static readonly IncidentCodeType C1049_3100 = new IncidentCodeType("3100");

	/// <summary>Homicide (Murder or Manslaughter) ("2000")</summary>
	public static readonly IncidentCodeType C1049_2000 = new IncidentCodeType("2000");

	/// <summary>Suicide ("3000")</summary>
	public static readonly IncidentCodeType C1049_3000 = new IncidentCodeType("3000");

	/// <summary>Obscene gestures ("2450")</summary>
	public static readonly IncidentCodeType C1049_2450 = new IncidentCodeType("2450");

	/// <summary>Suspicion of use of tobacco ("3350")</summary>
	public static readonly IncidentCodeType C1049_3350 = new IncidentCodeType("3350");

	/// <summary>Terroristic threat ("2740")</summary>
	public static readonly IncidentCodeType C1049_2740 = new IncidentCodeType("2740");

	/// <summary>Distribution of substance represented as an illegal drug ("1640")</summary>
	public static readonly IncidentCodeType C1049_1640 = new IncidentCodeType("1640");

	/// <summary>Suspicion of use of medication in violation of school rules ("2150")</summary>
	public static readonly IncidentCodeType C1049_2150 = new IncidentCodeType("2150");

	/// <summary>Suspicion of alcohol use ("1050")</summary>
	public static readonly IncidentCodeType C1049_1050 = new IncidentCodeType("1050");

	/// <summary>Other Offenses (e.g., Forgery, Extortion) ("9000")</summary>
	public static readonly IncidentCodeType C1049_9000 = new IncidentCodeType("9000");

	///<summary>Wrap an arbitrary string value in an IncidentCodeType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static IncidentCodeType Wrap( String wrappedValue ) {
		return new IncidentCodeType( wrappedValue );
	}

	private IncidentCodeType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
