// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A LocationOfInstruction</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 1.1</para>
/// </remarks>
[Serializable]
public class LocationOfInstruction : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of a LocationOfInstruction
	/// </summary>
	public LocationOfInstruction() : base ( StudentDTD.LOCATIONOFINSTRUCTION ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="code">Code representing the location of instruction.</param>
	///
	public LocationOfInstruction( LocationOfInstructionCode code ) : base( StudentDTD.LOCATIONOFINSTRUCTION )
	{
		this.SetCode( code );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected LocationOfInstruction( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { StudentDTD.LOCATIONOFINSTRUCTION_CODE }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>Code</c> attribute.
	/// </summary>
	/// <value> The <c>Code</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "Code representing the location of instruction."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public string Code
	{
		get
		{ 
			return GetFieldValue( StudentDTD.LOCATIONOFINSTRUCTION_CODE );
		}
		set
		{
			SetField( StudentDTD.LOCATIONOFINSTRUCTION_CODE, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>Code</c> attribute.
	/// </summary>
	/// <param name="val">A LocationOfInstructionCode object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "Code representing the location of instruction."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public void SetCode( LocationOfInstructionCode val )
	{
		SetField( StudentDTD.LOCATIONOFINSTRUCTION_CODE, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;OtherCodeList&gt;</c> element.
	/// </summary>
	/// <value> An OtherCodeList </value>
	/// <remarks>
	/// <para>To remove the <c>OtherCodeList</c>, set <c>OtherCodeList</c> to <c>null</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public OtherCodeList OtherCodeList
	{
		get
		{
			return (OtherCodeList)GetChild( StudentDTD.LOCATIONOFINSTRUCTION_OTHERCODELIST);
		}
		set
		{
			RemoveChild( StudentDTD.LOCATIONOFINSTRUCTION_OTHERCODELIST);
			if( value != null)
			{
				AddChild( StudentDTD.LOCATIONOFINSTRUCTION_OTHERCODELIST, value );
			}
		}
	}

}}
