// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>This element is mutually exclusive with Promotion, and its child elements should only be populated if the value of PromotionStatus is "Retained" or "Demoted".</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class Nonpromotion : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of a Nonpromotion
	/// </summary>
	public Nonpromotion() : base ( StudentDTD.NONPROMOTION ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="code">The reason the student was not promoted. This element should only be populated if the value of PromotionStatus is "Promoted".</param>
	///
	public Nonpromotion( NCES0673NonpromotionReason code ) : base( StudentDTD.NONPROMOTION )
	{
		this.SetCode( code );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Nonpromotion( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { StudentDTD.NONPROMOTION_CODE }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Code&gt;</c> element.
	/// </summary>
	/// <value> The <c>Code</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The reason the student was not promoted. This element should only be populated if the value of PromotionStatus is "Promoted"."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Code
	{
		get
		{ 
			return GetFieldValue( StudentDTD.NONPROMOTION_CODE );
		}
		set
		{
			SetField( StudentDTD.NONPROMOTION_CODE, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;Code&gt;</c> element.
	/// </summary>
	/// <param name="val">A NCES0673NonpromotionReason object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The reason the student was not promoted. This element should only be populated if the value of PromotionStatus is "Promoted"."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetCode( NCES0673NonpromotionReason val )
	{
		SetField( StudentDTD.NONPROMOTION_CODE, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;OtherCodeList&gt;</c> element.
	/// </summary>
	/// <value> An OtherCodeList </value>
	/// <remarks>
	/// <para>To remove the <c>OtherCodeList</c>, set <c>OtherCodeList</c> to <c>null</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public OtherCodeList OtherCodeList
	{
		get
		{
			return (OtherCodeList)GetChild( StudentDTD.NONPROMOTION_OTHERCODELIST);
		}
		set
		{
			RemoveChild( StudentDTD.NONPROMOTION_OTHERCODELIST);
			if( value != null)
			{
				AddChild( StudentDTD.NONPROMOTION_OTHERCODELIST, value );
			}
		}
	}

}}
