// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A SCEDCode</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class SCEDCode : SifElement
{
	/// <summary>
	/// Creates an instance of a SCEDCode
	/// </summary>
	public SCEDCode() : base ( StudentDTD.SCEDCODE ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected SCEDCode( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;CourseDescription&gt;</c> element.
	/// </summary>
	/// <value> The <c>CourseDescription</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string CourseDescription
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCEDCODE_COURSEDESCRIPTION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCEDCODE_COURSEDESCRIPTION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;CourseLevel&gt;</c> element.
	/// </summary>
	/// <value> The <c>CourseLevel</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Conveys the level of the course."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string CourseLevel
	{
		get
		{ 
			return GetFieldValue( StudentDTD.SCEDCODE_COURSELEVEL );
		}
		set
		{
			SetField( StudentDTD.SCEDCODE_COURSELEVEL, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;CourseLevel&gt;</c> element.
	/// </summary>
	/// <param name="val">A CourseLevel object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Conveys the level of the course."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void SetCourseLevel( CourseLevel val )
	{
		SetField( StudentDTD.SCEDCODE_COURSELEVEL, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AvailableCredit&gt;</c> element.
	/// </summary>
	/// <value> The <c>AvailableCredit</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies the amount of credit available to a student who successfully meets the objectives of the course, measured in Carnegie units (9.99 format)."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public decimal? AvailableCredit
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( StudentDTD.SCEDCODE_AVAILABLECREDIT ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCEDCODE_AVAILABLECREDIT, new SifDecimal( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SequenceNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>SequenceNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "One-digit number describing where a specific course lies when it is part of a consecutive sequence of courses described by the same general course description."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public int? SequenceNumber
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.SCEDCODE_SEQUENCENUMBER ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCEDCODE_SEQUENCENUMBER, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SequenceLimit&gt;</c> element.
	/// </summary>
	/// <value> The <c>SequenceLimit</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "One-digit number representing the total number of courses in the consecutive sequence described by the same general course description."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public int? SequenceLimit
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.SCEDCODE_SEQUENCELIMIT ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCEDCODE_SEQUENCELIMIT, new SifInt( value ), value );
		}
	}

}}
