// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.uk.Common;

namespace OpenADK.Library.uk.Assessment{

/// <summary>A Grades</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.1</para>
/// </remarks>
[Serializable]
public class Grades : SifList<Grade>
{
	/// <summary>
	/// Creates an instance of a Grades
	/// </summary>
	public Grades() : base ( AssessmentDTD.GRADES ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="grade">A Grade</param>
	///
	public Grades( Grade grade ) : base( AssessmentDTD.GRADES )
	{
		this.SafeAddChild( AssessmentDTD.GRADES_GRADE, grade );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Grades( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { AssessmentDTD.GRADES_GRADE }; }
	}

	///<summary>Adds the value of the <c>&lt;Grade&gt;</c> element.</summary>
	/// <param name="Title">The visual representation of the grade.</param>
	/// <param name="Description">The meaning of the grade.</param>
	/// <param name="RankOrder">The rank position of the grade within the set where the highest value is assumed to be the best. While duplicate ranks are allowed they are discouraged.</param>
	/// <param name="NumericValue">The numeric equivalent value of the grade.</param>
	///<remarks>
	/// <para>This form of <c>setGrade</c> is provided as a convenience method
	/// that is functionally equivalent to the method <c>AddGrade</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public void AddGrade( string Title, string Description, int? RankOrder, decimal? NumericValue ) {
		AddChild( AssessmentDTD.GRADES_GRADE, new Grade( Title, Description, RankOrder, NumericValue ) );
	}

}}
