// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.uk.Common;

namespace OpenADK.Library.uk.Assessment{

/// <summary>A Grade</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.1</para>
/// </remarks>
[Serializable]
public class Grade : SifElement
{
	/// <summary>
	/// Creates an instance of a Grade
	/// </summary>
	public Grade() : base ( AssessmentDTD.GRADE ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="title">The visual representation of the grade.</param>
	///<param name="description">The meaning of the grade.</param>
	///<param name="rankOrder">The rank position of the grade within the set where the highest value is assumed to be the best. While duplicate ranks are allowed they are discouraged.</param>
	///<param name="numericValue">The numeric equivalent value of the grade.</param>
	///
	public Grade( string title, string description, int? rankOrder, decimal? numericValue ) : base( AssessmentDTD.GRADE )
	{
		this.Title = title;
		this.Description = description;
		this.RankOrder = rankOrder;
		this.NumericValue = numericValue;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Grade( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { AssessmentDTD.GRADE_TITLE, AssessmentDTD.GRADE_DESCRIPTION, AssessmentDTD.GRADE_RANKORDER, AssessmentDTD.GRADE_NUMERICVALUE }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The visual representation of the grade."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string Title
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.GRADE_TITLE ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.GRADE_TITLE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Description&gt;</c> element.
	/// </summary>
	/// <value> The <c>Description</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The meaning of the grade."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string Description
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.GRADE_DESCRIPTION ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.GRADE_DESCRIPTION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;RankOrder&gt;</c> element.
	/// </summary>
	/// <value> The <c>RankOrder</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The rank position of the grade within the set where the highest value is assumed to be the best. While duplicate ranks are allowed they are discouraged."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public int? RankOrder
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( AssessmentDTD.GRADE_RANKORDER ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.GRADE_RANKORDER, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;NumericValue&gt;</c> element.
	/// </summary>
	/// <value> The <c>NumericValue</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The numeric equivalent value of the grade."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public decimal? NumericValue
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( AssessmentDTD.GRADE_NUMERICVALUE ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.GRADE_NUMERICVALUE, new SifDecimal( value ), value );
		}
	}

}}
