// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.uk.Common;

namespace OpenADK.Library.uk.Assessment{

/// <summary>An Item</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.1</para>
/// </remarks>
[Serializable]
public class Item : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of an Item
	/// </summary>
	public Item() : base ( AssessmentDTD.ITEM ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="response">Learner selection or response in raw format.</param>
	///
	public Item( string response ) : base( AssessmentDTD.ITEM )
	{
		this.Response = response;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Item( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { AssessmentDTD.ITEM_RESPONSE }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Response&gt;</c> element.
	/// </summary>
	/// <value> The <c>Response</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Learner selection or response in raw format."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string Response
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.ITEM_RESPONSE ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_RESPONSE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ResponseStatus&gt;</c> element.
	/// </summary>
	/// <value> The <c>ResponseStatus</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Status of the response."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string ResponseStatus
	{
		get
		{ 
			return GetFieldValue( AssessmentDTD.ITEM_RESPONSESTATUS );
		}
		set
		{
			SetField( AssessmentDTD.ITEM_RESPONSESTATUS, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;ResponseStatus&gt;</c> element.
	/// </summary>
	/// <param name="val">A ResponseStatus object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Status of the response."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public void SetResponseStatus( ResponseStatus val )
	{
		SetField( AssessmentDTD.ITEM_RESPONSESTATUS, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ResponseTime&gt;</c> element.
	/// </summary>
	/// <value> The <c>ResponseTime</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The length of time the learner took to respond."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string ResponseTime
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.ITEM_RESPONSETIME ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_RESPONSETIME, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Mark&gt;</c> element.
	/// </summary>
	/// <value> The <c>Mark</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The mark achieved for this item as evaluated by the assessment tool at the time of assessment."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string Mark
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.ITEM_MARK ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_MARK, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Group&gt;</c> element.
	/// </summary>
	/// <value> The <c>Group</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The item group within the assessment."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string Group
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.ITEM_GROUP ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_GROUP, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ItemName&gt;</c> element.
	/// </summary>
	/// <value> The <c>ItemName</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies the item on the assessment by name."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string ItemName
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.ITEM_ITEMNAME ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_ITEMNAME, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ItemNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>ItemNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Identifies the item by number on the assessment."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string ItemNumber
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.ITEM_ITEMNUMBER ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_ITEMNUMBER, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;OrderAsked&gt;</c> element.
	/// </summary>
	/// <value> The <c>OrderAsked</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The order in which the item was asked."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public decimal? OrderAsked
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( AssessmentDTD.ITEM_ORDERASKED ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_ORDERASKED, new SifDecimal( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;NumberOfAttempts&gt;</c> element.
	/// </summary>
	/// <value> The <c>NumberOfAttempts</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The number of times a learner changes their answer or attempts a response."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public int? NumberOfAttempts
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( AssessmentDTD.ITEM_NUMBEROFATTEMPTS ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.ITEM_NUMBEROFATTEMPTS, new SifInt( value ), value );
		}
	}

}}
