// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.uk.Common;

namespace OpenADK.Library.uk.Learning{

/// <summary>A GroupTeacherList</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.3</para>
/// </remarks>
[Serializable]
public class GroupTeacherList : SifList<GroupTeacher>
{
	/// <summary>
	/// Creates an instance of a GroupTeacherList
	/// </summary>
	public GroupTeacherList() : base ( LearningDTD.GROUPTEACHERLIST ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="groupTeacher">A GroupTeacher</param>
	///
	public GroupTeacherList( GroupTeacher groupTeacher ) : base( LearningDTD.GROUPTEACHERLIST )
	{
		this.SafeAddChild( LearningDTD.GROUPTEACHERLIST_GROUPTEACHER, groupTeacher );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected GroupTeacherList( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { LearningDTD.GROUPTEACHERLIST_GROUPTEACHER }; }
	}

	///<summary>Adds the value of the <c>&lt;GroupTeacher&gt;</c> element.</summary>
	/// <param name="TtTeacherRefId">The teacher (see TTTeacher)</param>
	/// <param name="Type">The teacher’s relationship with the TG</param>
	///<remarks>
	/// <para>This form of <c>setGroupTeacher</c> is provided as a convenience method
	/// that is functionally equivalent to the method <c>AddGroupTeacher</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	public void AddGroupTeacher( string TtTeacherRefId, GroupTeacherType Type ) {
		AddChild( LearningDTD.GROUPTEACHERLIST_GROUPTEACHER, new GroupTeacher( TtTeacherRefId, Type ) );
	}

}}
