// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;

namespace OpenADK.Library.uk.Common{

/// <summary>Information on contact persons for a school or LA.</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class Contact : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of a Contact
	/// </summary>
	public Contact() : base ( CommonDTD.CONTACT ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="sifRefId">The ID (GUID) of the person listed as a contact. Note that this is any person listed as a contact through either a ContactPersonal, WorkforcePersonal, or even a LearnerPersonal record.</param>
	///<param name="sifRefObject">The name of the object being referred to</param>
	///
	public Contact( string sifRefId, string sifRefObject ) : base( CommonDTD.CONTACT )
	{
		this.SIF_RefId = sifRefId;
		this.SIF_RefObject = sifRefObject;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Contact( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { CommonDTD.CONTACT_SIF_REFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>SIF_RefId</c> attribute.
	/// </summary>
	/// <value> The <c>SIF_RefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The ID (GUID) of the person listed as a contact. Note that this is any person listed as a contact through either a ContactPersonal, WorkforcePersonal, or even a LearnerPersonal record."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string SIF_RefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( CommonDTD.CONTACT_SIF_REFID ) ;
		}
		set
		{
			SetFieldValue( CommonDTD.CONTACT_SIF_REFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>SIF_RefObject</c> attribute.
	/// </summary>
	/// <value> The <c>SIF_RefObject</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The name of the object being referred to"</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string SIF_RefObject
	{
		get
		{
			return (string) GetSifSimpleFieldValue( CommonDTD.CONTACT_SIF_REFOBJECT ) ;
		}
		set
		{
			SetFieldValue( CommonDTD.CONTACT_SIF_REFOBJECT, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;PositionTitle&gt;</c> element.
	/// </summary>
	/// <value> The <c>PositionTitle</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The contact person's position title within the LA."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string PositionTitle
	{
		get
		{
			return (string) GetSifSimpleFieldValue( CommonDTD.CONTACT_POSITIONTITLE ) ;
		}
		set
		{
			SetFieldValue( CommonDTD.CONTACT_POSITIONTITLE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Role&gt;</c> element.
	/// </summary>
	/// <value> The <c>Role</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Role played by this contact in the LA.  Any descriptive text is allowed here."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string Role
	{
		get
		{
			return (string) GetSifSimpleFieldValue( CommonDTD.CONTACT_ROLE ) ;
		}
		set
		{
			SetFieldValue( CommonDTD.CONTACT_ROLE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;PublishInDirectory&gt;</c> element.
	/// </summary>
	/// <value> The <c>PublishInDirectory</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Indicates whether or not this contact's information should be published in a directory of School or LA information."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string PublishInDirectory
	{
		get
		{ 
			return GetFieldValue( CommonDTD.CONTACT_PUBLISHINDIRECTORY );
		}
		set
		{
			SetField( CommonDTD.CONTACT_PUBLISHINDIRECTORY, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;PublishInDirectory&gt;</c> element.
	/// </summary>
	/// <param name="val">A YesNo object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Indicates whether or not this contact's information should be published in a directory of School or LA information."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void SetPublishInDirectory( YesNo val )
	{
		SetField( CommonDTD.CONTACT_PUBLISHINDIRECTORY, val );
	}

}}
