// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Datamodel{

/// <summary>An EDENInfoType</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.3</para>
/// </remarks>
[Serializable]
public class EDENInfoType : SifElement
{
	/// <summary>
	/// Creates an instance of an EDENInfoType
	/// </summary>
	public EDENInfoType() : base ( DatamodelDTD.EDENINFOTYPE ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected EDENInfoType( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;FIPSStateCode&gt;</c> element.
	/// </summary>
	/// <value> The <c>FIPSStateCode</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The two-digit Federal Information Processing Standard (FIPS) Code for the State, District of Columbia, and the possessions and freely associated areas of the United States (e.g. Puerto Rico)."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	public string FIPSStateCode
	{
		get
		{
			return (string) GetSifSimpleFieldValue( DatamodelDTD.EDENINFOTYPE_FIPSSTATECODE ) ;
		}
		set
		{
			SetFieldValue( DatamodelDTD.EDENINFOTYPE_FIPSSTATECODE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AgencyIdNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>AgencyIdNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "A number used in EDEN to uniquely uniquely identify state agencies."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	public string AgencyIdNumber
	{
		get
		{
			return (string) GetSifSimpleFieldValue( DatamodelDTD.EDENINFOTYPE_AGENCYIDNUMBER ) ;
		}
		set
		{
			SetFieldValue( DatamodelDTD.EDENINFOTYPE_AGENCYIDNUMBER, new SifString( value ), value );
		}
	}

}}
