// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Trans{

/// <summary>This object contains all of the information about a bus.</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 1.1</para>
/// </remarks>
[Serializable]
public class BusInfo : SifDataObject
{
	/// <summary>
	/// Creates an instance of a BusInfo
	/// </summary>
	public BusInfo() : base( Adk.SifVersion, TransDTD.BUSINFO ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="refId">GUID that identifies this bus.</param>
	///<param name="vehicleNumber">Vehicle number of the bus.</param>
	///
	public BusInfo( string refId, string vehicleNumber ) : base( Adk.SifVersion, TransDTD.BUSINFO )
	{
		this.RefId = refId;
		this.VehicleNumber = vehicleNumber;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected BusInfo( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { TransDTD.BUSINFO_REFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>RefId</c> attribute.
	/// </summary>
	/// <value> The <c>RefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "GUID that identifies this bus."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public override string RefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( TransDTD.BUSINFO_REFID ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_REFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;VehicleNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>VehicleNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Vehicle number of the bus."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public string VehicleNumber
	{
		get
		{
			return (string) GetSifSimpleFieldValue( TransDTD.BUSINFO_VEHICLENUMBER ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_VEHICLENUMBER, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SeatingCapacity&gt;</c> element.
	/// </summary>
	/// <value> The <c>SeatingCapacity</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The number of people who can ride on the bus at the same time."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public int? SeatingCapacity
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( TransDTD.BUSINFO_SEATINGCAPACITY ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_SEATINGCAPACITY, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Contractor&gt;</c> element.
	/// </summary>
	/// <value> The <c>Contractor</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The name of the contractor for this bus."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public string Contractor
	{
		get
		{
			return (string) GetSifSimpleFieldValue( TransDTD.BUSINFO_CONTRACTOR ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_CONTRACTOR, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EquipmentList&gt;</c> element.
	/// </summary>
	/// <value> An EquipmentList </value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this null as: "Describes any special equipment that is on this bus"</para>
	/// <para>To remove the <c>EquipmentList</c>, set <c>EquipmentList</c> to <c>null</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	public EquipmentList EquipmentList
	{
		get
		{
			return (EquipmentList)GetChild( TransDTD.BUSINFO_EQUIPMENTLIST);
		}
		set
		{
			RemoveChild( TransDTD.BUSINFO_EQUIPMENTLIST);
			if( value != null)
			{
				AddChild( TransDTD.BUSINFO_EQUIPMENTLIST, value );
			}
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ManufactureYear&gt;</c> element.
	/// </summary>
	/// <value> The <c>ManufactureYear</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The manufacture year of the bus (CCYY)."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public int? ManufactureYear
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( TransDTD.BUSINFO_MANUFACTUREYEAR ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_MANUFACTUREYEAR, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;VehicleIdentificationNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>VehicleIdentificationNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The Vehicle Identification Number (VIN) of the bus."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string VehicleIdentificationNumber
	{
		get
		{
			return (string) GetSifSimpleFieldValue( TransDTD.BUSINFO_VEHICLEIDENTIFICATIONNUMBER ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_VEHICLEIDENTIFICATIONNUMBER, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;LicensePlateNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>LicensePlateNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The vehicle's license plate number."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.1</para>
	/// </remarks>
	public string LicensePlateNumber
	{
		get
		{
			return (string) GetSifSimpleFieldValue( TransDTD.BUSINFO_LICENSEPLATENUMBER ) ;
		}
		set
		{
			SetFieldValue( TransDTD.BUSINFO_LICENSEPLATENUMBER, new SifString( value ), value );
		}
	}

}}
