// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.au.Student
{
	///<summary>
	/// Defines the set of values that can be specified whenever an ActivityInvolvementCodeType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  an ActivityInvolvementCodeType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	[Serializable]
	public class ActivityInvolvementCodeType : SifEnum
	{
	/// <summary>Billiards ("1111")</summary>
	public static readonly ActivityInvolvementCodeType C1111_BILLIARDS = new ActivityInvolvementCodeType("1111");

	/// <summary>Pigeon racing ("1841")</summary>
	public static readonly ActivityInvolvementCodeType C1841_PIGEON_RACING = new ActivityInvolvementCodeType("1841");

	/// <summary>Water volleyball ("1772")</summary>
	public static readonly ActivityInvolvementCodeType C1772_WATER_VOLLEYBALL = new ActivityInvolvementCodeType("1772");

	/// <summary>Lawn bowls ("1411")</summary>
	public static readonly ActivityInvolvementCodeType C1411_LAWN_BOWLS = new ActivityInvolvementCodeType("1411");

	/// <summary>Darts ("1231")</summary>
	public static readonly ActivityInvolvementCodeType C1231_DARTS = new ActivityInvolvementCodeType("1231");

	/// <summary>Orienteering ("1471")</summary>
	public static readonly ActivityInvolvementCodeType C1471_ORIENTEERING = new ActivityInvolvementCodeType("1471");

	/// <summary>Boxing ("1131")</summary>
	public static readonly ActivityInvolvementCodeType C1131_BOXING = new ActivityInvolvementCodeType("1131");

	/// <summary>Broadcasting ("5022")</summary>
	public static readonly ActivityInvolvementCodeType C5022_BROADCASTING = new ActivityInvolvementCodeType("5022");

	/// <summary>Eisteddfod ("4042")</summary>
	public static readonly ActivityInvolvementCodeType C4042_EISTEDDFOD = new ActivityInvolvementCodeType("4042");

	/// <summary>Bocce ("1121")</summary>
	public static readonly ActivityInvolvementCodeType C1121_BOCCE = new ActivityInvolvementCodeType("1121");

	/// <summary>Wood chopping ("1811")</summary>
	public static readonly ActivityInvolvementCodeType C1811_WOOD_CHOPPING = new ActivityInvolvementCodeType("1811");

	/// <summary>Horse riding/Equestrian activities ("1371")</summary>
	public static readonly ActivityInvolvementCodeType C1371_HORSE_RIDING_EQUESTRIAN = new ActivityInvolvementCodeType("1371");

	/// <summary>Throwing, n.f.d. ("1280")</summary>
	public static readonly ActivityInvolvementCodeType C1280_THROWING_NFD = new ActivityInvolvementCodeType("1280");

	/// <summary>Other arts activity ("5019")</summary>
	public static readonly ActivityInvolvementCodeType C5019_OT_ARTS_ACTIVITY = new ActivityInvolvementCodeType("5019");

	/// <summary>Snow skiing ("1384")</summary>
	public static readonly ActivityInvolvementCodeType C1384_SNOW_SKIING = new ActivityInvolvementCodeType("1384");

	/// <summary>Aerobatics ("1021")</summary>
	public static readonly ActivityInvolvementCodeType C1021_AEROBATICS = new ActivityInvolvementCodeType("1021");

	/// <summary>Dog shows ("1251")</summary>
	public static readonly ActivityInvolvementCodeType C1251_DOG_SHOWS = new ActivityInvolvementCodeType("1251");

	/// <summary>Volleyball (Indoor and outdoor) ("1731")</summary>
	public static readonly ActivityInvolvementCodeType C1731_VOLLEYBALL_INDOOROUTDOOR = new ActivityInvolvementCodeType("1731");

	/// <summary>Paintball shooting ("1592")</summary>
	public static readonly ActivityInvolvementCodeType C1592_PAINTBALL_SHOOTING = new ActivityInvolvementCodeType("1592");

	/// <summary>Dance team ("1225")</summary>
	public static readonly ActivityInvolvementCodeType C1225_DANCE_TEAM = new ActivityInvolvementCodeType("1225");

	/// <summary>Judo/Jujitsu ("1432")</summary>
	public static readonly ActivityInvolvementCodeType C1432_JUDO_JUJITSU = new ActivityInvolvementCodeType("1432");

	/// <summary>Snow boarding ("1385")</summary>
	public static readonly ActivityInvolvementCodeType C1385_SNOW_BOARDING = new ActivityInvolvementCodeType("1385");

	/// <summary>Badminton ("1071")</summary>
	public static readonly ActivityInvolvementCodeType C1071_BADMINTON = new ActivityInvolvementCodeType("1071");

	/// <summary>Concert Band ("4022")</summary>
	public static readonly ActivityInvolvementCodeType C4022_CONCERT_BAND = new ActivityInvolvementCodeType("4022");

	/// <summary>Sailboarding ("1802")</summary>
	public static readonly ActivityInvolvementCodeType C1802_SAILBOARDING = new ActivityInvolvementCodeType("1802");

	/// <summary>Canoeing ("1151")</summary>
	public static readonly ActivityInvolvementCodeType C1151_CANOEING = new ActivityInvolvementCodeType("1151");

	/// <summary>Running ("1562")</summary>
	public static readonly ActivityInvolvementCodeType C1562_RUNNING = new ActivityInvolvementCodeType("1562");

	/// <summary>Army Cadets ("3011")</summary>
	public static readonly ActivityInvolvementCodeType C3011_ARMY_CADETS = new ActivityInvolvementCodeType("3011");

	/// <summary>Surf sport (other) ("1652")</summary>
	public static readonly ActivityInvolvementCodeType C1652_SURF_SPORT_OTHER = new ActivityInvolvementCodeType("1652");

	/// <summary>Other Music ("4039")</summary>
	public static readonly ActivityInvolvementCodeType C4039_OT_MUSIC = new ActivityInvolvementCodeType("4039");

	/// <summary>Boot scooting ("1221")</summary>
	public static readonly ActivityInvolvementCodeType C1221_BOOT_SCOOTING = new ActivityInvolvementCodeType("1221");

	/// <summary>Wrestling ("1821")</summary>
	public static readonly ActivityInvolvementCodeType C1821_WRESTLING = new ActivityInvolvementCodeType("1821");

	/// <summary>Mountain biking ("1214")</summary>
	public static readonly ActivityInvolvementCodeType C1214_MOUNTAIN_BIKING = new ActivityInvolvementCodeType("1214");

	/// <summary>Marching ("1421")</summary>
	public static readonly ActivityInvolvementCodeType C1421_MARCHING = new ActivityInvolvementCodeType("1421");

	/// <summary>Youth Development, n.f.d. ("3010")</summary>
	public static readonly ActivityInvolvementCodeType C3010_YOUTH_DEVELOPMENT = new ActivityInvolvementCodeType("3010");

	/// <summary>Fitness centre activities ("1012")</summary>
	public static readonly ActivityInvolvementCodeType C1012_FITNESS_CENTRE_ACTIVITIES = new ActivityInvolvementCodeType("1012");

	/// <summary>Harness racing/Trotting ("1341")</summary>
	public static readonly ActivityInvolvementCodeType C1341_HARNESS_RACING_TROTTING = new ActivityInvolvementCodeType("1341");

	/// <summary>School captain ("2016")</summary>
	public static readonly ActivityInvolvementCodeType C2016_SCHOOL_CAPTAIN = new ActivityInvolvementCodeType("2016");

	/// <summary>Classical Ballet ("1222")</summary>
	public static readonly ActivityInvolvementCodeType C1222_CLASSICAL_BALLET = new ActivityInvolvementCodeType("1222");

	/// <summary>Other youth development group ("3019")</summary>
	public static readonly ActivityInvolvementCodeType C3019_OT_YOUTH_DEVELOPMENT = new ActivityInvolvementCodeType("3019");

	/// <summary>Ultimate frisbee ("1281")</summary>
	public static readonly ActivityInvolvementCodeType C1281_ULTIMATE_FRISBEE = new ActivityInvolvementCodeType("1281");

	/// <summary>Class captain ("2013")</summary>
	public static readonly ActivityInvolvementCodeType C2013_CLASS_CAPTAIN = new ActivityInvolvementCodeType("2013");

	/// <summary>Other performing arts ("4044")</summary>
	public static readonly ActivityInvolvementCodeType C4044_OT_PERFORMING_ARTS = new ActivityInvolvementCodeType("4044");

	/// <summary>School Year book ("5023")</summary>
	public static readonly ActivityInvolvementCodeType C5023_SCHOOL_YEAR_BOOK = new ActivityInvolvementCodeType("5023");

	/// <summary>Rodeos ("1501")</summary>
	public static readonly ActivityInvolvementCodeType C1501_RODEOS = new ActivityInvolvementCodeType("1501");

	/// <summary>Chamber ensemble ("4025")</summary>
	public static readonly ActivityInvolvementCodeType C4025_CHAMBER_ENSEMBLE = new ActivityInvolvementCodeType("4025");

	/// <summary>Kickboxing ("1434")</summary>
	public static readonly ActivityInvolvementCodeType C1434_KICKBOXING = new ActivityInvolvementCodeType("1434");

	/// <summary>Minigolf ("1441")</summary>
	public static readonly ActivityInvolvementCodeType C1441_MINIGOLF = new ActivityInvolvementCodeType("1441");

	/// <summary>Other Cultural club ("6019")</summary>
	public static readonly ActivityInvolvementCodeType C6019_OT_CULTURAL_CLUB = new ActivityInvolvementCodeType("6019");

	/// <summary>Pool ("1112")</summary>
	public static readonly ActivityInvolvementCodeType C1112_POOL = new ActivityInvolvementCodeType("1112");

	/// <summary>Outdoor rock activities, n.f.d. ("1490")</summary>
	public static readonly ActivityInvolvementCodeType C1490_OUTDOOR_ROCK_ACTIVITIES = new ActivityInvolvementCodeType("1490");

	/// <summary>Roller sport (other) ("1514")</summary>
	public static readonly ActivityInvolvementCodeType C1514_ROLLER_SPORT_OTHER = new ActivityInvolvementCodeType("1514");

	/// <summary>Croquet ("1191")</summary>
	public static readonly ActivityInvolvementCodeType C1191_CROQUET = new ActivityInvolvementCodeType("1191");

	/// <summary>Non-motorised outdoor water sports, n.f.d. ("1770")</summary>
	public static readonly ActivityInvolvementCodeType C1770_NONMOTORISED_OUTDOOR_WATER_SPORTS = new ActivityInvolvementCodeType("1770");

	/// <summary>Putt-putt golf ("1442")</summary>
	public static readonly ActivityInvolvementCodeType C1442_PUTTPUTT_GOLF = new ActivityInvolvementCodeType("1442");

	/// <summary>Choir ("4012")</summary>
	public static readonly ActivityInvolvementCodeType C4012_CHOIR = new ActivityInvolvementCodeType("4012");

	/// <summary>Peer counseling ("7011")</summary>
	public static readonly ActivityInvolvementCodeType C7011_PEER_COUNSELING = new ActivityInvolvementCodeType("7011");

	/// <summary>Aerobics/exercising (other) ("1014")</summary>
	public static readonly ActivityInvolvementCodeType C1014_AEROBICS_EXERCISING_OTHER = new ActivityInvolvementCodeType("1014");

	/// <summary>Other general activity ("7019")</summary>
	public static readonly ActivityInvolvementCodeType C7019_OT_GENERAL_ACTIVITY = new ActivityInvolvementCodeType("7019");

	/// <summary>Archery ("1041")</summary>
	public static readonly ActivityInvolvementCodeType C1041_ARCHERY = new ActivityInvolvementCodeType("1041");

	/// <summary>Bush walking ("1141")</summary>
	public static readonly ActivityInvolvementCodeType C1141_BUSH_WALKING = new ActivityInvolvementCodeType("1141");

	/// <summary>Book Club ("6011")</summary>
	public static readonly ActivityInvolvementCodeType C6011_BOOK_CLUB = new ActivityInvolvementCodeType("6011");

	/// <summary>Rugby union (football) ("1551")</summary>
	public static readonly ActivityInvolvementCodeType C1551_RUGBY_UNION_FOOTBALL = new ActivityInvolvementCodeType("1551");

	/// <summary>Cricket (Indoor) ("1171")</summary>
	public static readonly ActivityInvolvementCodeType C1171_CRICKET_INDOOR = new ActivityInvolvementCodeType("1171");

	/// <summary>Baseball ("1081")</summary>
	public static readonly ActivityInvolvementCodeType C1081_BASEBALL = new ActivityInvolvementCodeType("1081");

	/// <summary>Royal Tennis ("1531")</summary>
	public static readonly ActivityInvolvementCodeType C1531_ROYAL_TENNIS = new ActivityInvolvementCodeType("1531");

	/// <summary>Ballroom Dancing ("1224")</summary>
	public static readonly ActivityInvolvementCodeType C1224_BALLROOM_DANCING = new ActivityInvolvementCodeType("1224");

	/// <summary>Shooting sports, n.f.d. ("1590")</summary>
	public static readonly ActivityInvolvementCodeType C1590_SHOOTING_SPORTS = new ActivityInvolvementCodeType("1590");

	/// <summary>Other sporting activities, n.f.d. ("1840")</summary>
	public static readonly ActivityInvolvementCodeType C1840_OT_SPORTING_ACTIVITIES = new ActivityInvolvementCodeType("1840");

	/// <summary>Tenpin bowling ("1691")</summary>
	public static readonly ActivityInvolvementCodeType C1691_TENPIN_BOWLING = new ActivityInvolvementCodeType("1691");

	/// <summary>Air sports, n.f.d. ("1020")</summary>
	public static readonly ActivityInvolvementCodeType C1020_AIR_SPORTS_NFD = new ActivityInvolvementCodeType("1020");

	/// <summary>Tutoring ("7012")</summary>
	public static readonly ActivityInvolvementCodeType C7012_TUTORING = new ActivityInvolvementCodeType("7012");

	/// <summary>Martial arts (other) ("1439")</summary>
	public static readonly ActivityInvolvementCodeType C1439_MARTIAL_ARTS_OTHER = new ActivityInvolvementCodeType("1439");

	/// <summary>Sheepdog trials ("1252")</summary>
	public static readonly ActivityInvolvementCodeType C1252_SHEEPDOG_TRIALS = new ActivityInvolvementCodeType("1252");

	/// <summary>Caving ("1492")</summary>
	public static readonly ActivityInvolvementCodeType C1492_CAVING = new ActivityInvolvementCodeType("1492");

	/// <summary>Class officer ("2014")</summary>
	public static readonly ActivityInvolvementCodeType C2014_CLASS_OFFICER = new ActivityInvolvementCodeType("2014");

	/// <summary>Circus acrobatics ("1322")</summary>
	public static readonly ActivityInvolvementCodeType C1322_CIRCUS_ACROBATICS = new ActivityInvolvementCodeType("1322");

	/// <summary>Rogaining ("1472")</summary>
	public static readonly ActivityInvolvementCodeType C1472_ROGAINING = new ActivityInvolvementCodeType("1472");

	/// <summary>Speech/debate ("5025")</summary>
	public static readonly ActivityInvolvementCodeType C5025_SPEECH_DEBATE = new ActivityInvolvementCodeType("5025");

	/// <summary>Squash ("1631")</summary>
	public static readonly ActivityInvolvementCodeType C1631_SQUASH = new ActivityInvolvementCodeType("1631");

	/// <summary>Horse racing ("1362")</summary>
	public static readonly ActivityInvolvementCodeType C1362_HORSE_RACING = new ActivityInvolvementCodeType("1362");

	/// <summary>Fencing ("1261")</summary>
	public static readonly ActivityInvolvementCodeType C1261_FENCING = new ActivityInvolvementCodeType("1261");

	/// <summary>Roller-blading ("1511")</summary>
	public static readonly ActivityInvolvementCodeType C1511_ROLLERBLADING = new ActivityInvolvementCodeType("1511");

	/// <summary>Chi Kung ("1431")</summary>
	public static readonly ActivityInvolvementCodeType C1431_CHI_KUNG = new ActivityInvolvementCodeType("1431");

	/// <summary>Snooker ("1113")</summary>
	public static readonly ActivityInvolvementCodeType C1113_SNOOKER = new ActivityInvolvementCodeType("1113");

	/// <summary>Exercise biking ("1011")</summary>
	public static readonly ActivityInvolvementCodeType C1011_EXERCISE_BIKING = new ActivityInvolvementCodeType("1011");

	/// <summary>Girl Scouts ("3015")</summary>
	public static readonly ActivityInvolvementCodeType C3015_GIRL_SCOUTS = new ActivityInvolvementCodeType("3015");

	/// <summary>Other student leadership ("2019")</summary>
	public static readonly ActivityInvolvementCodeType C2019_OT_STUDENT_LEADERSHIP = new ActivityInvolvementCodeType("2019");

	/// <summary>Fishing ("1272")</summary>
	public static readonly ActivityInvolvementCodeType C1272_FISHING = new ActivityInvolvementCodeType("1272");

	/// <summary>Ultralight flying ("1026")</summary>
	public static readonly ActivityInvolvementCodeType C1026_ULTRALIGHT_FLYING = new ActivityInvolvementCodeType("1026");

	/// <summary>Inline hockey ("1513")</summary>
	public static readonly ActivityInvolvementCodeType C1513_INLINE_HOCKEY = new ActivityInvolvementCodeType("1513");

	/// <summary>Cycling ("1212")</summary>
	public static readonly ActivityInvolvementCodeType C1212_CYCLING = new ActivityInvolvementCodeType("1212");

	/// <summary>Competition weight-lifting ("1781")</summary>
	public static readonly ActivityInvolvementCodeType C1781_COMPETITION_WEIGHTLIFTING = new ActivityInvolvementCodeType("1781");

	/// <summary>Embroidery ("5013")</summary>
	public static readonly ActivityInvolvementCodeType C5013_EMBROIDERY = new ActivityInvolvementCodeType("5013");

	/// <summary>Tai Chi ("1436")</summary>
	public static readonly ActivityInvolvementCodeType C1436_TAI_CHI = new ActivityInvolvementCodeType("1436");

	/// <summary>Beach volleyball ("1101")</summary>
	public static readonly ActivityInvolvementCodeType C1101_BEACH_VOLLEYBALL = new ActivityInvolvementCodeType("1101");

	/// <summary>Softball ("1621")</summary>
	public static readonly ActivityInvolvementCodeType C1621_SOFTBALL = new ActivityInvolvementCodeType("1621");

	/// <summary>Multidisciplinary events ("1843")</summary>
	public static readonly ActivityInvolvementCodeType C1843_MULTIDISCIPLINARY = new ActivityInvolvementCodeType("1843");

	/// <summary>Motor sports, n.f.d. ("1450")</summary>
	public static readonly ActivityInvolvementCodeType C1450_MOTOR_SPORTS_NFD = new ActivityInvolvementCodeType("1450");

	/// <summary>Hang gliding ("1025")</summary>
	public static readonly ActivityInvolvementCodeType C1025_HANG_GLIDING = new ActivityInvolvementCodeType("1025");

	/// <summary>Journalism ("5021")</summary>
	public static readonly ActivityInvolvementCodeType C5021_JOURNALISM = new ActivityInvolvementCodeType("5021");

	/// <summary>Korfball ("1391")</summary>
	public static readonly ActivityInvolvementCodeType C1391_KORFBALL = new ActivityInvolvementCodeType("1391");

	/// <summary>Cricket (Outdoor) ("1181")</summary>
	public static readonly ActivityInvolvementCodeType C1181_CRICKET_OUTDOOR = new ActivityInvolvementCodeType("1181");

	/// <summary>Touch football ("1701")</summary>
	public static readonly ActivityInvolvementCodeType C1701_TOUCH_FOOTBALL = new ActivityInvolvementCodeType("1701");

	/// <summary>Other Technology Club ("6029")</summary>
	public static readonly ActivityInvolvementCodeType C6029_OT_TECHNOLOGY_CLUB = new ActivityInvolvementCodeType("6029");

	/// <summary>Cross country running ("1201")</summary>
	public static readonly ActivityInvolvementCodeType C1201_CROSS_COUNTRY_RUNNING = new ActivityInvolvementCodeType("1201");

	/// <summary>Bike riding ("1211")</summary>
	public static readonly ActivityInvolvementCodeType C1211_BIKE_RIDING = new ActivityInvolvementCodeType("1211");

	/// <summary>Rock climbing ("1493")</summary>
	public static readonly ActivityInvolvementCodeType C1493_ROCK_CLIMBING = new ActivityInvolvementCodeType("1493");

	/// <summary>Boules ("1122")</summary>
	public static readonly ActivityInvolvementCodeType C1122_BOULES = new ActivityInvolvementCodeType("1122");

	/// <summary>Go-Karting (motor sports) ("1451")</summary>
	public static readonly ActivityInvolvementCodeType C1451_GOKARTING_MOTOR_SPORTS = new ActivityInvolvementCodeType("1451");

	/// <summary>Hockey (Indoor) ("1351")</summary>
	public static readonly ActivityInvolvementCodeType C1351_HOCKEY_INDOOR = new ActivityInvolvementCodeType("1351");

	/// <summary>Trail biking (motor sports) ("1711")</summary>
	public static readonly ActivityInvolvementCodeType C1711_TRAIL_BIKING_MOTOR_SPORTS = new ActivityInvolvementCodeType("1711");

	/// <summary>Roller sports, n.f.d. ("1510")</summary>
	public static readonly ActivityInvolvementCodeType C1510_ROLLER_SPORTS_NFD = new ActivityInvolvementCodeType("1510");

	/// <summary>Cue Sports, n.f.d. ("1110")</summary>
	public static readonly ActivityInvolvementCodeType C1110_CUE_SPORTS_NFD = new ActivityInvolvementCodeType("1110");

	/// <summary>Other instrumental ensemble ("4029")</summary>
	public static readonly ActivityInvolvementCodeType C4029_OT_INSTRUMENTAL = new ActivityInvolvementCodeType("4029");

	/// <summary>Gaelic football ("1291")</summary>
	public static readonly ActivityInvolvementCodeType C1291_GAELIC_FOOTBALL = new ActivityInvolvementCodeType("1291");

	/// <summary>Other sporting activities ("1849")</summary>
	public static readonly ActivityInvolvementCodeType C1849_OT_SPORTING_ACTIVITIES = new ActivityInvolvementCodeType("1849");

	/// <summary>Walking for exercise ("1741")</summary>
	public static readonly ActivityInvolvementCodeType C1741_WALKINGEXERCISE = new ActivityInvolvementCodeType("1741");

	/// <summary>Trampolining ("1324")</summary>
	public static readonly ActivityInvolvementCodeType C1324_TRAMPOLINING = new ActivityInvolvementCodeType("1324");

	/// <summary>Karate ("1433")</summary>
	public static readonly ActivityInvolvementCodeType C1433_KARATE = new ActivityInvolvementCodeType("1433");

	/// <summary>Ice/Snow sport (other) ("1383")</summary>
	public static readonly ActivityInvolvementCodeType C1383_ICE_SNOW_SPORT_OTHER = new ActivityInvolvementCodeType("1383");

	/// <summary>Airforce Cadets ("3012")</summary>
	public static readonly ActivityInvolvementCodeType C3012_AIRFORCE_CADETS = new ActivityInvolvementCodeType("3012");

	/// <summary>Board sports, n.f.d. ("1800")</summary>
	public static readonly ActivityInvolvementCodeType C1800_BOARD_SPORTS_NFD = new ActivityInvolvementCodeType("1800");

	/// <summary>Technology Students ("6021")</summary>
	public static readonly ActivityInvolvementCodeType C6021_TECHNOLOGY_STUDENTS = new ActivityInvolvementCodeType("6021");

	/// <summary>Indoor water sports, n.f.d. ("1660")</summary>
	public static readonly ActivityInvolvementCodeType C1660_INDOOR_WATER_SPORTS = new ActivityInvolvementCodeType("1660");

	/// <summary>Duke of Edinburugh Award ("2017")</summary>
	public static readonly ActivityInvolvementCodeType C2017_DUKE_OF_EDINBURUGH = new ActivityInvolvementCodeType("2017");

	/// <summary>Swimming ("1662")</summary>
	public static readonly ActivityInvolvementCodeType C1662_SWIMMING = new ActivityInvolvementCodeType("1662");

	/// <summary>Team captain ("2011")</summary>
	public static readonly ActivityInvolvementCodeType C2011_TEAM_CAPTAIN = new ActivityInvolvementCodeType("2011");

	/// <summary>Dog competitions, n.f.d. ("1250")</summary>
	public static readonly ActivityInvolvementCodeType C1250_DOG_COMPETITIONS = new ActivityInvolvementCodeType("1250");

	/// <summary>Health Occupations Students ("6031")</summary>
	public static readonly ActivityInvolvementCodeType C6031_HEALTH_OCCUPATIONS = new ActivityInvolvementCodeType("6031");

	/// <summary>Hunting ("1591")</summary>
	public static readonly ActivityInvolvementCodeType C1591_HUNTING = new ActivityInvolvementCodeType("1591");

	/// <summary>Dirt bike riding (motor sports) ("1712")</summary>
	public static readonly ActivityInvolvementCodeType C1712_DIRT_BIKE_RIDING_MOTOR_SPORTS = new ActivityInvolvementCodeType("1712");

	/// <summary>Jazz Ballet ("1223")</summary>
	public static readonly ActivityInvolvementCodeType C1223_JAZZ_BALLET = new ActivityInvolvementCodeType("1223");

	/// <summary>Art and graphic design ("5011")</summary>
	public static readonly ActivityInvolvementCodeType C5011_ARTGRAPHIC_DESIGN = new ActivityInvolvementCodeType("5011");

	/// <summary>Lacrosse ("1401")</summary>
	public static readonly ActivityInvolvementCodeType C1401_LACROSSE = new ActivityInvolvementCodeType("1401");

	/// <summary>Taekwondo ("1435")</summary>
	public static readonly ActivityInvolvementCodeType C1435_TAEKWONDO = new ActivityInvolvementCodeType("1435");

	/// <summary>Gymnasium workouts ("1013")</summary>
	public static readonly ActivityInvolvementCodeType C1013_GYMNASIUM_WORKOUTS = new ActivityInvolvementCodeType("1013");

	/// <summary>Weight training (for fitness - other) ("1792")</summary>
	public static readonly ActivityInvolvementCodeType C1792_WEIGHT_TRAINING_FOR_FITNESS_OTHER = new ActivityInvolvementCodeType("1792");

	/// <summary>Martial arts, n.f.d. ("1430")</summary>
	public static readonly ActivityInvolvementCodeType C1430_MARTIAL_ARTS_NFD = new ActivityInvolvementCodeType("1430");

	/// <summary>Ice skating ("1392")</summary>
	public static readonly ActivityInvolvementCodeType C1392_ICE_SKATING = new ActivityInvolvementCodeType("1392");

	/// <summary>Skateboarding ("1512")</summary>
	public static readonly ActivityInvolvementCodeType C1512_SKATEBOARDING = new ActivityInvolvementCodeType("1512");

	/// <summary>Gymnastics ("1321")</summary>
	public static readonly ActivityInvolvementCodeType C1321_GYMNASTICS = new ActivityInvolvementCodeType("1321");

	/// <summary>Formal/Social/Debutante Ball ("7013")</summary>
	public static readonly ActivityInvolvementCodeType C7013_FORMAL_SOCIAL_DEBUTANTE = new ActivityInvolvementCodeType("7013");

	/// <summary>Orchestra ("4023")</summary>
	public static readonly ActivityInvolvementCodeType C4023_ORCHESTRA = new ActivityInvolvementCodeType("4023");

	/// <summary>Exercise, n.f.d. ("1010")</summary>
	public static readonly ActivityInvolvementCodeType C1010_EXERCISE_NFD = new ActivityInvolvementCodeType("1010");

	/// <summary>Tennis (Indoor and outdoor) ("1681")</summary>
	public static readonly ActivityInvolvementCodeType C1681_TENNIS_INDOOROUTDOOR = new ActivityInvolvementCodeType("1681");

	/// <summary>Synchronized Swimming ("1663")</summary>
	public static readonly ActivityInvolvementCodeType C1663_SYNCHRONIZED_SWIMMING = new ActivityInvolvementCodeType("1663");

	/// <summary>Radio controlled model car/boat/plane racing ("1844")</summary>
	public static readonly ActivityInvolvementCodeType C1844_RADIO_CONTROLLED_MODEL_CAR_BOAT_PLANE = new ActivityInvolvementCodeType("1844");

	/// <summary>Soccer (Indoor) ("1601")</summary>
	public static readonly ActivityInvolvementCodeType C1601_SOCCER_INDOOR = new ActivityInvolvementCodeType("1601");

	/// <summary>Shooting sport (other) ("1594")</summary>
	public static readonly ActivityInvolvementCodeType C1594_SHOOTING_SPORT_OTHER = new ActivityInvolvementCodeType("1594");

	/// <summary>Gyroplane flying ("1024")</summary>
	public static readonly ActivityInvolvementCodeType C1024_GYROPLANE_FLYING = new ActivityInvolvementCodeType("1024");

	/// <summary>Kayaking ("1152")</summary>
	public static readonly ActivityInvolvementCodeType C1152_KAYAKING = new ActivityInvolvementCodeType("1152");

	/// <summary>Basketball (indoor &amp;amp; outdoor) ("1091")</summary>
	public static readonly ActivityInvolvementCodeType C1091_BASKETBALL_INDOOR_AMP_OUTDOOR = new ActivityInvolvementCodeType("1091");

	/// <summary>BMXing ("1213")</summary>
	public static readonly ActivityInvolvementCodeType C1213_BMXING = new ActivityInvolvementCodeType("1213");

	/// <summary>Pilates ("1481")</summary>
	public static readonly ActivityInvolvementCodeType C1481_PILATES = new ActivityInvolvementCodeType("1481");

	/// <summary>Surf Lifesaving/Royal Lifesaving ("1641")</summary>
	public static readonly ActivityInvolvementCodeType C1641_SURF_LIFESAVING_ROYAL = new ActivityInvolvementCodeType("1641");

	/// <summary>Powerboating ("1762")</summary>
	public static readonly ActivityInvolvementCodeType C1762_POWERBOATING = new ActivityInvolvementCodeType("1762");

	/// <summary>Boomerang throwing ("1282")</summary>
	public static readonly ActivityInvolvementCodeType C1282_BOOMERANG_THROWING = new ActivityInvolvementCodeType("1282");

	/// <summary>Petanque ("1123")</summary>
	public static readonly ActivityInvolvementCodeType C1123_PETANQUE = new ActivityInvolvementCodeType("1123");

	/// <summary>Underwater hockey ("1773")</summary>
	public static readonly ActivityInvolvementCodeType C1773_UNDERWATER_HOCKEY = new ActivityInvolvementCodeType("1773");

	/// <summary>Sailing ("1571")</summary>
	public static readonly ActivityInvolvementCodeType C1571_SAILING = new ActivityInvolvementCodeType("1571");

	/// <summary>Dancing (other) ("1229")</summary>
	public static readonly ActivityInvolvementCodeType C1229_DANCING_OTHER = new ActivityInvolvementCodeType("1229");

	/// <summary>Music - theory and composition ("4031")</summary>
	public static readonly ActivityInvolvementCodeType C4031_MUSIC_THEORYCOMPOSITION = new ActivityInvolvementCodeType("4031");

	/// <summary>Athletics, track &amp;amp; field ("1051")</summary>
	public static readonly ActivityInvolvementCodeType C1051_ATHLETICS_TRACK_AMP = new ActivityInvolvementCodeType("1051");

	/// <summary>Australian rules football ("1061")</summary>
	public static readonly ActivityInvolvementCodeType C1061_AUSTRALIAN_RULES = new ActivityInvolvementCodeType("1061");

	/// <summary>Polo cross ("1373")</summary>
	public static readonly ActivityInvolvementCodeType C1373_POLO_CROSS = new ActivityInvolvementCodeType("1373");

	/// <summary>Target shooting ("1595")</summary>
	public static readonly ActivityInvolvementCodeType C1595_TARGET_SHOOTING = new ActivityInvolvementCodeType("1595");

	/// <summary>Jet skiing ("1761")</summary>
	public static readonly ActivityInvolvementCodeType C1761_JET_SKIING = new ActivityInvolvementCodeType("1761");

	/// <summary>Ice/Snow Sports, n.f.d. ("1380")</summary>
	public static readonly ActivityInvolvementCodeType C1380_ICE_SNOW_SPORTS = new ActivityInvolvementCodeType("1380");

	/// <summary>Yoga ("1831")</summary>
	public static readonly ActivityInvolvementCodeType C1831_YOGA = new ActivityInvolvementCodeType("1831");

	/// <summary>Arts activites,  n.f.d. ("5010")</summary>
	public static readonly ActivityInvolvementCodeType C5010_ARTS_ACTIVITES_NFD = new ActivityInvolvementCodeType("5010");

	/// <summary>Ballooning ("1022")</summary>
	public static readonly ActivityInvolvementCodeType C1022_BALLOONING = new ActivityInvolvementCodeType("1022");

	/// <summary>Pistol shooting ("1593")</summary>
	public static readonly ActivityInvolvementCodeType C1593_PISTOL_SHOOTING = new ActivityInvolvementCodeType("1593");

	/// <summary>Music - instrumental ("4021")</summary>
	public static readonly ActivityInvolvementCodeType C4021_MUSIC_INSTRUMENTAL = new ActivityInvolvementCodeType("4021");

	/// <summary>Scuba diving ("1581")</summary>
	public static readonly ActivityInvolvementCodeType C1581_SCUBA_DIVING = new ActivityInvolvementCodeType("1581");

	/// <summary>Other vocal ensemble ("4019")</summary>
	public static readonly ActivityInvolvementCodeType C4019_OT_VOCAL_ENSEMBLE = new ActivityInvolvementCodeType("4019");

	/// <summary>Water polo ("1751")</summary>
	public static readonly ActivityInvolvementCodeType C1751_WATER_POLO = new ActivityInvolvementCodeType("1751");

	/// <summary>Art club ("6014")</summary>
	public static readonly ActivityInvolvementCodeType C6014_ART_CLUB = new ActivityInvolvementCodeType("6014");

	/// <summary>Dance Sports, n.f.d. ("1220")</summary>
	public static readonly ActivityInvolvementCodeType C1220_DANCE_SPORTS_NFD = new ActivityInvolvementCodeType("1220");

	/// <summary>Computer club ("6022")</summary>
	public static readonly ActivityInvolvementCodeType C6022_COMPUTER_CLUB = new ActivityInvolvementCodeType("6022");

	/// <summary>Ice hockey ("1381")</summary>
	public static readonly ActivityInvolvementCodeType C1381_ICE_HOCKEY = new ActivityInvolvementCodeType("1381");

	/// <summary>Aquarobics ("1031")</summary>
	public static readonly ActivityInvolvementCodeType C1031_AQUAROBICS = new ActivityInvolvementCodeType("1031");

	/// <summary>Leadership Actvities ("2010")</summary>
	public static readonly ActivityInvolvementCodeType C2010_LEADERSHIP_ACTVITIES = new ActivityInvolvementCodeType("2010");

	/// <summary>Netball (Indoor and outdoor) ("1461")</summary>
	public static readonly ActivityInvolvementCodeType C1461_NETBALL_INDOOROUTDOOR = new ActivityInvolvementCodeType("1461");

	/// <summary>Water-skiing ("1763")</summary>
	public static readonly ActivityInvolvementCodeType C1763_WATERSKIING = new ActivityInvolvementCodeType("1763");

	/// <summary>Triathlons ("1721")</summary>
	public static readonly ActivityInvolvementCodeType C1721_TRIATHLONS = new ActivityInvolvementCodeType("1721");

	/// <summary>Angling ("1271")</summary>
	public static readonly ActivityInvolvementCodeType C1271_ANGLING = new ActivityInvolvementCodeType("1271");

	/// <summary>Music - vocal ("4011")</summary>
	public static readonly ActivityInvolvementCodeType C4011_MUSIC_VOCAL = new ActivityInvolvementCodeType("4011");

	/// <summary>Communications, nf.d. ("5020")</summary>
	public static readonly ActivityInvolvementCodeType C5020_COMMUNICATIONS_NFD = new ActivityInvolvementCodeType("5020");

	/// <summary>Other Cadets ("3013")</summary>
	public static readonly ActivityInvolvementCodeType C3013_OT_CADETS = new ActivityInvolvementCodeType("3013");

	/// <summary>Jogging ("1561")</summary>
	public static readonly ActivityInvolvementCodeType C1561_JOGGING = new ActivityInvolvementCodeType("1561");

	/// <summary>Gliding ("1023")</summary>
	public static readonly ActivityInvolvementCodeType C1023_GLIDING = new ActivityInvolvementCodeType("1023");

	/// <summary>Surfing ("1651")</summary>
	public static readonly ActivityInvolvementCodeType C1651_SURFING = new ActivityInvolvementCodeType("1651");

	/// <summary>Rugby league (football) ("1541")</summary>
	public static readonly ActivityInvolvementCodeType C1541_RUGBY_LEAGUE_FOOTBALL = new ActivityInvolvementCodeType("1541");

	/// <summary>Other communications ("5029")</summary>
	public static readonly ActivityInvolvementCodeType C5029_OT_COMMUNICATIONS = new ActivityInvolvementCodeType("5029");

	/// <summary>Jazz ensemble ("4024")</summary>
	public static readonly ActivityInvolvementCodeType C4024_JAZZ_ENSEMBLE = new ActivityInvolvementCodeType("4024");

	/// <summary>Callisthenics ("1323")</summary>
	public static readonly ActivityInvolvementCodeType C1323_CALLISTHENICS = new ActivityInvolvementCodeType("1323");

	/// <summary>Show jumping ("1374")</summary>
	public static readonly ActivityInvolvementCodeType C1374_SHOW_JUMPING = new ActivityInvolvementCodeType("1374");

	/// <summary>Hockey (Outdoor) ("1352")</summary>
	public static readonly ActivityInvolvementCodeType C1352_HOCKEY_OUTDOOR = new ActivityInvolvementCodeType("1352");

	/// <summary>Painting ("5012")</summary>
	public static readonly ActivityInvolvementCodeType C5012_PAINTING = new ActivityInvolvementCodeType("5012");

	/// <summary>Racquet ball ("1632")</summary>
	public static readonly ActivityInvolvementCodeType C1632_RACQUET_BALL = new ActivityInvolvementCodeType("1632");

	/// <summary>Annual music production ("4043")</summary>
	public static readonly ActivityInvolvementCodeType C4043_ANNUAL_MUSIC_PRODUCTION = new ActivityInvolvementCodeType("4043");

	/// <summary>Playing ("1842")</summary>
	public static readonly ActivityInvolvementCodeType C1842_PLAYING = new ActivityInvolvementCodeType("1842");

	/// <summary>Abseiling ("1491")</summary>
	public static readonly ActivityInvolvementCodeType C1491_ABSEILING = new ActivityInvolvementCodeType("1491");

	/// <summary>Theatre/drama ("4041")</summary>
	public static readonly ActivityInvolvementCodeType C4041_THEATRE_DRAMA = new ActivityInvolvementCodeType("4041");

	/// <summary>Gridiron (USA football ) ("1311")</summary>
	public static readonly ActivityInvolvementCodeType C1311_GRIDIRON_USA_FOOTBALL = new ActivityInvolvementCodeType("1311");

	/// <summary>Air sport ( other ) ("1027")</summary>
	public static readonly ActivityInvolvementCodeType C1027_AIR_SPORT_OT = new ActivityInvolvementCodeType("1027");

	/// <summary>Softcrosse ("1402")</summary>
	public static readonly ActivityInvolvementCodeType C1402_SOFTCROSSE = new ActivityInvolvementCodeType("1402");

	/// <summary>Handball ("1331")</summary>
	public static readonly ActivityInvolvementCodeType C1331_HANDBALL = new ActivityInvolvementCodeType("1331");

	/// <summary>Student representative council officer ("2015")</summary>
	public static readonly ActivityInvolvementCodeType C2015_STUDENT_REPRESENTATIVE_COUNCIL = new ActivityInvolvementCodeType("2015");

	/// <summary>White water rafting ("1774")</summary>
	public static readonly ActivityInvolvementCodeType C1774_WHITE_WATER_RAFTING = new ActivityInvolvementCodeType("1774");

	/// <summary>Language club ("6013")</summary>
	public static readonly ActivityInvolvementCodeType C6013_LANGUAGE_CLUB = new ActivityInvolvementCodeType("6013");

	/// <summary>Circuits ("1015")</summary>
	public static readonly ActivityInvolvementCodeType C1015_CIRCUITS = new ActivityInvolvementCodeType("1015");

	/// <summary>Chess club ("6032")</summary>
	public static readonly ActivityInvolvementCodeType C6032_CHESS_CLUB = new ActivityInvolvementCodeType("6032");

	/// <summary>Motor sport (other) ("1459")</summary>
	public static readonly ActivityInvolvementCodeType C1459_MOTOR_SPORT_OTHER = new ActivityInvolvementCodeType("1459");

	/// <summary>Golf ("1301")</summary>
	public static readonly ActivityInvolvementCodeType C1301_GOLF = new ActivityInvolvementCodeType("1301");

	/// <summary>Table tennis ("1671")</summary>
	public static readonly ActivityInvolvementCodeType C1671_TABLE_TENNIS = new ActivityInvolvementCodeType("1671");

	/// <summary>Diving (board) ("1661")</summary>
	public static readonly ActivityInvolvementCodeType C1661_DIVING_BOARD = new ActivityInvolvementCodeType("1661");

	/// <summary>Track motor sport ("1452")</summary>
	public static readonly ActivityInvolvementCodeType C1452_TRACK_MOTOR_SPORT = new ActivityInvolvementCodeType("1452");

	/// <summary>Science Club ("6023")</summary>
	public static readonly ActivityInvolvementCodeType C6023_SCIENCE_CLUB = new ActivityInvolvementCodeType("6023");

	/// <summary>Carpet bowls ("1161")</summary>
	public static readonly ActivityInvolvementCodeType C1161_CARPET_BOWLS = new ActivityInvolvementCodeType("1161");

	/// <summary>Bike sports, n.f.d. ("1210")</summary>
	public static readonly ActivityInvolvementCodeType C1210_BIKE_SPORTS_NFD = new ActivityInvolvementCodeType("1210");

	/// <summary>Wind surfing ("1801")</summary>
	public static readonly ActivityInvolvementCodeType C1801_WIND_SURFING = new ActivityInvolvementCodeType("1801");

	/// <summary>Canoe polo ("1771")</summary>
	public static readonly ActivityInvolvementCodeType C1771_CANOE_POLO = new ActivityInvolvementCodeType("1771");

	/// <summary>Student representative council president ("2012")</summary>
	public static readonly ActivityInvolvementCodeType C2012_STUDENT_REPRESENTATIVE_COUNCIL = new ActivityInvolvementCodeType("2012");

	/// <summary>Motorised water sports, n.f.d. ("1760")</summary>
	public static readonly ActivityInvolvementCodeType C1760_MOTORISED_WATER_SPORTS = new ActivityInvolvementCodeType("1760");

	/// <summary>Polo ("1372")</summary>
	public static readonly ActivityInvolvementCodeType C1372_POLO = new ActivityInvolvementCodeType("1372");

	/// <summary>Boy Scouts ("3014")</summary>
	public static readonly ActivityInvolvementCodeType C3014_BOY_SCOUTS = new ActivityInvolvementCodeType("3014");

	/// <summary>Dog racing ("1241")</summary>
	public static readonly ActivityInvolvementCodeType C1241_DOG_RACING = new ActivityInvolvementCodeType("1241");

	/// <summary>Drama club ("6012")</summary>
	public static readonly ActivityInvolvementCodeType C6012_DRAMA_CLUB = new ActivityInvolvementCodeType("6012");

	/// <summary>Literary publications ("5024")</summary>
	public static readonly ActivityInvolvementCodeType C5024_LITERARY_PUBLICATIONS = new ActivityInvolvementCodeType("5024");

	/// <summary>Rowing ("1521")</summary>
	public static readonly ActivityInvolvementCodeType C1521_ROWING = new ActivityInvolvementCodeType("1521");

	/// <summary>Tee ball (T ball) ("1622")</summary>
	public static readonly ActivityInvolvementCodeType C1622_TEE_BALL_T_BALL = new ActivityInvolvementCodeType("1622");

	/// <summary>Bodybuilding ("1791")</summary>
	public static readonly ActivityInvolvementCodeType C1791_BODYBUILDING = new ActivityInvolvementCodeType("1791");

	/// <summary>Cheerleading ("1845")</summary>
	public static readonly ActivityInvolvementCodeType C1845_CHEERLEADING = new ActivityInvolvementCodeType("1845");

	/// <summary>Other club or organization ("6039")</summary>
	public static readonly ActivityInvolvementCodeType C6039_OT_CLUB_OR_ORGANIZATION = new ActivityInvolvementCodeType("6039");

	/// <summary>Soccer (Outdoor) ("1612")</summary>
	public static readonly ActivityInvolvementCodeType C1612_SOCCER_OUTDOOR = new ActivityInvolvementCodeType("1612");

	///<summary>Wrap an arbitrary string value in an ActivityInvolvementCodeType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static ActivityInvolvementCodeType Wrap( String wrappedValue ) {
		return new ActivityInvolvementCodeType( wrappedValue );
	}

	private ActivityInvolvementCodeType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
