// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.au.Student
{
	///<summary>
	/// Defines the set of values that can be specified whenever a FTPTStatusCodeType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a FTPTStatusCodeType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	[Serializable]
	public class FTPTStatusCodeType : SifEnum
	{
	/// <summary>Full Time ("01")</summary>
	public static readonly FTPTStatusCodeType C01_FULL_TIME = new FTPTStatusCodeType("01");

	/// <summary>Part Time ("02")</summary>
	public static readonly FTPTStatusCodeType C02_PART_TIME = new FTPTStatusCodeType("02");

	///<summary>Wrap an arbitrary string value in a FTPTStatusCodeType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static FTPTStatusCodeType Wrap( String wrappedValue ) {
		return new FTPTStatusCodeType( wrappedValue );
	}

	private FTPTStatusCodeType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
