// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Energymanagement{

/// <summary>A Type</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.6</para>
/// </remarks>
[Serializable]
public class Type : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of a Type
	/// </summary>
	public Type() : base ( EnergymanagementDTD.TYPE ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="energyZoneName">Text description of Energy Zone Area to which readings will apply.</param>
	///
	public Type( string energyZoneName ) : base( EnergymanagementDTD.TYPE )
	{
		this.EnergyZoneName = energyZoneName;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Type( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { EnergymanagementDTD.TYPE_ENERGYZONENAME }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Facility&gt;</c> element.
	/// </summary>
	/// <value> The <c>Facility</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Type of educational facility. Either the faciity type or the description must be provided."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string Facility
	{
		get
		{ 
			return GetFieldValue( EnergymanagementDTD.TYPE_FACILITY );
		}
		set
		{
			SetField( EnergymanagementDTD.TYPE_FACILITY, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;Facility&gt;</c> element.
	/// </summary>
	/// <param name="val">A Facility object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Type of educational facility. Either the faciity type or the description must be provided."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public void SetFacility( Facility val )
	{
		SetField( EnergymanagementDTD.TYPE_FACILITY, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Description&gt;</c> element.
	/// </summary>
	/// <value> The <c>Description</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: ""Used when location type is not covered by prefixed values in enumerated facility type list.
	/// 
	///             Used when location type is not covered by prefixed values in enumerated facility type list.""</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string Description
	{
		get
		{
			return (string) GetSifSimpleFieldValue( EnergymanagementDTD.TYPE_DESCRIPTION ) ;
		}
		set
		{
			SetFieldValue( EnergymanagementDTD.TYPE_DESCRIPTION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EnergyZoneName&gt;</c> element.
	/// </summary>
	/// <value> The <c>EnergyZoneName</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Text description of Energy Zone Area to which readings will apply."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string EnergyZoneName
	{
		get
		{
			return (string) GetSifSimpleFieldValue( EnergymanagementDTD.TYPE_ENERGYZONENAME ) ;
		}
		set
		{
			SetFieldValue( EnergymanagementDTD.TYPE_ENERGYZONENAME, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;TagList&gt;</c> element.
	/// </summary>
	/// <value> A TagList </value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this null as: "List of energy zone identifiers (each consisting of a Name and Value)."</para>
	/// <para>To remove the <c>TagList</c>, set <c>TagList</c> to <c>null</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public TagList TagList
	{
		get
		{
			return (TagList)GetChild( EnergymanagementDTD.TYPE_TAGLIST);
		}
		set
		{
			RemoveChild( EnergymanagementDTD.TYPE_TAGLIST);
			if( value != null)
			{
				AddChild( EnergymanagementDTD.TYPE_TAGLIST, value );
			}
		}
	}

}}
