// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Hrfin{

/// <summary>This object contains HR contract information related to employees.  SIF_Events are reported.</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 1.5r1</para>
/// </remarks>
[Serializable]
public class EmployeeContract : SifDataObject
{
	/// <summary>
	/// Creates an instance of an EmployeeContract
	/// </summary>
	public EmployeeContract() : base( Adk.SifVersion, HrfinDTD.EMPLOYEECONTRACT ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="refId">The GUID of the employee contract information.</param>
	///<param name="employeePersonalRefId">The GUID that refers to the EmployeePersonal object.</param>
	///<param name="baseSalary">Base salary of employee for this contact in whole dollars</param>
	///<param name="contractStartDate">Contractual start date.</param>
	///<param name="contractEndDate">Contractual ending date.</param>
	///
	public EmployeeContract( string refId, string employeePersonalRefId, MonetaryAmount baseSalary, DateTime? contractStartDate, DateTime? contractEndDate ) : base( Adk.SifVersion, HrfinDTD.EMPLOYEECONTRACT )
	{
		this.RefId = refId;
		this.EmployeePersonalRefId = employeePersonalRefId;
		this.BaseSalary = baseSalary;
		this.ContractStartDate = contractStartDate;
		this.ContractEndDate = contractEndDate;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected EmployeeContract( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { HrfinDTD.EMPLOYEECONTRACT_REFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>RefId</c> attribute.
	/// </summary>
	/// <value> The <c>RefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The GUID of the employee contract information."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public override string RefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( HrfinDTD.EMPLOYEECONTRACT_REFID ) ;
		}
		set
		{
			SetFieldValue( HrfinDTD.EMPLOYEECONTRACT_REFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>EmployeePersonalRefId</c> attribute.
	/// </summary>
	/// <value> The <c>EmployeePersonalRefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The GUID that refers to the EmployeePersonal object."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public string EmployeePersonalRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( HrfinDTD.EMPLOYEECONTRACT_EMPLOYEEPERSONALREFID ) ;
		}
		set
		{
			SetFieldValue( HrfinDTD.EMPLOYEECONTRACT_EMPLOYEEPERSONALREFID, new SifString( value ), value );
		}
	}

	///<summary>Sets the value of the <c>&lt;BaseSalary&gt;</c> element.</summary>
	/// <param name="Value">Gets or sets the content value of the &amp;lt;MonetaryAmount&amp;gt; element</param>
	///<remarks>
	/// <para>This form of <c>setBaseSalary</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>BaseSalary</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public void SetBaseSalary( decimal? Value ) {
		RemoveChild( HrfinDTD.EMPLOYEECONTRACT_BASESALARY);
		AddChild( HrfinDTD.EMPLOYEECONTRACT_BASESALARY, new MonetaryAmount( Value ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;BaseSalary&gt;</c> element.
	/// </summary>
	/// <value> A MonetaryAmount </value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this null as: "Base salary of employee for this contact in whole dollars"</para>
	/// <para>To remove the <c>MonetaryAmount</c>, set <c>BaseSalary</c> to <c>null</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public MonetaryAmount BaseSalary
	{
		get
		{
			return (MonetaryAmount)GetChild( HrfinDTD.EMPLOYEECONTRACT_BASESALARY);
		}
		set
		{
			RemoveChild( HrfinDTD.EMPLOYEECONTRACT_BASESALARY);
			if( value != null)
			{
				AddChild( HrfinDTD.EMPLOYEECONTRACT_BASESALARY, value );
			}
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ContractStartDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ContractStartDate</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Contractual start date."</para>
	/// <para>This element is known by more than one tag name depending on the version of SIF in use. 
	/// The ADK will use the tag names shown below when parsing and rendering elements of this kind.</para>
	/// <list type="table"><listheader><term>Version</term><description>Tag</description></listheader>;
	/// <item><term>2.0 (and greater)</term><description>&lt;ContractStartDate&gt;</description></item>
	/// </list>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public DateTime? ContractStartDate
	{
		get
		{
			return (DateTime?) GetSifSimpleFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTSTARTDATE ) ;
		}
		set
		{
			SetFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTSTARTDATE, new SifDate( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ContractEndDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ContractEndDate</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Contractual ending date."</para>
	/// <para>This element is known by more than one tag name depending on the version of SIF in use. 
	/// The ADK will use the tag names shown below when parsing and rendering elements of this kind.</para>
	/// <list type="table"><listheader><term>Version</term><description>Tag</description></listheader>;
	/// <item><term>2.0 (and greater)</term><description>&lt;ContractEndDate&gt;</description></item>
	/// </list>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public DateTime? ContractEndDate
	{
		get
		{
			return (DateTime?) GetSifSimpleFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTENDDATE ) ;
		}
		set
		{
			SetFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTENDDATE, new SifDate( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ContractTerm&gt;</c> element.
	/// </summary>
	/// <value> The <c>ContractTerm</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Contractual Term in school years"</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public string ContractTerm
	{
		get
		{ 
			return GetFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTTERM );
		}
		set
		{
			SetField( HrfinDTD.EMPLOYEECONTRACT_CONTRACTTERM, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;ContractTerm&gt;</c> element.
	/// </summary>
	/// <param name="val">A ContractualTermCode object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Contractual Term in school years"</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public void SetContractTerm( ContractualTermCode val )
	{
		SetField( HrfinDTD.EMPLOYEECONTRACT_CONTRACTTERM, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ContractDays&gt;</c> element.
	/// </summary>
	/// <value> The <c>ContractDays</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Number of days in service for contract total"</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public int? ContractDays
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTDAYS ) ;
		}
		set
		{
			SetFieldValue( HrfinDTD.EMPLOYEECONTRACT_CONTRACTDAYS, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AssignmentDays&gt;</c> element.
	/// </summary>
	/// <value> The <c>AssignmentDays</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Number of days per year employee is expected to work in this assignment"</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	public int? AssignmentDays
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( HrfinDTD.EMPLOYEECONTRACT_ASSIGNMENTDAYS ) ;
		}
		set
		{
			SetFieldValue( HrfinDTD.EMPLOYEECONTRACT_ASSIGNMENTDAYS, new SifInt( value ), value );
		}
	}

}}
