// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.au.School
{
	///<summary>
	/// Defines the set of values that can be specified whenever a ResourceReportLine_ObjectType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a ResourceReportLine_ObjectType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.5</para>
	/// </remarks>
	[Serializable]
	public class ResourceReportLine_ObjectType : SifEnum
	{
	/// <summary>StaffPersonal ("StaffPersonal")</summary>
	public static readonly ResourceReportLine_ObjectType STAFF_PERSONAL = new ResourceReportLine_ObjectType("StaffPersonal");

	/// <summary>TeachingGroup ("TeachingGroup")</summary>
	public static readonly ResourceReportLine_ObjectType TEACHING_GROUP = new ResourceReportLine_ObjectType("TeachingGroup");

	/// <summary>StudentPersonal ("StudentPersonal")</summary>
	public static readonly ResourceReportLine_ObjectType STUDENT_PERSONAL = new ResourceReportLine_ObjectType("StudentPersonal");

	///<summary>Wrap an arbitrary string value in a ResourceReportLine_ObjectType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static ResourceReportLine_ObjectType Wrap( String wrappedValue ) {
		return new ResourceReportLine_ObjectType( wrappedValue );
	}

	private ResourceReportLine_ObjectType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
