// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Programs{

/// <summary>A PartCTransitionMeetingNotHeldReasons</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class PartCTransitionMeetingNotHeldReasons : SifList<PartCTransitionMeetingNotHeldReason>
{
	/// <summary>
	/// Creates an instance of a PartCTransitionMeetingNotHeldReasons
	/// </summary>
	public PartCTransitionMeetingNotHeldReasons() : base ( ProgramsDTD.PARTCTRANSITIONMEETINGNOTHELDREASONS ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="partcTransitionMeetingNotHeldReason">A PartCTransitionMeetingNotHeldReason</param>
	///
	public PartCTransitionMeetingNotHeldReasons( PartCTransitionMeetingNotHeldReason partcTransitionMeetingNotHeldReason ) : base( ProgramsDTD.PARTCTRANSITIONMEETINGNOTHELDREASONS )
	{
		this.SafeAddChild( ProgramsDTD.PARTCTRANSITIONMEETINGNOTHELDREASONS_PARTCTRANSITIONMEETINGNOTHELDREASON, partcTransitionMeetingNotHeldReason );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected PartCTransitionMeetingNotHeldReasons( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
}}
