// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.us.Programs
{
	///<summary>
	/// Defines the set of values that can be specified whenever a ProgramAvailabilityCode
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a ProgramAvailabilityCode object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	[Serializable]
	public class ProgramAvailabilityCode : SifEnum
	{
	/// <summary>Other ("9999")</summary>
	public static readonly ProgramAvailabilityCode OTHER = new ProgramAvailabilityCode("9999");

	/// <summary>Summer ("0237")</summary>
	public static readonly ProgramAvailabilityCode SUMMER = new ProgramAvailabilityCode("0237");

	/// <summary>Evenings ("0239")</summary>
	public static readonly ProgramAvailabilityCode EVENINGS = new ProgramAvailabilityCode("0239");

	/// <summary>Weekend ("0234")</summary>
	public static readonly ProgramAvailabilityCode WEEKEND = new ProgramAvailabilityCode("0234");

	/// <summary>After school ("0236")</summary>
	public static readonly ProgramAvailabilityCode AFTER_SCHOOL = new ProgramAvailabilityCode("0236");

	/// <summary>Before School ("0235")</summary>
	public static readonly ProgramAvailabilityCode BEFORE_SCHOOL = new ProgramAvailabilityCode("0235");

	/// <summary>In-school service day ("0238")</summary>
	public static readonly ProgramAvailabilityCode IN_SCHOOL_SERVICE_DAY = new ProgramAvailabilityCode("0238");

	/// <summary>During school ("0231")</summary>
	public static readonly ProgramAvailabilityCode DURING_SCHOOL = new ProgramAvailabilityCode("0231");

	///<summary>Wrap an arbitrary string value in a ProgramAvailabilityCode object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static ProgramAvailabilityCode Wrap( String wrappedValue ) {
		return new ProgramAvailabilityCode( wrappedValue );
	}

	private ProgramAvailabilityCode( string enumDefValue ) : base( enumDefValue ) {}
	}
}
