// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Instr{

/// <summary>A MeasurementsRTI</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.6</para>
/// </remarks>
[Serializable]
public class MeasurementsRTI : SifElement
{
	/// <summary>
	/// Creates an instance of a MeasurementsRTI
	/// </summary>
	public MeasurementsRTI() : base ( InstrDTD.MEASUREMENTSRTI ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="measurementTool">The specific tool that will be used to gather data about how the student is improving.</param>
	///<param name="frequencyofMeasure">The frequency of the measuement.</param>
	///
	public MeasurementsRTI( string measurementTool, FrequencyTimeCode frequencyofMeasure ) : base( InstrDTD.MEASUREMENTSRTI )
	{
		this.MeasurementTool = measurementTool;
		this.SetFrequencyofMeasure( frequencyofMeasure );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected MeasurementsRTI( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { InstrDTD.MEASUREMENTSRTI_MEASUREMENTTOOL, InstrDTD.MEASUREMENTSRTI_FREQUENCYOFMEASURE }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;MeasurementTool&gt;</c> element.
	/// </summary>
	/// <value> The <c>MeasurementTool</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The specific tool that will be used to gather data about how the student is improving."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string MeasurementTool
	{
		get
		{
			return (string) GetSifSimpleFieldValue( InstrDTD.MEASUREMENTSRTI_MEASUREMENTTOOL ) ;
		}
		set
		{
			SetFieldValue( InstrDTD.MEASUREMENTSRTI_MEASUREMENTTOOL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;FrequencyofMeasure&gt;</c> element.
	/// </summary>
	/// <value> The <c>FrequencyofMeasure</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The frequency of the measuement."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string FrequencyofMeasure
	{
		get
		{ 
			return GetFieldValue( InstrDTD.MEASUREMENTSRTI_FREQUENCYOFMEASURE );
		}
		set
		{
			SetField( InstrDTD.MEASUREMENTSRTI_FREQUENCYOFMEASURE, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;FrequencyofMeasure&gt;</c> element.
	/// </summary>
	/// <param name="val">A FrequencyTimeCode object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "The frequency of the measuement."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public void SetFrequencyofMeasure( FrequencyTimeCode val )
	{
		SetField( InstrDTD.MEASUREMENTSRTI_FREQUENCYOFMEASURE, val );
	}

}}
