// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.us.Instr
{
	///<summary>
	/// Defines the set of values that can be specified whenever a ReferenceType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a ReferenceType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.5r1</para>
	/// </remarks>
	[Serializable]
	public class ReferenceType : SifEnum
	{
	/// <summary>SIF_GUID ("SIF_GUID")</summary>
	public static readonly ReferenceType SIF_GUID = new ReferenceType("SIF_GUID");

	/// <summary>URI ("URI")</summary>
	public static readonly ReferenceType URI = new ReferenceType("URI");

	///<summary>Wrap an arbitrary string value in a ReferenceType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static ReferenceType Wrap( String wrappedValue ) {
		return new ReferenceType( wrappedValue );
	}

	private ReferenceType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
