// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Instr{

/// <summary>A RelatedLearningStandards</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class RelatedLearningStandards : SifKeyedList<LearningStandardDocumentRefId>
{
	/// <summary>
	/// Creates an instance of a RelatedLearningStandards
	/// </summary>
	public RelatedLearningStandards() : base ( InstrDTD.RELATEDLEARNINGSTANDARDS ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="learningStandardDocumentRefId">Links to related LearningStandardDocument</param>
	///
	public RelatedLearningStandards( LearningStandardDocumentRefId learningStandardDocumentRefId ) : base( InstrDTD.RELATEDLEARNINGSTANDARDS )
	{
		this.SafeAddChild( InstrDTD.RELATEDLEARNINGSTANDARDS_LEARNINGSTANDARDDOCUMENTREFID, learningStandardDocumentRefId );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected RelatedLearningStandards( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	///<summary>Adds the value of the <c>&lt;LearningStandardDocumentRefId&gt;</c> element.</summary>
	/// <param name="Value">Gets or sets the content value of the &amp;lt;LearningStandardDocumentRefId&amp;gt; element</param>
	///<remarks>
	/// <para>This form of <c>setLearningStandardDocumentRefId</c> is provided as a convenience method
	/// that is functionally equivalent to the method <c>AddLearningStandardDocumentRefId</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void AddLearningStandardDocumentRefId( string Value ) {
		AddChild( InstrDTD.RELATEDLEARNINGSTANDARDS_LEARNINGSTANDARDDOCUMENTREFID, new LearningStandardDocumentRefId( Value ) );
	}

}}
