// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.uk.Common;

namespace OpenADK.Library.uk.Learner{

/// <summary>This object contains information about a learner's enrolment in a course (teaching group) or other (class, homeroom or registration) group. Compare with US/Canada object: StudentSectionEnrollment</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class LearnerGroupEnrolment : SifDataObject
{
	/// <summary>
	/// Creates an instance of a LearnerGroupEnrolment
	/// </summary>
	public LearnerGroupEnrolment() : base( Adk.SifVersion, LearnerDTD.LEARNERGROUPENROLMENT ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="refId">The ID (GUID) that uniquely identifies this LearnerGroupEnrolment entity. </param>
	///<param name="learnerPersonalRefId">The ID (GUID) of the learner to whom the enrolment information applies. </param>
	///<param name="schoolGroupRefId">The ID (GUID) of the group in which this learner is enroled. </param>
	///<param name="schoolYear">School year for which the information is applicable, expressed as the four-digit year in which the school year ends (e.g. 2007 for the 2006/07 school year). Where a group membership is valid across multiple years, the current year at the time of publication will be used. </param>
	///
	public LearnerGroupEnrolment( string refId, string learnerPersonalRefId, string schoolGroupRefId, int? schoolYear ) : base( Adk.SifVersion, LearnerDTD.LEARNERGROUPENROLMENT )
	{
		this.RefId = refId;
		this.LearnerPersonalRefId = learnerPersonalRefId;
		this.SchoolGroupRefId = schoolGroupRefId;
		this.SchoolYear = schoolYear;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected LearnerGroupEnrolment( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { LearnerDTD.LEARNERGROUPENROLMENT_REFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>RefId</c> attribute.
	/// </summary>
	/// <value> The <c>RefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The ID (GUID) that uniquely identifies this LearnerGroupEnrolment entity. "</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public override string RefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_REFID ) ;
		}
		set
		{
			SetFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_REFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>LearnerPersonalRefId</c> attribute.
	/// </summary>
	/// <value> The <c>LearnerPersonalRefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The ID (GUID) of the learner to whom the enrolment information applies. "</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string LearnerPersonalRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_LEARNERPERSONALREFID ) ;
		}
		set
		{
			SetFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_LEARNERPERSONALREFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>SchoolGroupRefId</c> attribute.
	/// </summary>
	/// <value> The <c>SchoolGroupRefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The ID (GUID) of the group in which this learner is enroled. "</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string SchoolGroupRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_SCHOOLGROUPREFID ) ;
		}
		set
		{
			SetFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_SCHOOLGROUPREFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SchoolYear&gt;</c> element.
	/// </summary>
	/// <value> The <c>SchoolYear</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "School year for which the information is applicable, expressed as the four-digit year in which the school year ends (e.g. 2007 for the 2006/07 school year). Where a group membership is valid across multiple years, the current year at the time of publication will be used. "</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public int? SchoolYear
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_SCHOOLYEAR ) ;
		}
		set
		{
			SetFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_SCHOOLYEAR, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EntryDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>EntryDate</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Date from when this enrolment is valid."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public DateTime? EntryDate
	{
		get
		{
			return (DateTime?) GetSifSimpleFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_ENTRYDATE ) ;
		}
		set
		{
			SetFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_ENTRYDATE, new SifDate( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExitDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExitDate</c> element of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this element as: "Date on which the learner's enrolment ends or has ended."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public DateTime? ExitDate
	{
		get
		{
			return (DateTime?) GetSifSimpleFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_EXITDATE ) ;
		}
		set
		{
			SetFieldValue( LearnerDTD.LEARNERGROUPENROLMENT_EXITDATE, new SifDate( value ), value );
		}
	}

}}
