// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Assessment{

/// <summary>A FormIdentifiers</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.6</para>
/// </remarks>
[Serializable]
public class FormIdentifiers : SifKeyedList<FormIdentifier>
{
	/// <summary>
	/// Creates an instance of a FormIdentifiers
	/// </summary>
	public FormIdentifiers() : base ( AssessmentDTD.FORMIDENTIFIERS ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="formIdentifier">Reference number for the form.</param>
	///
	public FormIdentifiers( FormIdentifier formIdentifier ) : base( AssessmentDTD.FORMIDENTIFIERS )
	{
		this.SafeAddChild( AssessmentDTD.FORMIDENTIFIERS_FORMIDENTIFIER, formIdentifier );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected FormIdentifiers( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { AssessmentDTD.FORMIDENTIFIERS_FORMIDENTIFIER }; }
	}

	///<summary>Adds the value of the <c>&lt;FormIdentifier&gt;</c> element.</summary>
	/// <param name="FormIdentifierType">The Type Codes indicate the type and/or uses of the identifier.</param>
	/// <param name="Value">Gets or sets the content value of the &amp;lt;FormIdentifier&amp;gt; element</param>
	///<remarks>
	/// <para>This form of <c>setFormIdentifier</c> is provided as a convenience method
	/// that is functionally equivalent to the method <c>AddFormIdentifier</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public void AddFormIdentifier( FormIdentifierType FormIdentifierType, string Value ) {
		AddChild( AssessmentDTD.FORMIDENTIFIERS_FORMIDENTIFIER, new FormIdentifier( FormIdentifierType, Value ) );
	}

}}
