// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Assessment{

/// <summary>A FormIdentifier</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.6</para>
/// </remarks>
[Serializable]
public class FormIdentifier : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of a FormIdentifier
	/// </summary>
	public FormIdentifier() : base ( AssessmentDTD.FORMIDENTIFIER ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="formIdentifierType">The Type Codes indicate the type and/or uses of the identifier.</param>
	///<param name="value">Gets or sets the content value of the &amp;lt;FormIdentifier&amp;gt; element</param>
	///
	public FormIdentifier( FormIdentifierType formIdentifierType, string value ) : base( AssessmentDTD.FORMIDENTIFIER )
	{
		this.SetFormIdentifierType( formIdentifierType );
		this.Value = value;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected FormIdentifier( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { AssessmentDTD.FORMIDENTIFIER_FORMIDENTIFIERTYPE }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;FormIdentifier&gt;</c> element.
	/// </summary>
	/// <value> The <c>Value</c> of the content of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this of the content as: "Gets or sets the content value of the &amp;lt;FormIdentifier&amp;gt; element"</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string Value
	{
		get
		{
			return (string) GetSifSimpleFieldValue( AssessmentDTD.FORMIDENTIFIER ) ;
		}
		set
		{
			SetFieldValue( AssessmentDTD.FORMIDENTIFIER, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>FormIdentifierType</c> attribute.
	/// </summary>
	/// <value> The <c>FormIdentifierType</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The Type Codes indicate the type and/or uses of the identifier."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string FormIdentifierType
	{
		get
		{ 
			return GetFieldValue( AssessmentDTD.FORMIDENTIFIER_FORMIDENTIFIERTYPE );
		}
		set
		{
			SetField( AssessmentDTD.FORMIDENTIFIER_FORMIDENTIFIERTYPE, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>FormIdentifierType</c> attribute.
	/// </summary>
	/// <param name="val">A FormIdentifierType object</param>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The Type Codes indicate the type and/or uses of the identifier."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public void SetFormIdentifierType( FormIdentifierType val )
	{
		SetField( AssessmentDTD.FORMIDENTIFIER_FORMIDENTIFIERTYPE, val );
	}

}}
