// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.au.Common;

namespace OpenADK.Library.au.Programs{

/// <summary>A ProgramFundingSources</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.3</para>
/// </remarks>
[Serializable]
public class ProgramFundingSources : SifKeyedList<ProgramFundingSource>
{
	/// <summary>
	/// Creates an instance of a ProgramFundingSources
	/// </summary>
	public ProgramFundingSources() : base ( ProgramsDTD.PROGRAMFUNDINGSOURCES ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="programFundingSource">A ProgramFundingSource</param>
	///
	public ProgramFundingSources( ProgramFundingSource programFundingSource ) : base( ProgramsDTD.PROGRAMFUNDINGSOURCES )
	{
		this.SafeAddChild( ProgramsDTD.PROGRAMFUNDINGSOURCES_PROGRAMFUNDINGSOURCE, programFundingSource );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected ProgramFundingSources( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { ProgramsDTD.PROGRAMFUNDINGSOURCES_PROGRAMFUNDINGSOURCE }; }
	}

	///<summary>Adds the value of the <c>&lt;ProgramFundingSource&gt;</c> element.</summary>
	/// <param name="Code">Funding source for the program, may be more than one.</param>
	///<remarks>
	/// <para>This form of <c>setProgramFundingSource</c> is provided as a convenience method
	/// that is functionally equivalent to the method <c>AddProgramFundingSource</c></para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	public void AddProgramFundingSource( ProgramFundingSourceCodeType Code ) {
		AddChild( ProgramsDTD.PROGRAMFUNDINGSOURCES_PROGRAMFUNDINGSOURCE, new ProgramFundingSource( Code ) );
	}

}}
