// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.au.Common;

namespace OpenADK.Library.au.Sif3assessment{

/// <summary>A Sif3AssessmentItemAssociation</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.6</para>
/// <para>Since: 2.6</para>
/// </remarks>
[Serializable]
public class Sif3AssessmentItemAssociation : SifDataObject
{
	/// <summary>
	/// Creates an instance of a Sif3AssessmentItemAssociation
	/// </summary>
	public Sif3AssessmentItemAssociation() : base( Adk.SifVersion, Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="refId">The GUID that uniquely identifies an instance of the object.</param>
	///<param name="assessmentItemRefId">An AssessmentItemRefId</param>
	///<param name="targetAssessmentItemRefId">A TargetAssessmentItemRefId</param>
	///<param name="associationType">An AssociationType</param>
	///
	public Sif3AssessmentItemAssociation( string refId, string assessmentItemRefId, string targetAssessmentItemRefId, AssociationType associationType ) : base( Adk.SifVersion, Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION )
	{
		this.RefId = refId;
		this.AssessmentItemRefId = assessmentItemRefId;
		this.TargetAssessmentItemRefId = targetAssessmentItemRefId;
		this.SetAssociationType( associationType );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Sif3AssessmentItemAssociation( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_REFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>RefId</c> attribute.
	/// </summary>
	/// <value> The <c>RefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "The GUID that uniquely identifies an instance of the object."</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public override string RefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_REFID ) ;
		}
		set
		{
			SetFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_REFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AssessmentItemRefId&gt;</c> element.
	/// </summary>
	/// <value> The <c>AssessmentItemRefId</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string AssessmentItemRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_ASSESSMENTITEMREFID ) ;
		}
		set
		{
			SetFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_ASSESSMENTITEMREFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;TargetAssessmentItemRefId&gt;</c> element.
	/// </summary>
	/// <value> The <c>TargetAssessmentItemRefId</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string TargetAssessmentItemRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_TARGETASSESSMENTITEMREFID ) ;
		}
		set
		{
			SetFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_TARGETASSESSMENTITEMREFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AssociationType&gt;</c> element.
	/// </summary>
	/// <value> The <c>AssociationType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public string AssociationType
	{
		get
		{ 
			return GetFieldValue( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_ASSOCIATIONTYPE );
		}
		set
		{
			SetField( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_ASSOCIATIONTYPE, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;AssociationType&gt;</c> element.
	/// </summary>
	/// <param name="val">A AssociationType object</param>
	/// <remarks>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	public void SetAssociationType( AssociationType val )
	{
		SetField( Sif3assessmentDTD.SIF3ASSESSMENTITEMASSOCIATION_ASSOCIATIONTYPE, val );
	}

}}
