// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.au.Common
{
	///<summary>
	/// Defines the set of values that can be specified whenever an AUCodeSetsFFPOSStatusCodeType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  an AUCodeSetsFFPOSStatusCodeType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.6</para>
	/// </remarks>
	[Serializable]
	public class AUCodeSetsFFPOSStatusCodeType : SifEnum
	{
	/// <summary>Not stated/Unknown ("9")</summary>
	public static readonly AUCodeSetsFFPOSStatusCodeType C9_UNKNOWN = new AUCodeSetsFFPOSStatusCodeType("9");

	/// <summary>FFPOS ("1")</summary>
	public static readonly AUCodeSetsFFPOSStatusCodeType C1_FFPOS = new AUCodeSetsFFPOSStatusCodeType("1");

	/// <summary>Non-FFPOS ("2")</summary>
	public static readonly AUCodeSetsFFPOSStatusCodeType C2_NON_FFPOS = new AUCodeSetsFFPOSStatusCodeType("2");

	///<summary>Wrap an arbitrary string value in an AUCodeSetsFFPOSStatusCodeType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static AUCodeSetsFFPOSStatusCodeType Wrap( String wrappedValue ) {
		return new AUCodeSetsFFPOSStatusCodeType( wrappedValue );
	}

	private AUCodeSetsFFPOSStatusCodeType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
