// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.au.Common
{
	///<summary>
	/// Defines the set of values that can be specified whenever an AustralianStandardClassificationOfReligiousGroupsASCRGType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  an AustralianStandardClassificationOfReligiousGroupsASCRGType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 2.3</para>
	/// </remarks>
	[Serializable]
	public class AustralianStandardClassificationOfReligiousGroupsASCRGType : SifEnum
	{
	/// <summary>Sukyo Mahikari ("6112")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6112_SUKYO_MAHIKARI = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6112");

	/// <summary>Eastern Orthodox, nfd ("2230")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2230_EASTERN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2230");

	/// <summary>Baha'i ("6031")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6031_BAHAI = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6031");

	/// <summary>Christadelphians ("2902")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2902_CHRISTADELPHIANS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2902");

	/// <summary>Apostolic Church of Queensland ("2901")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2901_APOSTOLIC_CHURCH_OF = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2901");

	/// <summary>Churches of Christ (Conference) ("2111")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2111_CHURCHES_OF_CHRIST_CONFERENCE = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2111");

	/// <summary>Oriental Orthodox, nec ("2219")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2219_ORIENTAL_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2219");

	/// <summary>Rhema Family Church ("2414")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2414_RHEMA_FAMILY_CHURCH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2414");

	/// <summary>Rastafarianism ("6994")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6994_RASTAFARIANISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6994");

	/// <summary>Community of Christ ("2152")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2152_COMMUNITY_OF_CHRIST = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2152");

	/// <summary>New Age, so described ("0004")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C0004_NEW_AGE_SO_DESCRIBED = new AustralianStandardClassificationOfReligiousGroupsASCRGType("0004");

	/// <summary>Paganism ("6133")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6133_PAGANISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6133");

	/// <summary>International Church of Christ ("2113")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2113_INTERNATIONAL_CHURCH_OF = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2113");

	/// <summary>Assyrian Church of the East ("2221")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2221_ASSYRIAN_CHURCH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2221");

	/// <summary>Confucianism ("6052")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6052_CONFUCIANISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6052");

	/// <summary>Other Protestant, nfd ("2800")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2800_OT_PROTESTANT_NFD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2800");

	/// <summary>Assyrian Apostolic, nec ("2229")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2229_ASSYRIAN_APOSTOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2229");

	/// <summary>Armenian Apostolic ("2212")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2212_ARMENIAN_APOSTOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2212");

	/// <summary>Churches of Christ, nfd ("2110")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2110_CHURCHES_OF_CHRIST = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2110");

	/// <summary>Humanism ("7013")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C7013_HUMANISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("7013");

	/// <summary>Ukrainian Orthodox ("2238")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2238_UKRAINIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2238");

	/// <summary>Church of Jesus Christ of LDS (Mormons) ("2151")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2151_CHURCH_OF_JESUS_CHRIST_OF_LDS_MORMONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2151");

	/// <summary>Unitarian ("2914")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2914_UNITARIAN = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2914");

	/// <summary>Taoism ("6053")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6053_TAOISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6053");

	/// <summary>Ancient Church of the East ("2222")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2222_ANCIENT_CHURCH_OFEAST = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2222");

	/// <summary>Assyrian Apostolic, nfd ("2220")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2220_ASSYRIAN_APOSTOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2220");

	/// <summary>Animism ("6131")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6131_ANIMISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6131");

	/// <summary>Aboriginal Evangelical Missions ("2801")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2801_ABORIGINAL_EVANGELICAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2801");

	/// <summary>Australian Aboriginal Traditional Religions ("6011")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6011_AUSTRALIAN_ABORIGINAL_TRADITIONAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6011");

	/// <summary>Temple Society ("2913")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2913_TEMPLE_SOCIETY = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2913");

	/// <summary>Not Stated ("0001")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C0001_NOT_STATED = new AustralianStandardClassificationOfReligiousGroupsASCRGType("0001");

	/// <summary>Tenrikyo ("6113")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6113_TENRIKYO = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6113");

	/// <summary>Chinese Religions, nec ("6059")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6059_CHINESE_RELIGIONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6059");

	/// <summary>Apostolic Church (Australia) ("2401")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2401_APOSTOLIC_CHURCH_AUSTRALIA = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2401");

	/// <summary>Free Reformed ("2253")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2253_FREE_REFORMED = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2253");

	/// <summary>Worldwide Church of God ("2915")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2915_WORLDWIDE_CHURCH_OF = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2915");

	/// <summary>Church of God, so described ("2002")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2002_CHURCH_OF_GOD_SO = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2002");

	/// <summary>Full Gospel Church ("2412")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2412_FULL_GOSPEL_CHURCH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2412");

	/// <summary>Hinduism ("3011")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C3011_HINDUISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("3011");

	/// <summary>Romanian Orthodox ("2235")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2235_ROMANIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2235");

	/// <summary>Ratana (Maori) ("2908")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2908_RATANA_MAORI = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2908");

	/// <summary>Ethiopian Orthodox Church ("2216")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2216_ETHIOPIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2216");

	/// <summary>Brethren ("2051")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2051_BRETHREN = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2051");

	/// <summary>Anglican Church of Australia ("2012")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2012_ANGLICAN_CHURCH_OF = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2012");

	/// <summary>Eastern Orthodox, nec ("2239")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2239_EASTERN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2239");

	/// <summary>Eckankar ("6993")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6993_ECKANKAR = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6993");

	/// <summary>Anglican, nfd ("2010")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2010_ANGLICAN_NFD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2010");

	/// <summary>Atheism ("7012")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C7012_ATHEISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("7012");

	/// <summary>Druidism ("6132")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6132_DRUIDISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6132");

	/// <summary>Presbyterian and Reformed, nfd ("2250")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2250_PRESBYTERIANREFORMED = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2250");

	/// <summary>Agnosticism ("7011")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C7011_AGNOSTICISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("7011");

	/// <summary>Christian Science ("2903")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2903_CHRISTIAN_SCIENCE = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2903");

	/// <summary>Presbyterian ("2251")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2251_PRESBYTERIAN = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2251");

	/// <summary>Bethesda Churches ("2403")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2403_BETHESDA_CHURCHES = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2403");

	/// <summary>Nature Religions, nec ("6139")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6139_NATURE_RELIGIONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6139");

	/// <summary>Antiochian Orthodox ("2232")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2232_ANTIOCHIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2232");

	/// <summary>Oriental Orthodox, nfd ("2210")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2210_ORIENTAL_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2210");

	/// <summary>Church of the Nazarene ("2804")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2804_CHURCH_OFNAZARENE = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2804");

	/// <summary>Baptist ("2031")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2031_BAPTIST = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2031");

	/// <summary>Chaldean Catholic ("2075")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2075_CHALDEAN_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2075");

	/// <summary>Western Catholic ("2071")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2071_WESTERN_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2071");

	/// <summary>Zoroastrianism ("6998")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6998_ZOROASTRIANISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6998");

	/// <summary>Not Defined ("0003")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C0003_NOT_DEFINED = new AustralianStandardClassificationOfReligiousGroupsASCRGType("0003");

	/// <summary>Jehovah's Witnesses ("2131")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2131_JEHOVAHS_WITNESSES = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2131");

	/// <summary>Greek Orthodox ("2233")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2233_GREEK_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2233");

	/// <summary>Japanese Religions, nec ("6119")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6119_JAPANESE_RELIGIONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6119");

	/// <summary>Faith Churches ("2408")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2408_FAITH_CHURCHES = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2408");

	/// <summary>Ukrainian Catholic ("2074")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2074_UKRAINIAN_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2074");

	/// <summary>Christian City Church ("2404")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2404_CHRISTIAN_CITY_CHURCH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2404");

	/// <summary>New Churches (Swedenborgian) ("2907")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2907_NEW_CHURCHES_SWEDENBORGIAN = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2907");

	/// <summary>Christian Life Churches International ("2405")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2405_CHRISTIAN_LIFE_CHURCHES = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2405");

	/// <summary>Spiritualism ("6171")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6171_SPIRITUALISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6171");

	/// <summary>Japanese Religions, nfd ("6110")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6110_JAPANESE_RELIGIONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6110");

	/// <summary>Judaism ("5011")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C5011_JUDAISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("5011");

	/// <summary>Christian, nfd ("2000")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2000_CHRISTIAN_NFD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2000");

	/// <summary>Other Christian, nfd ("2900")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2900_OT_CHRISTIAN_NFD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2900");

	/// <summary>Caodaism ("6991")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6991_CAODAISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6991");

	/// <summary>Congregational ("2805")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2805_CONGREGATIONAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2805");

	/// <summary>Church of Christ (Nondenominational) ("2112")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2112_CHURCH_OF_CHRIST_NONDENOMINATIONAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2112");

	/// <summary>New Church Alliance, so described ("2004")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2004_NEW_CHURCH_ALLIANCE_SO = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2004");

	/// <summary>Chinese Religions, nfd ("6050")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6050_CHINESE_RELIGIONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6050");

	/// <summary>Apostolic Church, so described ("2001")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2001_APOSTOLIC_CHURCH_SO = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2001");

	/// <summary>Religious Science ("2911")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2911_RELIGIOUS_SCIENCE = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2911");

	/// <summary>Religious Society of Friends (Quakers) ("2912")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2912_RELIGIOUS_SOCIETY_OF_FRIENDS_QUAKERS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2912");

	/// <summary>Australian Christian Churches, so described ("2003")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2003_AUSTRALIAN_CHRISTIAN_CHURCHES_SO = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2003");

	/// <summary>Church of Jesus Christ of Latter Day Saints, nfd ("2150")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2150_CHURCH_OF_JESUS_CHRIST_OF_LATTER_DAY_SAINTS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2150");

	/// <summary>Born Again Christian ("2802")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2802_BORN_AGAIN_CHRISTIAN = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2802");

	/// <summary>Druse ("6071")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6071_DRUSE = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6071");

	/// <summary>Ancestor Veneration ("6051")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6051_ANCESTOR_VENERATION = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6051");

	/// <summary>Buddhism ("1011")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C1011_BUDDHISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("1011");

	/// <summary>Lutheran ("2171")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2171_LUTHERAN = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2171");

	/// <summary>Christian Outreach Centres ("2406")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2406_CHRISTIAN_OUTREACH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2406");

	/// <summary>Reformed ("2252")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2252_REFORMED = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2252");

	/// <summary>Church of Scientology ("6992")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6992_CHURCH_OF_SCIENTOLOGY = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6992");

	/// <summary>Foursquare Gospel Church ("2411")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2411_FOURSQUARE_GOSPEL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2411");

	/// <summary>Serbian Orthodox ("2237")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2237_SERBIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2237");

	/// <summary>Pentecostal, nfd ("2400")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2400_PENTECOSTAL_NFD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2400");

	/// <summary>No Religion, nfd ("7010")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C7010_NO_RELIGION_NFD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("7010");

	/// <summary>Other Christian, nec ("2999")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2999_OT_CHRISTIAN_NEC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2999");

	/// <summary>Wiccan/Witchcraft ("6135")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6135_WICCAN_WITCHCRAFT = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6135");

	/// <summary>Pantheism ("6134")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6134_PANTHEISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6134");

	/// <summary>Rationalism ("7014")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C7014_RATIONALISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("7014");

	/// <summary>Jainism ("6997")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6997_JAINISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6997");

	/// <summary>Sikhism ("6151")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6151_SIKHISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6151");

	/// <summary>Wesleyan Methodist Church ("2808")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2808_WESLEYAN_METHODIST = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2808");

	/// <summary>Russian Orthodox ("2236")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2236_RUSSIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2236");

	/// <summary>Uniting Church ("2331")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2331_UNITING_CHURCH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2331");

	/// <summary>Theism ("0005")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C0005_THEISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("0005");

	/// <summary>Religious Belief, nfd ("0002")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C0002_RELIGIOUS_BELIEF = new AustralianStandardClassificationOfReligiousGroupsASCRGType("0002");

	/// <summary>New Apostolic Church ("2906")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2906_NEW_APOSTOLIC_CHURCH = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2906");

	/// <summary>Ethnic Evangelical Churches ("2806")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2806_ETHNIC_EVANGELICAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2806");

	/// <summary>Liberal Catholic Church ("2905")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2905_LIBERAL_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2905");

	/// <summary>Coptic Orthodox Church ("2214")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2214_COPTIC_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2214");

	/// <summary>Christian and Missionary Alliance ("2803")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2803_CHRISTIANMISSIONARY = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2803");

	/// <summary>Maronite Catholic ("2072")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2072_MARONITE_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2072");

	/// <summary>Syrian Orthodox Church ("2215")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2215_SYRIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2215");

	/// <summary>Other Protestant, nec ("2899")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2899_OT_PROTESTANT_NEC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2899");

	/// <summary>United Pentecostal ("2415")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2415_UNITED_PENTECOSTAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2415");

	/// <summary>Macedonian Orthodox ("2234")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2234_MACEDONIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2234");

	/// <summary>Gnostic Christians ("2904")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2904_GNOSTIC_CHRISTIANS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2904");

	/// <summary>Religious Groups, nec ("6999")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6999_RELIGIOUS_GROUPS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6999");

	/// <summary>Catholic, nec ("2079")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2079_CATHOLIC_NEC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2079");

	/// <summary>Shinto ("6111")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6111_SHINTO = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6111");

	/// <summary>Pentecostal, nec ("2499")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2499_PENTECOSTAL_NEC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2499");

	/// <summary>Albanian Orthodox ("2231")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2231_ALBANIAN_ORTHODOX = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2231");

	/// <summary>Assemblies of God ("2402")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2402_ASSEMBLIES_OF_GOD = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2402");

	/// <summary>Melkite Catholic ("2073")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2073_MELKITE_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2073");

	/// <summary>Revival Centres ("2413")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2413_REVIVAL_CENTRES = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2413");

	/// <summary>Independent Evangelical Churches ("2807")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2807_INDEPENDENT_EVANGELICAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2807");

	/// <summary>Theosophy ("6996")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6996_THEOSOPHY = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6996");

	/// <summary>Satanism ("6995")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6995_SATANISM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6995");

	/// <summary>Nature Religions, nfd ("6130")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C6130_NATURE_RELIGIONS = new AustralianStandardClassificationOfReligiousGroupsASCRGType("6130");

	/// <summary>Salvation Army ("2271")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2271_SALVATION_ARMY = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2271");

	/// <summary>Anglican Catholic Church ("2013")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2013_ANGLICAN_CATHOLIC = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2013");

	/// <summary>Christian Revival Crusade ("2407")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2407_CHRISTIAN_REVIVAL = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2407");

	/// <summary>Islam ("4011")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C4011_ISLAM = new AustralianStandardClassificationOfReligiousGroupsASCRGType("4011");

	/// <summary>Seventh-day Adventist ("2311")</summary>
	public static readonly AustralianStandardClassificationOfReligiousGroupsASCRGType C2311_SEVENTHDAY_ADVENTIST = new AustralianStandardClassificationOfReligiousGroupsASCRGType("2311");

	///<summary>Wrap an arbitrary string value in an AustralianStandardClassificationOfReligiousGroupsASCRGType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static AustralianStandardClassificationOfReligiousGroupsASCRGType Wrap( String wrappedValue ) {
		return new AustralianStandardClassificationOfReligiousGroupsASCRGType( wrappedValue );
	}

	private AustralianStandardClassificationOfReligiousGroupsASCRGType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
