// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using OpenADK.Util;
using OpenADK.Library;
using OpenADK.Library.Impl;
using CommonDTD = OpenADK.Library.us.Common.CommonDTD;
using ReportingDTD = OpenADK.Library.us.Reporting.ReportingDTD;

namespace OpenADK.Library.us.Infrastructure
{

// BEGIN FILE... (SIFDTD_Comments_CS.txt)

	/// <summary>Metadata for the Schools Interoperability Framework (SIF)</summary>
	/// <remarks>
	/// <para>
	/// SIFDTD defines global {@linkplain com.edustructures.sifworks.ElementDef} 
	/// constants that describe SIF Data Objects, elements, and attributes across all 
	/// supported versions of the SIF Specification. The ADK uses this metadata 
	/// internally to parse and render SIF Data Objects.  In addition, many of the 
	/// framework APIs require that the programmer pass an ElementDef constant from 
	/// the SIFDTD class to identify an object, element, or attribute.
	/// </para>
	/// <para>
	/// ElementDef constants are named <c>[PARENT_]ENTITY</c>, where 
	/// <c>PARENT</c> is the name of the parent element and 
	/// <c>ENTITY</c> is the name of the element or attribute 
	/// encapsulated by the ElementDef. Some examples of ElementDef constants defined
	/// by this class include:
	/// </para>
	/// <list type="table">
	/// <listheader><term>IElementDef</term><description>Description</description></listheader>
	/// <item><term><c>SIFDTD.STUDENTPERSONAL</c></term><description>Identifies the StudentPersonal data object</description></item>
	/// <item><term><c>SIFDTD.SCHOOLINFO</c></term><description>Identifies the SchoolInfo data object</description></item>
	/// </list>
	/// Many of the Adk's public interfaces require an ElementDef constant to be passed
	/// as a parameter. For example, the first parameter to the <see cref="IZone.SetSubscriber"/>
	/// method is an IElementDef:
	/// <code>myZone.setSubscriber( SIFDTD.BUSINFO, this, ADKFlags.PROV_SUBSCRIBE );</code>
	/// ElementDef also identifies child elements and attributes as demonstrated by the	<c>Query.AddCondition</c> method:
	/// <code>
	/// Query query = new Query( SifDtd.STUDENTPERSONAL );
	/// query.AddCondition( SifDtd.STUDENTPERSONAL_REFID, Condition.EQ, "4A37969803F0D00322AF0EB969038483" );
	/// </code>
	/// <para>
	/// <b>SDO Libraries</b>
	/// </para>
	/// <para>
	/// ElementDef metadata is grouped into "SDO Libraries", which are organized along 
	/// SIF Working Group boundaries. SDO Libraries are loaded into the <c>SifDdt</c> 
	/// class when the Adk is initialized. All or part of the metadata is loaded into depending on the flags passed to the
	/// <see cref="Adk.Initialize(SifVersion, SdoLibraryType)"/> method,
	/// metadata from one or more SDO Libraries may be loaded. For example, the following
	/// call loads metadata for the <c>Student Information Working Group Objects</c>  
	/// and <c>Transportation And Geographic Information Working Group Objects</c> 
	/// (Common Elements and <c>Infrastructure Working Group Objects</c> metadata is always loaded
	/// </para>
	/// <code>Adk.Initialize( SiFVersion.LATEST, SdoLibraryType.Student | SdoLibraryType.Trans )</code>
	/// <para>
	/// If an given SDO Library is not loaded, all of the SIFDTD constants that belong
	/// to that library will be <code>null</code> and cannot be referenced. For example,
	/// given the SDO Libraries loaded above, attempting to reference the 
	/// <code>SIFDTD.LIBRARYPATRONSTATUS</code> object from the Library Automation Working
	/// Group would result in a NullPointerException:
	/// </para>
	/// <code>SifDtd.LIBRARYPATRONSTATUS.Name;</code>
	/// </remarks>
	public class InfrastructureDTD : OpenADK.Library.Impl.SdoLibraryImpl
	{
	/** Defines the &lt;Authentication&gt; SIF Data Object */
	public static IElementDef AUTHENTICATION = null;
	/** Defines the &lt;AuthenticationInfo&gt; SIF Data Object */
	public static IElementDef AUTHENTICATIONINFO = null;
	/** Defines the &lt;AuthSystem&gt; SIF Data Object */
	public static IElementDef AUTHSYSTEM = null;
	/** Defines the &lt;PasswordList&gt; SIF Data Object */
	public static IElementDef PASSWORDLIST = null;


	// Field elements of AUTHENTICATION (4 fields)
	/** Defines the RefId attribute as a child of &lt;Authentication&gt; */
	public static IElementDef AUTHENTICATION_REFID = null;
	/** Defines the SIF_RefId attribute as a child of &lt;Authentication&gt; */
	public static IElementDef AUTHENTICATION_SIF_REFID = null;
	/** Defines the SIF_RefObject attribute as a child of &lt;Authentication&gt; */
	public static IElementDef AUTHENTICATION_SIF_REFOBJECT = null;
	/** Defines the &lt;AuthenticationInfo&gt; element as a child of &lt;Authentication&gt; */
	public static IElementDef AUTHENTICATION_AUTHENTICATIONINFO = null;
	/** SIF 1.5 and later: Defines the built-in SIF_ExtendedElements element common to all SIF Data Objects */
	public static IElementDef AUTHENTICATION_SIF_EXTENDEDELEMENTS = null;
	/** SIF 2.0 and later: Defines the built-in SIF_Metadata element common to all SIF Data Objects */
	public static IElementDef AUTHENTICATION_SIF_METADATA = null;

	// Field elements of AUTHENTICATIONINFO (4 fields)
	/** Defines the &lt;System&gt; element as a child of &lt;AuthenticationInfo&gt; */
	public static IElementDef AUTHENTICATIONINFO_SYSTEM = null;
	/** Defines the &lt;Username&gt; element as a child of &lt;AuthenticationInfo&gt; */
	public static IElementDef AUTHENTICATIONINFO_USERNAME = null;
	/** Defines the &lt;DistinguishedName&gt; element as a child of &lt;AuthenticationInfo&gt; */
	public static IElementDef AUTHENTICATIONINFO_DISTINGUISHEDNAME = null;
	/** Defines the &lt;PasswordList&gt; element as a child of &lt;AuthenticationInfo&gt; */
	public static IElementDef AUTHENTICATIONINFO_PASSWORDLIST = null;

	// Field elements of AUTHSYSTEM (1 fields)
	/** Defines the Type attribute as a child of &lt;AuthSystem&gt; */
	public static IElementDef AUTHSYSTEM_TYPE = null;

	// Field elements of PASSWORDLIST (1 fields)
	/** Defines the &lt;Password&gt; element as a child of &lt;PasswordList&gt; */
	public static IElementDef PASSWORDLIST_PASSWORD = null;

	public override void Load()
	{
		//  Objects defined by this SDO Library...

		AUTHENTICATION = new ElementDefImpl( null, "Authentication", null, 0, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_OBJECT), SifVersion.SIF15r1, SifVersion.SIF26 );
		AUTHENTICATIONINFO = new ElementDefImpl( null, "AuthenticationInfo", null, 0, SifDtd.INFRASTRUCTURE, "us", 0, SifVersion.SIF15r1, SifVersion.SIF26 );
		AUTHSYSTEM = new ElementDefImpl( null, "AuthSystem", "System", 0, SifDtd.INFRASTRUCTURE, "us", 0, SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		PASSWORDLIST = new ElementDefImpl( null, "PasswordList", null, 0, SifDtd.INFRASTRUCTURE, "us", 0, SifVersion.SIF15r1, SifVersion.SIF26 );


		// <Authentication> fields (4 entries)
		InfrastructureDTD.AUTHENTICATION_REFID = new ElementDefImpl( AUTHENTICATION, "RefId", null, 1, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_ATTRIBUTE), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		InfrastructureDTD.AUTHENTICATION_SIF_REFID = new ElementDefImpl( AUTHENTICATION, "SIF_RefId", "SifRefId", 2, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_ATTRIBUTE), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		InfrastructureDTD.AUTHENTICATION_SIF_REFID.DefineVersionInfo(SifVersion.SIF20, "SIF_RefId", 2, (ElementDefImpl.FD_ATTRIBUTE)); // (Sif 20 alias)
		InfrastructureDTD.AUTHENTICATION_SIF_REFOBJECT = new ElementDefImpl( AUTHENTICATION, "SIF_RefObject", "SifRefIdType", 3, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_ATTRIBUTE), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		InfrastructureDTD.AUTHENTICATION_SIF_REFOBJECT.DefineVersionInfo(SifVersion.SIF20, "SIF_RefObject", 3, (ElementDefImpl.FD_ATTRIBUTE)); // (Sif 20 alias)
		InfrastructureDTD.AUTHENTICATION_AUTHENTICATIONINFO = new ElementDefImpl( AUTHENTICATION, "AuthenticationInfo", null, 4, SifDtd.INFRASTRUCTURE, "us", 0, SifVersion.SIF15r1, SifVersion.SIF26 );
		AUTHENTICATION_SIF_EXTENDEDELEMENTS = new ElementDefImpl( AUTHENTICATION, "SIF_ExtendedElements", null, 127, SifDtd.GLOBAL, null, (0), SifVersion.SIF15r1, SifVersion.SIF26 );
		AUTHENTICATION_SIF_METADATA = new ElementDefImpl( AUTHENTICATION, "SIF_Metadata", null, 128, SifDtd.DATAMODEL, "us", (0), SifVersion.SIF20, SifVersion.SIF26 );

		// <AuthenticationInfo> fields (4 entries)
		InfrastructureDTD.AUTHENTICATIONINFO_SYSTEM = new ElementDefAlias( AUTHENTICATIONINFO, "System", null, "AuthSystem", 1, SifDtd.INFRASTRUCTURE, "us", 0, SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		InfrastructureDTD.AUTHENTICATIONINFO_USERNAME = new ElementDefImpl( AUTHENTICATIONINFO, "Username", null, 2, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_FIELD), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		InfrastructureDTD.AUTHENTICATIONINFO_DISTINGUISHEDNAME = new ElementDefImpl( AUTHENTICATIONINFO, "DistinguishedName", null, 3, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_FIELD), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
		InfrastructureDTD.AUTHENTICATIONINFO_PASSWORDLIST = new ElementDefImpl( AUTHENTICATIONINFO, "PasswordList", null, 4, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_COLLAPSE), SifVersion.SIF15r1, SifVersion.SIF26 );
		InfrastructureDTD.AUTHENTICATIONINFO_PASSWORDLIST.DefineVersionInfo(SifVersion.SIF20, "PasswordList", 4, 0); // (Sif 20 alias)

		// <System> fields (1 entries)
		InfrastructureDTD.AUTHSYSTEM_TYPE = new ElementDefImpl( AUTHSYSTEM, "Type", null, 1, SifDtd.INFRASTRUCTURE, "us", (ElementDefImpl.FD_ATTRIBUTE), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );

		// <PasswordList> fields (1 entries)
		InfrastructureDTD.PASSWORDLIST_PASSWORD = new ElementDefImpl( PASSWORDLIST, "Password", null, 1, SifDtd.INFRA, null, (ElementDefImpl.FD_REPEATABLE), SifVersion.SIF15r1, SifVersion.SIF26, SifTypeConverters.STRING );
	}

	#region Update SifDtd
	public override void AddElementMappings( IDictionary<String, IElementDef> dictionary )
	{
		dictionary[ "PasswordList" ] = PASSWORDLIST;
		dictionary["PasswordList_Password"] = InfrastructureDTD.PASSWORDLIST_PASSWORD ;
		dictionary[ "AuthenticationInfo" ] = AUTHENTICATIONINFO;
		dictionary["AuthenticationInfo_DistinguishedName"] = InfrastructureDTD.AUTHENTICATIONINFO_DISTINGUISHEDNAME ;
		dictionary["AuthenticationInfo_Password"] = InfrastructureDTD.PASSWORDLIST_PASSWORD ;//Collapsed in 1.5r1
		dictionary["AuthenticationInfo_PasswordList"] = InfrastructureDTD.AUTHENTICATIONINFO_PASSWORDLIST ;
		dictionary["AuthenticationInfo_System"] = InfrastructureDTD.AUTHENTICATIONINFO_SYSTEM ;
		dictionary["AuthenticationInfo_Username"] = InfrastructureDTD.AUTHENTICATIONINFO_USERNAME ;
		dictionary[ "AuthSystem" ] = AUTHSYSTEM;
		dictionary["AuthSystem_Type"] = InfrastructureDTD.AUTHSYSTEM_TYPE ;
		dictionary[ "Authentication" ] = AUTHENTICATION;
		dictionary[ "Authentication_SIF_ExtendedElements" ] = AUTHENTICATION_SIF_EXTENDEDELEMENTS ;
		dictionary[ "Authentication_SIF_Metadata" ] = AUTHENTICATION_SIF_METADATA;
		dictionary["Authentication_AuthenticationInfo"] = InfrastructureDTD.AUTHENTICATION_AUTHENTICATIONINFO ;
		dictionary["Authentication_RefId"] = InfrastructureDTD.AUTHENTICATION_REFID ;
		dictionary["Authentication_SIF_RefId"] = InfrastructureDTD.AUTHENTICATION_SIF_REFID ;//2.0 alias
		dictionary["Authentication_SIF_RefObject"] = InfrastructureDTD.AUTHENTICATION_SIF_REFOBJECT ;//2.0 alias
		dictionary["Authentication_SifRefId"] = InfrastructureDTD.AUTHENTICATION_SIF_REFID ;
		dictionary["Authentication_SifRefIdType"] = InfrastructureDTD.AUTHENTICATION_SIF_REFOBJECT ;
	}
	#endregion
}}
