// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.uk.Common;

namespace OpenADK.Library.uk.Workforce{

/// <summary>A Posts</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class Posts : SifKeyedList<Post>
{
	/// <summary>
	/// Creates an instance of a Posts
	/// </summary>
	public Posts() : base ( WorkforceDTD.POSTS ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="post">The role(s) of the person within this school.</param>
	///
	public Posts( Post post ) : base( WorkforceDTD.POSTS )
	{
		this.SafeAddChild( WorkforceDTD.POSTS_POST, post );
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected Posts( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public  IElementDef[] KeyFields {
		get { return new IElementDef[] { WorkforceDTD.POSTS_POST }; }
	}

	///<summary>Adds the value of the <c>&lt;Post&gt;</c> element.</summary>
	/// <param name="Value">Gets or sets the content value of the &amp;lt;Post&amp;gt; element</param>
	///<remarks>
	/// <para>This form of <c>setPost</c> is provided as a convenience method
	/// that is functionally equivalent to the method <c>AddPost</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void AddPost( EmployeePost Value ) {
		AddChild( WorkforceDTD.POSTS_POST, new Post( Value ) );
	}

}}
