// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;
using OpenADK.Library.us.Gradebook;
using OpenADK.Library.us.Student;

namespace OpenADK.Library.us.Etranscripts{

/// <summary>A TermInfoData</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.5</para>
/// <para>Since: 2.0</para>
/// </remarks>
[Serializable]
public class TermInfoData : SifKeyedElement
{
	/// <summary>
	/// Creates an instance of a TermInfoData
	/// </summary>
	public TermInfoData() : base ( EtranscriptsDTD.TERMINFODATA ){}

	/// <summary>
	/// Constructor that accepts values for all mandatory fields
	/// </summary>
	///<param name="schoolAttendedRefId">Reference to the school of record for the courses being taken (see SchoolAttended).</param>
	///
	public TermInfoData( string schoolAttendedRefId ) : base( EtranscriptsDTD.TERMINFODATA )
	{
		this.SchoolAttendedRefId = schoolAttendedRefId;
	}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected TermInfoData( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets the metadata fields that make up the key of this object
	/// </summary>
	/// <value>
	/// an array of metadata fields that make up the object's key
	/// </value>
	public override IElementDef[] KeyFields {
		get { return new IElementDef[] { EtranscriptsDTD.TERMINFODATA_SCHOOLATTENDEDREFID }; }
	}

	/// <summary>
	/// Gets or sets the value of the <c>SchoolAttendedRefId</c> attribute.
	/// </summary>
	/// <value> The <c>SchoolAttendedRefId</c> attribute of this object.</value>
	/// <remarks>
	/// <para>The SIF specification defines the meaning of this attribute as: "Reference to the school of record for the courses being taken (see SchoolAttended)."</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string SchoolAttendedRefId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( EtranscriptsDTD.TERMINFODATA_SCHOOLATTENDEDREFID ) ;
		}
		set
		{
			SetFieldValue( EtranscriptsDTD.TERMINFODATA_SCHOOLATTENDEDREFID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SchoolYear&gt;</c> element.
	/// </summary>
	/// <value> The <c>SchoolYear</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public int? SchoolYear
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( EtranscriptsDTD.TERMINFODATA_SCHOOLYEAR ) ;
		}
		set
		{
			SetFieldValue( EtranscriptsDTD.TERMINFODATA_SCHOOLYEAR, new SifInt( value ), value );
		}
	}

	///<summary>Sets the value of the <c>&lt;StartDate&gt;</c> element.</summary>
	/// <param name="Value">Gets or sets the content value of the &amp;lt;PartialDateType&amp;gt; element</param>
	///<remarks>
	/// <para>This form of <c>setStartDate</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>StartDate</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void SetStartDate( string Value ) {
		RemoveChild( EtranscriptsDTD.TERMINFODATA_STARTDATE);
		AddChild( EtranscriptsDTD.TERMINFODATA_STARTDATE, new PartialDateType( Value ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;StartDate&gt;</c> element.
	/// </summary>
	/// <value> A PartialDateType </value>
	/// <remarks>
	/// <para>To remove the <c>PartialDateType</c>, set <c>StartDate</c> to <c>null</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public PartialDateType StartDate
	{
		get
		{
			return (PartialDateType)GetChild( EtranscriptsDTD.TERMINFODATA_STARTDATE);
		}
		set
		{
			RemoveChild( EtranscriptsDTD.TERMINFODATA_STARTDATE);
			if( value != null)
			{
				AddChild( EtranscriptsDTD.TERMINFODATA_STARTDATE, value );
			}
		}
	}

	///<summary>Sets the value of the <c>&lt;EndDate&gt;</c> element.</summary>
	/// <param name="Value">Gets or sets the content value of the &amp;lt;PartialDateType&amp;gt; element</param>
	///<remarks>
	/// <para>This form of <c>setEndDate</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>EndDate</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void SetEndDate( string Value ) {
		RemoveChild( EtranscriptsDTD.TERMINFODATA_ENDDATE);
		AddChild( EtranscriptsDTD.TERMINFODATA_ENDDATE, new PartialDateType( Value ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EndDate&gt;</c> element.
	/// </summary>
	/// <value> A PartialDateType </value>
	/// <remarks>
	/// <para>To remove the <c>PartialDateType</c>, set <c>EndDate</c> to <c>null</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public PartialDateType EndDate
	{
		get
		{
			return (PartialDateType)GetChild( EtranscriptsDTD.TERMINFODATA_ENDDATE);
		}
		set
		{
			RemoveChild( EtranscriptsDTD.TERMINFODATA_ENDDATE);
			if( value != null)
			{
				AddChild( EtranscriptsDTD.TERMINFODATA_ENDDATE, value );
			}
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Description&gt;</c> element.
	/// </summary>
	/// <value> The <c>Description</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string Description
	{
		get
		{
			return (string) GetSifSimpleFieldValue( EtranscriptsDTD.TERMINFODATA_DESCRIPTION ) ;
		}
		set
		{
			SetFieldValue( EtranscriptsDTD.TERMINFODATA_DESCRIPTION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;TermCode&gt;</c> element.
	/// </summary>
	/// <value> The <c>TermCode</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string TermCode
	{
		get
		{
			return (string) GetSifSimpleFieldValue( EtranscriptsDTD.TERMINFODATA_TERMCODE ) ;
		}
		set
		{
			SetFieldValue( EtranscriptsDTD.TERMINFODATA_TERMCODE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Track&gt;</c> element.
	/// </summary>
	/// <value> The <c>Track</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public string Track
	{
		get
		{
			return (string) GetSifSimpleFieldValue( EtranscriptsDTD.TERMINFODATA_TRACK ) ;
		}
		set
		{
			SetFieldValue( EtranscriptsDTD.TERMINFODATA_TRACK, new SifString( value ), value );
		}
	}

	///<summary>Sets the value of the <c>&lt;TermSpan&gt;</c> element.</summary>
	/// <param name="Code">Code for session type.</param>
	///<remarks>
	/// <para>This form of <c>setTermSpan</c> is provided as a convenience method
	/// that is functionally equivalent to the <c>TermSpan</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public void SetTermSpan( SessionTypeCode Code ) {
		RemoveChild( EtranscriptsDTD.TERMINFODATA_TERMSPAN);
		AddChild( EtranscriptsDTD.TERMINFODATA_TERMSPAN, new TermSpan( Code ) );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;TermSpan&gt;</c> element.
	/// </summary>
	/// <value> A TermSpan </value>
	/// <remarks>
	/// <para>To remove the <c>TermSpan</c>, set <c>TermSpan</c> to <c>null</c></para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	public TermSpan TermSpan
	{
		get
		{
			return (TermSpan)GetChild( EtranscriptsDTD.TERMINFODATA_TERMSPAN);
		}
		set
		{
			RemoveChild( EtranscriptsDTD.TERMINFODATA_TERMSPAN);
			if( value != null)
			{
				AddChild( EtranscriptsDTD.TERMINFODATA_TERMSPAN, value );
			}
		}
	}

}}
