// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.us.Common
{
	///<summary>
	/// Defines the set of values that can be specified whenever a RelationshipCode
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a RelationshipCode object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	[Serializable]
	public class RelationshipCode : SifEnum
	{
	/// <summary>Mother's significant other ("1775")</summary>
	public static readonly RelationshipCode MOTHERS_SIGNIFICANT_OTHER = new RelationshipCode("1775");

	/// <summary>Niece ("1738")</summary>
	public static readonly RelationshipCode NIECE = new RelationshipCode("1738");

	/// <summary>Fianc\u00E9e ("1763")</summary>
	public static readonly RelationshipCode FIANCEE = new RelationshipCode("1763");

	/// <summary>Sister, natural/adoptive  ("1741")</summary>
	public static readonly RelationshipCode SISTER_NATURAL_ADOPTIVE = new RelationshipCode("1741");

	/// <summary>Probation officer ("1779")</summary>
	public static readonly RelationshipCode PROBATION_OFFICER = new RelationshipCode("1779");

	/// <summary>Grandfather ("1730")</summary>
	public static readonly RelationshipCode GRANDFATHER = new RelationshipCode("1730");

	/// <summary>Great aunt ("1770")</summary>
	public static readonly RelationshipCode GREAT_AUNT = new RelationshipCode("1770");

	/// <summary>Adopted Daughter ("5006")</summary>
	public static readonly RelationshipCode ADOPTED_DAUGHTER = new RelationshipCode("5006");

	/// <summary>Former wife ("1758")</summary>
	public static readonly RelationshipCode FORMER_WIFE = new RelationshipCode("1758");

	/// <summary>Other ("9999")</summary>
	public static readonly RelationshipCode OTHER = new RelationshipCode("9999");

	/// <summary>Daughter-in-law ("1754")</summary>
	public static readonly RelationshipCode DAUGHTER_IN_LAW = new RelationshipCode("1754");

	/// <summary>Minister or priest ("1774")</summary>
	public static readonly RelationshipCode MINISTER_OR_PRIEST = new RelationshipCode("1774");

	/// <summary>Brother, half ("1721")</summary>
	public static readonly RelationshipCode BROTHER_HALF = new RelationshipCode("1721");

	/// <summary>Father-in-law ("1761")</summary>
	public static readonly RelationshipCode FATHER_IN_LAW = new RelationshipCode("1761");

	/// <summary>Stepdaughter ("4987")</summary>
	public static readonly RelationshipCode STEPDAUGHTER = new RelationshipCode("4987");

	/// <summary>Foster parent ("1765")</summary>
	public static readonly RelationshipCode FOSTER_PARENT = new RelationshipCode("1765");

	/// <summary>Fianc\u00E9 ("1762")</summary>
	public static readonly RelationshipCode FIANCE = new RelationshipCode("1762");

	/// <summary>Great uncle ("1771")</summary>
	public static readonly RelationshipCode GREAT_UNCLE = new RelationshipCode("1771");

	/// <summary>Brother, natural/adoptive  ("1722")</summary>
	public static readonly RelationshipCode BROTHER_NATURAL_ADOPTIVE = new RelationshipCode("1722");

	/// <summary>Father, foster ("1726")</summary>
	public static readonly RelationshipCode FATHER_FOSTER = new RelationshipCode("1726");

	/// <summary>Brother-in-law ("1752")</summary>
	public static readonly RelationshipCode BROTHER_IN_LAW = new RelationshipCode("1752");

	/// <summary>Brother, natural/adoptive ("1722")</summary>
	public static readonly RelationshipCode BROTHER_NATURAL_OR_ADOPTIVE = new RelationshipCode("1722");

	/// <summary>Mother, natural/adoptive ("1735")</summary>
	public static readonly RelationshipCode MOTHER_NATURAL_OR_ADOPTIVE = new RelationshipCode("1735");

	/// <summary>Life partner of parent ("1773")</summary>
	public static readonly RelationshipCode LIFE_PARTNER_OF_PARENT = new RelationshipCode("1773");

	/// <summary>Stepson ("1782")</summary>
	public static readonly RelationshipCode STEPSON = new RelationshipCode("1782");

	/// <summary>Sister, half ("1740")</summary>
	public static readonly RelationshipCode SISTER_HALF = new RelationshipCode("1740");

	/// <summary>Mother, natural/adoptive  ("1735")</summary>
	public static readonly RelationshipCode MOTHER_NATURAL_ADOPTIVE = new RelationshipCode("1735");

	/// <summary>Father's significant other ("1760")</summary>
	public static readonly RelationshipCode FATHERS_SIGNIFICANT_OTHER = new RelationshipCode("1760");

	/// <summary>Partner ("1777")</summary>
	public static readonly RelationshipCode PARTNER = new RelationshipCode("1777");

	/// <summary>Father, natural/adoptive  ("1727")</summary>
	public static readonly RelationshipCode FATHER_NATURAL_ADOPTIVE = new RelationshipCode("1727");

	/// <summary>Daughter ("1725")</summary>
	public static readonly RelationshipCode DAUGHTER = new RelationshipCode("1725");

	/// <summary>Dependent ("1755")</summary>
	public static readonly RelationshipCode DEPENDENT = new RelationshipCode("1755");

	/// <summary>Advisor ("1750")</summary>
	public static readonly RelationshipCode ADVISOR = new RelationshipCode("1750");

	/// <summary>Adopted son ("1747")</summary>
	public static readonly RelationshipCode ADOPTED_SON = new RelationshipCode("1747");

	/// <summary>Nephew ("1737")</summary>
	public static readonly RelationshipCode NEPHEW = new RelationshipCode("1737");

	/// <summary>Agency representative ("1751")</summary>
	public static readonly RelationshipCode AGENCY_REPRESENTATIVE = new RelationshipCode("1751");

	/// <summary>Uncle ("1744")</summary>
	public static readonly RelationshipCode UNCLE = new RelationshipCode("1744");

	/// <summary>Friend ("1729")</summary>
	public static readonly RelationshipCode FRIEND = new RelationshipCode("1729");

	/// <summary>Aunt ("1720")</summary>
	public static readonly RelationshipCode AUNT = new RelationshipCode("1720");

	/// <summary>Partner of parent ("1778")</summary>
	public static readonly RelationshipCode PARTNER_OF_PARENT = new RelationshipCode("1778");

	/// <summary>Life partner ("1772")</summary>
	public static readonly RelationshipCode LIFE_PARTNER = new RelationshipCode("1772");

	/// <summary>Cousin ("1724")</summary>
	public static readonly RelationshipCode COUSIN = new RelationshipCode("1724");

	/// <summary>Sister, natural/adoptive ("1741")</summary>
	public static readonly RelationshipCode SISTER_NATURAL_OR_ADOPTIVE = new RelationshipCode("1741");

	/// <summary>Father, natural/adoptive ("1727")</summary>
	public static readonly RelationshipCode FATHER_NATURAL_OR_ADOPTIVE = new RelationshipCode("1727");

	/// <summary>Son-in-law ("1781")</summary>
	public static readonly RelationshipCode SON_IN_LAW = new RelationshipCode("1781");

	/// <summary>Mother-in-law ("1776")</summary>
	public static readonly RelationshipCode MOTHER_IN_LAW = new RelationshipCode("1776");

	/// <summary>Sister-in-law ("1780")</summary>
	public static readonly RelationshipCode SISTER_IN_LAW = new RelationshipCode("1780");

	/// <summary>Former husband ("1757")</summary>
	public static readonly RelationshipCode FORMER_HUSBAND = new RelationshipCode("1757");

	/// <summary>Grandson ("1769")</summary>
	public static readonly RelationshipCode GRANDSON = new RelationshipCode("1769");

	/// <summary>Brother, step ("1723")</summary>
	public static readonly RelationshipCode BROTHER_STEP = new RelationshipCode("1723");

	/// <summary>Wife ("1746")</summary>
	public static readonly RelationshipCode WIFE = new RelationshipCode("1746");

	/// <summary>None ("9998")</summary>
	public static readonly RelationshipCode NONE = new RelationshipCode("9998");

	/// <summary>Mother, foster ("1734")</summary>
	public static readonly RelationshipCode MOTHER_FOSTER = new RelationshipCode("1734");

	/// <summary>Ward ("1745")</summary>
	public static readonly RelationshipCode WARD = new RelationshipCode("1745");

	/// <summary>Husband ("1732")</summary>
	public static readonly RelationshipCode HUSBAND = new RelationshipCode("1732");

	/// <summary>Significant other ("1739")</summary>
	public static readonly RelationshipCode SIGNIFICANT_OTHER = new RelationshipCode("1739");

	/// <summary>Son ("1743")</summary>
	public static readonly RelationshipCode SON = new RelationshipCode("1743");

	/// <summary>Sister, step ("1742")</summary>
	public static readonly RelationshipCode SISTER_STEP = new RelationshipCode("1742");

	/// <summary>Employer ("1552")</summary>
	public static readonly RelationshipCode EMPLOYER = new RelationshipCode("1552");

	/// <summary>Court appointed guardian ("1753")</summary>
	public static readonly RelationshipCode COURT_APPOINTED_GUARDIAN = new RelationshipCode("1753");

	/// <summary>Foster son ("1766")</summary>
	public static readonly RelationshipCode FOSTER_SON = new RelationshipCode("1766");

	/// <summary>Granddaughter ("1767")</summary>
	public static readonly RelationshipCode GRANDDAUGHTER = new RelationshipCode("1767");

	/// <summary>Grandmother ("1731")</summary>
	public static readonly RelationshipCode GRANDMOTHER = new RelationshipCode("1731");

	/// <summary>Adoptive parents ("1749")</summary>
	public static readonly RelationshipCode ADOPTIVE_PARENTS = new RelationshipCode("1749");

	/// <summary>Family member ("1759")</summary>
	public static readonly RelationshipCode FAMILY_MEMBER = new RelationshipCode("1759");

	/// <summary>Foster daughter ("1764")</summary>
	public static readonly RelationshipCode FOSTER_DAUGHTER = new RelationshipCode("1764");

	/// <summary>Mother, step ("1736")</summary>
	public static readonly RelationshipCode MOTHER_STEP = new RelationshipCode("1736");

	/// <summary>Father, step ("1728")</summary>
	public static readonly RelationshipCode FATHER_STEP = new RelationshipCode("1728");

	///<summary>Wrap an arbitrary string value in a RelationshipCode object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static RelationshipCode Wrap( String wrappedValue ) {
		return new RelationshipCode( wrappedValue );
	}

	private RelationshipCode( string enumDefValue ) : base( enumDefValue ) {}
	}
}
