// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.us.Common
{
	///<summary>
	/// Defines the set of values that can be specified whenever a StatePrCode
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a StatePrCode object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.6</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	[Serializable]
	public class StatePrCode : SifEnum
	{
	/// <summary>Arkansas ("AR")</summary>
	public static readonly StatePrCode AR = new StatePrCode("AR");

	/// <summary>Armed Forces Pacific ("AP")</summary>
	public static readonly StatePrCode AP = new StatePrCode("AP");

	/// <summary>Guam ("GU")</summary>
	public static readonly StatePrCode GU = new StatePrCode("GU");

	/// <summary>Alabama ("AL")</summary>
	public static readonly StatePrCode AL = new StatePrCode("AL");

	/// <summary>Alaska ("AK")</summary>
	public static readonly StatePrCode AK = new StatePrCode("AK");

	/// <summary>Montana ("MT")</summary>
	public static readonly StatePrCode MT = new StatePrCode("MT");

	/// <summary>Mississippi ("MS")</summary>
	public static readonly StatePrCode MS = new StatePrCode("MS");

	/// <summary>Armed Forces Africa, Canada, Europe and Middle East ("AE")</summary>
	public static readonly StatePrCode AE = new StatePrCode("AE");

	/// <summary>Missouri ("MO")</summary>
	public static readonly StatePrCode MO = new StatePrCode("MO");

	/// <summary>Minnesota ("MN")</summary>
	public static readonly StatePrCode MN = new StatePrCode("MN");

	/// <summary>Alberta ("AB")</summary>
	public static readonly StatePrCode AB = new StatePrCode("AB");

	/// <summary>Armed Forces Americas (except Canada) ("AA")</summary>
	public static readonly StatePrCode AA = new StatePrCode("AA");

	/// <summary>Yukon ("YT")</summary>
	public static readonly StatePrCode YT = new StatePrCode("YT");

	/// <summary>Michigan ("MI")</summary>
	public static readonly StatePrCode MI = new StatePrCode("MI");

	/// <summary>Georgia ("GA")</summary>
	public static readonly StatePrCode GA = new StatePrCode("GA");

	/// <summary>Saskatchewan ("SK")</summary>
	public static readonly StatePrCode SK = new StatePrCode("SK");

	/// <summary>Maine ("ME")</summary>
	public static readonly StatePrCode ME = new StatePrCode("ME");

	/// <summary>Maryland ("MD")</summary>
	public static readonly StatePrCode MD = new StatePrCode("MD");

	/// <summary>Manitoba ("MB")</summary>
	public static readonly StatePrCode MB = new StatePrCode("MB");

	/// <summary>Massachusetts ("MA")</summary>
	public static readonly StatePrCode MA = new StatePrCode("MA");

	/// <summary>South Dakota ("SD")</summary>
	public static readonly StatePrCode SD = new StatePrCode("SD");

	/// <summary>South Carolina ("SC")</summary>
	public static readonly StatePrCode SC = new StatePrCode("SC");

	/// <summary>Florida ("FL")</summary>
	public static readonly StatePrCode FL = new StatePrCode("FL");

	/// <summary>Rhode Island ("RI")</summary>
	public static readonly StatePrCode RI = new StatePrCode("RI");

	/// <summary>Louisiana ("LA")</summary>
	public static readonly StatePrCode LA = new StatePrCode("LA");

	/// <summary>Kentucky ("KY")</summary>
	public static readonly StatePrCode KY = new StatePrCode("KY");

	/// <summary>Kansas ("KS")</summary>
	public static readonly StatePrCode KS = new StatePrCode("KS");

	/// <summary>Wyoming ("WY")</summary>
	public static readonly StatePrCode WY = new StatePrCode("WY");

	/// <summary>West Virginia ("WV")</summary>
	public static readonly StatePrCode WV = new StatePrCode("WV");

	/// <summary>Wisconsin ("WI")</summary>
	public static readonly StatePrCode WI = new StatePrCode("WI");

	/// <summary>Quebec ("QC")</summary>
	public static readonly StatePrCode QC = new StatePrCode("QC");

	/// <summary>Washington ("WA")</summary>
	public static readonly StatePrCode WA = new StatePrCode("WA");

	/// <summary>Puerto Rico ("PR")</summary>
	public static readonly StatePrCode PR = new StatePrCode("PR");

	/// <summary>Quebec ("PQ")</summary>
	public static readonly StatePrCode PQ = new StatePrCode("PQ");

	/// <summary>Delaware ("DE")</summary>
	public static readonly StatePrCode DE = new StatePrCode("DE");

	/// <summary>Vermont ("VT")</summary>
	public static readonly StatePrCode VT = new StatePrCode("VT");

	/// <summary>District of Columbia ("DC")</summary>
	public static readonly StatePrCode DC = new StatePrCode("DC");

	/// <summary>Canal Zone ("CZ")</summary>
	public static readonly StatePrCode CZ = new StatePrCode("CZ");

	/// <summary>Prince Edward Island ("PE")</summary>
	public static readonly StatePrCode PE = new StatePrCode("PE");

	/// <summary>Virgin Islands ("VI")</summary>
	public static readonly StatePrCode VI = new StatePrCode("VI");

	/// <summary>Pennsylvania ("PA")</summary>
	public static readonly StatePrCode PA = new StatePrCode("PA");

	/// <summary>Connecticut ("CT")</summary>
	public static readonly StatePrCode CT = new StatePrCode("CT");

	/// <summary>Virginia ("VA")</summary>
	public static readonly StatePrCode VA = new StatePrCode("VA");

	/// <summary>Colorado ("CO")</summary>
	public static readonly StatePrCode CO = new StatePrCode("CO");

	/// <summary>Indiana ("IN")</summary>
	public static readonly StatePrCode IN = new StatePrCode("IN");

	/// <summary>Oregon ("OR")</summary>
	public static readonly StatePrCode OR = new StatePrCode("OR");

	/// <summary>Illinois ("IL")</summary>
	public static readonly StatePrCode IL = new StatePrCode("IL");

	/// <summary>Utah ("UT")</summary>
	public static readonly StatePrCode UT = new StatePrCode("UT");

	/// <summary>Ontario ("ON")</summary>
	public static readonly StatePrCode ON = new StatePrCode("ON");

	/// <summary>California ("CA")</summary>
	public static readonly StatePrCode CA = new StatePrCode("CA");

	/// <summary>Oklahoma ("OK")</summary>
	public static readonly StatePrCode OK = new StatePrCode("OK");

	/// <summary>Idaho ("ID")</summary>
	public static readonly StatePrCode ID = new StatePrCode("ID");

	/// <summary>Ohio ("OH")</summary>
	public static readonly StatePrCode OH = new StatePrCode("OH");

	/// <summary>Iowa ("IA")</summary>
	public static readonly StatePrCode IA = new StatePrCode("IA");

	/// <summary>New York ("NY")</summary>
	public static readonly StatePrCode NY = new StatePrCode("NY");

	/// <summary>Nevada ("NV")</summary>
	public static readonly StatePrCode NV = new StatePrCode("NV");

	/// <summary>Nunavut ("NU")</summary>
	public static readonly StatePrCode NU = new StatePrCode("NU");

	/// <summary>North West Territories ("NT")</summary>
	public static readonly StatePrCode NT = new StatePrCode("NT");

	/// <summary>Nova Scotia ("NS")</summary>
	public static readonly StatePrCode NS = new StatePrCode("NS");

	/// <summary>Texas ("TX")</summary>
	public static readonly StatePrCode TX = new StatePrCode("TX");

	/// <summary>Hawaii ("HI")</summary>
	public static readonly StatePrCode HI = new StatePrCode("HI");

	/// <summary>British Columbia ("BC")</summary>
	public static readonly StatePrCode BC = new StatePrCode("BC");

	/// <summary>New Mexico ("NM")</summary>
	public static readonly StatePrCode NM = new StatePrCode("NM");

	/// <summary>Newfoundland ("NL")</summary>
	public static readonly StatePrCode NL = new StatePrCode("NL");

	/// <summary>New Jersey ("NJ")</summary>
	public static readonly StatePrCode NJ = new StatePrCode("NJ");

	/// <summary>Tennessee ("TN")</summary>
	public static readonly StatePrCode TN = new StatePrCode("TN");

	/// <summary>New Hampshire ("NH")</summary>
	public static readonly StatePrCode NH = new StatePrCode("NH");

	/// <summary>Newfoundland ("NF")</summary>
	public static readonly StatePrCode NF = new StatePrCode("NF");

	/// <summary>Arizona ("AZ")</summary>
	public static readonly StatePrCode AZ = new StatePrCode("AZ");

	/// <summary>Nebraska ("NE")</summary>
	public static readonly StatePrCode NE = new StatePrCode("NE");

	/// <summary>North Dakota ("ND")</summary>
	public static readonly StatePrCode ND = new StatePrCode("ND");

	/// <summary>North Carolina ("NC")</summary>
	public static readonly StatePrCode NC = new StatePrCode("NC");

	/// <summary>New Brunswick ("NB")</summary>
	public static readonly StatePrCode NB = new StatePrCode("NB");

	///<summary>Wrap an arbitrary string value in a StatePrCode object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static StatePrCode Wrap( String wrappedValue ) {
		return new StatePrCode( wrappedValue );
	}

	private StatePrCode( string enumDefValue ) : base( enumDefValue ) {}
	}
}
