// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.us.Common
{
	///<summary>
	/// Defines the set of values that can be specified whenever a Topics
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a Topics object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 2.0</para>
	/// </remarks>
	[Serializable]
	public class Topics : SifEnum
	{
	/// <summary>AggregateStatisticInfo ("AggregateStatisticInfo")</summary>
	public static readonly Topics AGGREGATESTATISTICINFO = new Topics("AggregateStatisticInfo");

	/// <summary>ProfessionalDevelopmentRegistration ("ProfessionalDevelopmentRegistration")</summary>
	public static readonly Topics PROFESSIONALDEVELOPMENTREGISTRATION = new Topics("ProfessionalDevelopmentRegistration");

	/// <summary>StudentScoreSet ("StudentScoreSet")</summary>
	public static readonly Topics STUDENTSCORESET = new Topics("StudentScoreSet");

	/// <summary>RoomType ("RoomType")</summary>
	public static readonly Topics ROOMTYPE = new Topics("RoomType");

	/// <summary>AttendanceCodeInfo ("AttendanceCodeInfo")</summary>
	public static readonly Topics ATTENDANCECODEINFO = new Topics("AttendanceCodeInfo");

	/// <summary>FinancialBudget ("FinancialBudget")</summary>
	public static readonly Topics FINANCIALBUDGET = new Topics("FinancialBudget");

	/// <summary>EmployeePicture ("EmployeePicture")</summary>
	public static readonly Topics EMPLOYEEPICTURE = new Topics("EmployeePicture");

	/// <summary>StudentSectionMarks ("StudentSectionMarks")</summary>
	public static readonly Topics STUDENTSECTIONMARKS = new Topics("StudentSectionMarks");

	/// <summary>EmploymentRecord ("EmploymentRecord")</summary>
	public static readonly Topics EMPLOYMENTRECORD = new Topics("EmploymentRecord");

	/// <summary>AssessmentRegistration ("AssessmentRegistration")</summary>
	public static readonly Topics ASSESSMENTREGISTRATION = new Topics("AssessmentRegistration");

	/// <summary>StudentAcademicRecord ("StudentAcademicRecord")</summary>
	public static readonly Topics STUDENTACADEMICRECORD = new Topics("StudentAcademicRecord");

	/// <summary>FoodserviceMenuPlan ("FoodserviceMenuPlan")</summary>
	public static readonly Topics FOODSERVICEMENUPLAN = new Topics("FoodserviceMenuPlan");

	/// <summary>StaffMeal ("StaffMeal")</summary>
	public static readonly Topics STAFFMEAL = new Topics("StaffMeal");

	/// <summary>StudentParticipation ("StudentParticipation")</summary>
	public static readonly Topics STUDENTPARTICIPATION = new Topics("StudentParticipation");

	/// <summary>StudentDemographicRecord ("StudentDemographicRecord")</summary>
	public static readonly Topics STUDENTDEMOGRAPHICRECORD = new Topics("StudentDemographicRecord");

	/// <summary>SectionInfo ("SectionInfo")</summary>
	public static readonly Topics SECTIONINFO = new Topics("SectionInfo");

	/// <summary>TimeWorked ("TimeWorked")</summary>
	public static readonly Topics TIMEWORKED = new Topics("TimeWorked");

	/// <summary>AssessmentSubTest ("AssessmentSubTest")</summary>
	public static readonly Topics ASSESSMENTSUBTEST = new Topics("AssessmentSubTest");

	/// <summary>Lesson ("Lesson")</summary>
	public static readonly Topics LESSON = new Topics("Lesson");

	/// <summary>Assignment ("Assignment")</summary>
	public static readonly Topics ASSIGNMENT = new Topics("Assignment");

	/// <summary>BusRouteInfo ("BusRouteInfo")</summary>
	public static readonly Topics BUSROUTEINFO = new Topics("BusRouteInfo");

	/// <summary>FoodserviceStaffEnrollmentCount ("FoodserviceStaffEnrollmentCount")</summary>
	public static readonly Topics FOODSERVICESTAFFENROLLMENTCOUNT = new Topics("FoodserviceStaffEnrollmentCount");

	/// <summary>StudentLEARelationship ("StudentLEARelationship")</summary>
	public static readonly Topics STUDENTLEARELATIONSHIP = new Topics("StudentLEARelationship");

	/// <summary>ActivityProvider ("ActivityProvider")</summary>
	public static readonly Topics ACTIVITYPROVIDER = new Topics("ActivityProvider");

	/// <summary>LearningStandardItem ("LearningStandardItem")</summary>
	public static readonly Topics LEARNINGSTANDARDITEM = new Topics("LearningStandardItem");

	/// <summary>SIF_ReportObject ("SIF_ReportObject")</summary>
	public static readonly Topics SIF_REPORTOBJECT = new Topics("SIF_ReportObject");

	/// <summary>BusEquipment ("BusEquipment")</summary>
	public static readonly Topics BUSEQUIPMENT = new Topics("BusEquipment");

	/// <summary>Authentication ("Authentication")</summary>
	public static readonly Topics AUTHENTICATION = new Topics("Authentication");

	/// <summary>BellSchedule ("BellSchedule")</summary>
	public static readonly Topics BELLSCHEDULE = new Topics("BellSchedule");

	/// <summary>CalendarSummary ("CalendarSummary")</summary>
	public static readonly Topics CALENDARSUMMARY = new Topics("CalendarSummary");

	/// <summary>EmployeeContract ("EmployeeContract")</summary>
	public static readonly Topics EMPLOYEECONTRACT = new Topics("EmployeeContract");

	/// <summary>Purchasing ("Purchasing")</summary>
	public static readonly Topics PURCHASING = new Topics("Purchasing");

	/// <summary>AssessmentForm ("AssessmentForm")</summary>
	public static readonly Topics ASSESSMENTFORM = new Topics("AssessmentForm");

	/// <summary>OfficialStudentPeriodAttendance ("OfficialStudentPeriodAttendance")</summary>
	public static readonly Topics OFFICIALSTUDENTPERIODATTENDANCE = new Topics("OfficialStudentPeriodAttendance");

	/// <summary>CurriculumStructure ("CurriculumStructure")</summary>
	public static readonly Topics CURRICULUMSTRUCTURE = new Topics("CurriculumStructure");

	/// <summary>ProfessionalDevelopmentActivities ("ProfessionalDevelopmentActivities")</summary>
	public static readonly Topics PROFESSIONALDEVELOPMENTACTIVITIES = new Topics("ProfessionalDevelopmentActivities");

	/// <summary>AssessmentItem ("AssessmentItem")</summary>
	public static readonly Topics ASSESSMENTITEM = new Topics("AssessmentItem");

	/// <summary>StudentContactRelationship ("StudentContactRelationship")</summary>
	public static readonly Topics STUDENTCONTACTRELATIONSHIP = new Topics("StudentContactRelationship");

	/// <summary>SchoolCourseInfo ("SchoolCourseInfo")</summary>
	public static readonly Topics SCHOOLCOURSEINFO = new Topics("SchoolCourseInfo");

	/// <summary>ProfDevActivities ("ProfDevActivities")</summary>
	public static readonly Topics PROFDEVACTIVITIES = new Topics("ProfDevActivities");

	/// <summary>SIF_LogEntry ("SIF_LogEntry")</summary>
	public static readonly Topics SIF_LOGENTRY = new Topics("SIF_LogEntry");

	/// <summary>StudentSchoolEnrollment ("StudentSchoolEnrollment")</summary>
	public static readonly Topics STUDENTSCHOOLENROLLMENT = new Topics("StudentSchoolEnrollment");

	/// <summary>AssessmentPackage ("AssessmentPackage")</summary>
	public static readonly Topics ASSESSMENTPACKAGE = new Topics("AssessmentPackage");

	/// <summary>FoodserviceItemUnit ("FoodserviceItemUnit")</summary>
	public static readonly Topics FOODSERVICEITEMUNIT = new Topics("FoodserviceItemUnit");

	/// <summary>SEAInfo ("SEAInfo")</summary>
	public static readonly Topics SEAINFO = new Topics("SEAInfo");

	/// <summary>FinancialIncomeStatement ("FinancialIncomeStatement")</summary>
	public static readonly Topics FINANCIALINCOMESTATEMENT = new Topics("FinancialIncomeStatement");

	/// <summary>ContentCatalog ("ContentCatalog")</summary>
	public static readonly Topics CONTENTCATALOG = new Topics("ContentCatalog");

	/// <summary>StudentAttendanceSummary ("StudentAttendanceSummary")</summary>
	public static readonly Topics STUDENTATTENDANCESUMMARY = new Topics("StudentAttendanceSummary");

	/// <summary>StudentSnapshot ("StudentSnapshot")</summary>
	public static readonly Topics STUDENTSNAPSHOT = new Topics("StudentSnapshot");

	/// <summary>FoodserviceMealPrices ("FoodserviceMealPrices")</summary>
	public static readonly Topics FOODSERVICEMEALPRICES = new Topics("FoodserviceMealPrices");

	/// <summary>StudentDailyAttendance ("StudentDailyAttendance")</summary>
	public static readonly Topics STUDENTDAILYATTENDANCE = new Topics("StudentDailyAttendance");

	/// <summary>StudentResponseSet ("StudentResponseSet")</summary>
	public static readonly Topics STUDENTRESPONSESET = new Topics("StudentResponseSet");

	/// <summary>FinancialTransaction ("FinancialTransaction")</summary>
	public static readonly Topics FINANCIALTRANSACTION = new Topics("FinancialTransaction");

	/// <summary>StudentPlacement ("StudentPlacement")</summary>
	public static readonly Topics STUDENTPLACEMENT = new Topics("StudentPlacement");

	/// <summary>StudentSpecialEducationRecord ("StudentSpecialEducationRecord")</summary>
	public static readonly Topics STUDENTSPECIALEDUCATIONRECORD = new Topics("StudentSpecialEducationRecord");

	/// <summary>SchoolInfo ("SchoolInfo")</summary>
	public static readonly Topics SCHOOLINFO = new Topics("SchoolInfo");

	/// <summary>FoodserviceItemSales ("FoodserviceItemSales")</summary>
	public static readonly Topics FOODSERVICEITEMSALES = new Topics("FoodserviceItemSales");

	/// <summary>GradingAssignment ("GradingAssignment")</summary>
	public static readonly Topics GRADINGASSIGNMENT = new Topics("GradingAssignment");

	/// <summary>EmployeeRecertification ("EmployeeRecertification")</summary>
	public static readonly Topics EMPLOYEERECERTIFICATION = new Topics("EmployeeRecertification");

	/// <summary>FoodserviceTransactionPayMethod ("FoodserviceTransactionPayMethod")</summary>
	public static readonly Topics FOODSERVICETRANSACTIONPAYMETHOD = new Topics("FoodserviceTransactionPayMethod");

	/// <summary>StudentTransportInfo ("StudentTransportInfo")</summary>
	public static readonly Topics STUDENTTRANSPORTINFO = new Topics("StudentTransportInfo");

	/// <summary>StudentLocator ("StudentLocator")</summary>
	public static readonly Topics STUDENTLOCATOR = new Topics("StudentLocator");

	/// <summary>LearningResource ("LearningResource")</summary>
	public static readonly Topics LEARNINGRESOURCE = new Topics("LearningResource");

	/// <summary>MarkValueInfo ("MarkValueInfo")</summary>
	public static readonly Topics MARKVALUEINFO = new Topics("MarkValueInfo");

	/// <summary>DisciplineIncident ("DisciplineIncident")</summary>
	public static readonly Topics DISCIPLINEINCIDENT = new Topics("DisciplineIncident");

	/// <summary>FoodserviceSales ("FoodserviceSales")</summary>
	public static readonly Topics FOODSERVICESALES = new Topics("FoodserviceSales");

	/// <summary>StudentGrade ("StudentGrade")</summary>
	public static readonly Topics STUDENTGRADE = new Topics("StudentGrade");

	/// <summary>ReportAuthorityInfo ("ReportAuthorityInfo")</summary>
	public static readonly Topics REPORTAUTHORITYINFO = new Topics("ReportAuthorityInfo");

	/// <summary>FinancialClass ("FinancialClass")</summary>
	public static readonly Topics FINANCIALCLASS = new Topics("FinancialClass");

	/// <summary>StudentParameters ("StudentParameters")</summary>
	public static readonly Topics STUDENTPARAMETERS = new Topics("StudentParameters");

	/// <summary>StudentRecordPackage ("StudentRecordPackage")</summary>
	public static readonly Topics STUDENTRECORDPACKAGE = new Topics("StudentRecordPackage");

	/// <summary>BusInfo ("BusInfo")</summary>
	public static readonly Topics BUSINFO = new Topics("BusInfo");

	/// <summary>ProfessionalDevelopmentProgram ("ProfessionalDevelopmentProgram")</summary>
	public static readonly Topics PROFESSIONALDEVELOPMENTPROGRAM = new Topics("ProfessionalDevelopmentProgram");

	/// <summary>EmployeeCredential ("EmployeeCredential")</summary>
	public static readonly Topics EMPLOYEECREDENTIAL = new Topics("EmployeeCredential");

	/// <summary>StaffParameters ("StaffParameters")</summary>
	public static readonly Topics STAFFPARAMETERS = new Topics("StaffParameters");

	/// <summary>ReportManifest ("ReportManifest")</summary>
	public static readonly Topics REPORTMANIFEST = new Topics("ReportManifest");

	/// <summary>AssessmentAdministration ("AssessmentAdministration")</summary>
	public static readonly Topics ASSESSMENTADMINISTRATION = new Topics("AssessmentAdministration");

	/// <summary>FinancialAccountAccountingPeriodLocationInfo ("FinancialAccountAccountingPeriodLocationInfo")</summary>
	public static readonly Topics FINANCIALACCOUNTACCOUNTINGPERIODLOCATIONINFO = new Topics("FinancialAccountAccountingPeriodLocationInfo");

	/// <summary>BusStopInfo ("BusStopInfo")</summary>
	public static readonly Topics BUSSTOPINFO = new Topics("BusStopInfo");

	/// <summary>EmployeeCredit ("EmployeeCredit")</summary>
	public static readonly Topics EMPLOYEECREDIT = new Topics("EmployeeCredit");

	/// <summary>GradingCategory ("GradingCategory")</summary>
	public static readonly Topics GRADINGCATEGORY = new Topics("GradingCategory");

	/// <summary>FoodserviceTransaction ("FoodserviceTransaction")</summary>
	public static readonly Topics FOODSERVICETRANSACTION = new Topics("FoodserviceTransaction");

	/// <summary>FoodserviceReimbursementRates ("FoodserviceReimbursementRates")</summary>
	public static readonly Topics FOODSERVICEREIMBURSEMENTRATES = new Topics("FoodserviceReimbursementRates");

	/// <summary>FoodserviceMilkSales ("FoodserviceMilkSales")</summary>
	public static readonly Topics FOODSERVICEMILKSALES = new Topics("FoodserviceMilkSales");

	/// <summary>W4 ("W4")</summary>
	public static readonly Topics W4 = new Topics("W4");

	/// <summary>Activity ("Activity")</summary>
	public static readonly Topics ACTIVITY = new Topics("Activity");

	/// <summary>AggregateCharacteristicInfo ("AggregateCharacteristicInfo")</summary>
	public static readonly Topics AGGREGATECHARACTERISTICINFO = new Topics("AggregateCharacteristicInfo");

	/// <summary>GradingAssignmentScore ("GradingAssignmentScore")</summary>
	public static readonly Topics GRADINGASSIGNMENTSCORE = new Topics("GradingAssignmentScore");

	/// <summary>LEAInfo ("LEAInfo")</summary>
	public static readonly Topics LEAINFO = new Topics("LEAInfo");

	/// <summary>StudentContactPersonal ("StudentContactPersonal")</summary>
	public static readonly Topics STUDENTCONTACTPERSONAL = new Topics("StudentContactPersonal");

	/// <summary>LibraryPatronStatus ("LibraryPatronStatus")</summary>
	public static readonly Topics LIBRARYPATRONSTATUS = new Topics("LibraryPatronStatus");

	/// <summary>StudentRecordExchange ("StudentRecordExchange")</summary>
	public static readonly Topics STUDENTRECORDEXCHANGE = new Topics("StudentRecordExchange");

	/// <summary>StudentMeal ("StudentMeal")</summary>
	public static readonly Topics STUDENTMEAL = new Topics("StudentMeal");

	/// <summary>RoomInfo ("RoomInfo")</summary>
	public static readonly Topics ROOMINFO = new Topics("RoomInfo");

	/// <summary>VendorInfo ("VendorInfo")</summary>
	public static readonly Topics VENDORINFO = new Topics("VendorInfo");

	/// <summary>EmployeeAssignment ("EmployeeAssignment")</summary>
	public static readonly Topics EMPLOYEEASSIGNMENT = new Topics("EmployeeAssignment");

	/// <summary>FoodserviceItemPortion ("FoodserviceItemPortion")</summary>
	public static readonly Topics FOODSERVICEITEMPORTION = new Topics("FoodserviceItemPortion");

	/// <summary>MarkInfo ("MarkInfo")</summary>
	public static readonly Topics MARKINFO = new Topics("MarkInfo");

	/// <summary>BusRouteDetail ("BusRouteDetail")</summary>
	public static readonly Topics BUSROUTEDETAIL = new Topics("BusRouteDetail");

	/// <summary>FoodserviceItem ("FoodserviceItem")</summary>
	public static readonly Topics FOODSERVICEITEM = new Topics("FoodserviceItem");

	/// <summary>FoodserviceStaffMealCounts ("FoodserviceStaffMealCounts")</summary>
	public static readonly Topics FOODSERVICESTAFFMEALCOUNTS = new Topics("FoodserviceStaffMealCounts");

	/// <summary>StudentPersonal ("StudentPersonal")</summary>
	public static readonly Topics STUDENTPERSONAL = new Topics("StudentPersonal");

	/// <summary>LocationInfo ("LocationInfo")</summary>
	public static readonly Topics LOCATIONINFO = new Topics("LocationInfo");

	/// <summary>StudentActivityInfo ("StudentActivityInfo")</summary>
	public static readonly Topics STUDENTACTIVITYINFO = new Topics("StudentActivityInfo");

	/// <summary>ItemCharacteristics ("ItemCharacteristics")</summary>
	public static readonly Topics ITEMCHARACTERISTICS = new Topics("ItemCharacteristics");

	/// <summary>FinancialAnnual ("FinancialAnnual")</summary>
	public static readonly Topics FINANCIALANNUAL = new Topics("FinancialAnnual");

	/// <summary>Assessment ("Assessment")</summary>
	public static readonly Topics ASSESSMENT = new Topics("Assessment");

	/// <summary>StaffPersonal ("StaffPersonal")</summary>
	public static readonly Topics STAFFPERSONAL = new Topics("StaffPersonal");

	/// <summary>StudentActivityParticipation ("StudentActivityParticipation")</summary>
	public static readonly Topics STUDENTACTIVITYPARTICIPATION = new Topics("StudentActivityParticipation");

	/// <summary>StudentSpecialEducationSummary ("StudentSpecialEducationSummary")</summary>
	public static readonly Topics STUDENTSPECIALEDUCATIONSUMMARY = new Topics("StudentSpecialEducationSummary");

	/// <summary>AggregateStatisticFact ("AggregateStatisticFact")</summary>
	public static readonly Topics AGGREGATESTATISTICFACT = new Topics("AggregateStatisticFact");

	/// <summary>SectionMarkInfo ("SectionMarkInfo")</summary>
	public static readonly Topics SECTIONMARKINFO = new Topics("SectionMarkInfo");

	/// <summary>StudentPicture ("StudentPicture")</summary>
	public static readonly Topics STUDENTPICTURE = new Topics("StudentPicture");

	/// <summary>FoodserviceTransactionDetails ("FoodserviceTransactionDetails")</summary>
	public static readonly Topics FOODSERVICETRANSACTIONDETAILS = new Topics("FoodserviceTransactionDetails");

	/// <summary>SIF_AgentACL ("SIF_AgentACL")</summary>
	public static readonly Topics SIF_AGENTACL = new Topics("SIF_AgentACL");

	/// <summary>FinancialAccount ("FinancialAccount")</summary>
	public static readonly Topics FINANCIALACCOUNT = new Topics("FinancialAccount");

	/// <summary>BusPositionInfo ("BusPositionInfo")</summary>
	public static readonly Topics BUSPOSITIONINFO = new Topics("BusPositionInfo");

	/// <summary>AccountingPeriod ("AccountingPeriod")</summary>
	public static readonly Topics ACCOUNTINGPERIOD = new Topics("AccountingPeriod");

	/// <summary>EmployeePersonal ("EmployeePersonal")</summary>
	public static readonly Topics EMPLOYEEPERSONAL = new Topics("EmployeePersonal");

	/// <summary>FoodserviceStudentMealCounts ("FoodserviceStudentMealCounts")</summary>
	public static readonly Topics FOODSERVICESTUDENTMEALCOUNTS = new Topics("FoodserviceStudentMealCounts");

	/// <summary>TermInfo ("TermInfo")</summary>
	public static readonly Topics TERMINFO = new Topics("TermInfo");

	/// <summary>Payment ("Payment")</summary>
	public static readonly Topics PAYMENT = new Topics("Payment");

	/// <summary>EmployeeWage ("EmployeeWage")</summary>
	public static readonly Topics EMPLOYEEWAGE = new Topics("EmployeeWage");

	/// <summary>FoodservicePurchaseTransaction ("FoodservicePurchaseTransaction")</summary>
	public static readonly Topics FOODSERVICEPURCHASETRANSACTION = new Topics("FoodservicePurchaseTransaction");

	/// <summary>Billing ("Billing")</summary>
	public static readonly Topics BILLING = new Topics("Billing");

	/// <summary>LearningStandardDocument ("LearningStandardDocument")</summary>
	public static readonly Topics LEARNINGSTANDARDDOCUMENT = new Topics("LearningStandardDocument");

	/// <summary>StudentContact ("StudentContact")</summary>
	public static readonly Topics STUDENTCONTACT = new Topics("StudentContact");

	/// <summary>StaffAssignment ("StaffAssignment")</summary>
	public static readonly Topics STAFFASSIGNMENT = new Topics("StaffAssignment");

	/// <summary>FoodserviceStudentEnrollmentCount ("FoodserviceStudentEnrollmentCount")</summary>
	public static readonly Topics FOODSERVICESTUDENTENROLLMENTCOUNT = new Topics("FoodserviceStudentEnrollmentCount");

	/// <summary>StudentSectionEnrollment ("StudentSectionEnrollment")</summary>
	public static readonly Topics STUDENTSECTIONENROLLMENT = new Topics("StudentSectionEnrollment");

	/// <summary>StudentPeriodAttendance ("StudentPeriodAttendance")</summary>
	public static readonly Topics STUDENTPERIODATTENDANCE = new Topics("StudentPeriodAttendance");

	/// <summary>CalendarDate ("CalendarDate")</summary>
	public static readonly Topics CALENDARDATE = new Topics("CalendarDate");

	/// <summary>TestAccommodation ("TestAccommodation")</summary>
	public static readonly Topics TESTACCOMMODATION = new Topics("TestAccommodation");

	/// <summary>FiscalYear ("FiscalYear")</summary>
	public static readonly Topics FISCALYEAR = new Topics("FiscalYear");

	/// <summary>LearningResourcePackage ("LearningResourcePackage")</summary>
	public static readonly Topics LEARNINGRESOURCEPACKAGE = new Topics("LearningResourcePackage");

	///<summary>Wrap an arbitrary string value in a Topics object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static Topics Wrap( String wrappedValue ) {
		return new Topics( wrappedValue );
	}

	private Topics( string enumDefValue ) : base( enumDefValue ) {}
	}
}
