// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using OpenADK.Library;

namespace OpenADK.Library.Infra
{
	///<summary>
	/// Defines the set of values that can be specified whenever a SIF_SIFNodeType
	/// is used as a parameter to a method or constructor. 
	///</summary>
	/// <remarks>
	/// Alternatively, the static
	///  <see cref="Wrap"/> method can be called to encapsulate any string value in
	///  a SIF_SIFNodeType object.
	/// <para>Author: Generated by adkgen</para>
	/// <para>Version: 2.5</para>
	/// <para>Since: 1.1</para>
	/// </remarks>
	[Serializable]
	public class SIF_SIFNodeType : SifEnum
	{
	/// <summary>SIF Agent ("Agent")</summary>
	public static readonly SIF_SIFNodeType AGENT = new SIF_SIFNodeType("Agent");

	/// <summary>Zone Integration Server ("ZIS")</summary>
	public static readonly SIF_SIFNodeType ZIS = new SIF_SIFNodeType("ZIS");

	///<summary>Wrap an arbitrary string value in a SIF_SIFNodeType object.</summary>
	///<param name="wrappedValue">The element/attribute value.</param>
	///<remarks>This method does not verify
	///that the value is valid according to the SIF Specification</remarks>
	public static SIF_SIFNodeType Wrap( String wrappedValue ) {
		return new SIF_SIFNodeType( wrappedValue );
	}

	private SIF_SIFNodeType( string enumDefValue ) : base( enumDefValue ) {}
	}
}
